### ISSUE TITLE
[SQL Lab] Add an alert in SQL Lab when results are limited

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#10330]
**Is your feature request related to a problem? Please describe.**
As a SQL Lab user, I would like to see a warning when rows returned by my query are limited and when exporting to CSV, so that I can prevent mistake / needing to re-export CSV. SQL Lab will currently add a limit (of 1M) on rows returned in the UI and when exporting to csv. 

**Describe the solution you'd like**
The feature request is to make it more visible that the rows are truncated, so that the user knows data they are exporting is not all data.

**Comment by yousoph** [comment]
Mocks for indicator & messaging: 

- When config DISPLAY_MAX_ROW is limiting the results: #13018  
- When config SQL_MAX_ROW is limiting the results for [admins](https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=90%3A281) and [non admins](https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=90%3A423)
- [When the limit dropdown is limiting the results displayed ](https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=90%3A1)
- [When the user has a limit in the query text itself that is limiting the results displayed](https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=90%3A140)

**Comment by eschutho** [comment]
this is great. Thanks @yousoph! What if more than one condition are true, like the limit dropdown and the limit in the query are both the same?

**Comment by Steejay** [comment]
thanks for bringing up this edge case @eschutho 

• When more than one condition are true for [admins](https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=133%3A70) and [non admins](https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=133%3A212)

For these conditions, the configuration in the message is always behind a tooltip. ie if [query = display_max_row](https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=135%3A333)

Reasoning: show what is visible in the UI first (query/dropdown) so that users can establish a visual relationship and use progressive disclosure to reveal additional matching limit constraints on the server side (configs). 


cc @yousoph

**Comment by Steejay** [comment]
We did consider a more generalized message like "The number of rows displayed is limited to 1 000 by more than one limit constraint" but opted for a more specific message for additional clarity. Thoughts?

**Comment by zuzana-vej** [comment]
End user doesn't know about DISPLAY_MAX_ROW or SQL_MAX_ROW and there is nothing they can do (besides contacting the admin). Do we want to expose this level of detail to them?

I think the messaging for when user limits in dropdown, or when user limits in query is great. When there is systems settings which admin (maintaining team) needs to config, I would think we can keep more generic message like one of these:

- It appears that the number of rows displayed is limited to 1000 by system configuration. 
- It appears that the number of rows displayed is limited to 1000 by system configuration. Contact your admin for more details.

Also do we need to word "It appears"? Or can we just say "The number of rows displayed is limited to 1000 by system configuration." The "It appears" make is sounds like we are not sure whether that's the case (and if we aren't sure then it appears is correct, if we are sure that this is limiting factor and query would otherwise return more results, we don't need "it appears".

**Comment by Steejay** [comment]
@zuzana-vej Thank you for the feedback! You bring up a great point. This is something we did consider and proposed that admins and non admins have different messages (see links attached in above messages).

![Frame 285 (1)](https://user-images.githubusercontent.com/60786102/107552554-8241b280-6b88-11eb-882a-a6f5dd65925c.jpg)
![Frame 284](https://user-images.githubusercontent.com/60786102/107552557-82da4900-6b88-11eb-944d-b3be76b57416.jpg)

re "It appears" copy. Yes great call out. This needs to be updated. Currently the system doesnt know if thats the case but we are doing the work to change that so that Superset _will_ know. I'll update the copy to communicate this more directly.

**Comment by zuzana-vej** [comment]
Sounds good yes the admin/non admin makes sense thanks for clarifying.
