### ISSUE TITLE
Shortlinks do not pass standalone=true param to the chart url

### ISSUE THREAD

**Issue by bkyryliuk** [apache/superset#10484]
Links like http://superset.com/r/2999&standalone=true get used to preserve standalone=true in the url, but doesn't anymore

Tested on the latest master

**Comment by etr2460** [comment]
@bkyryliuk i see you assigned this to yourself. Were you going to fix this?

**Comment by bkyryliuk** [comment]
I was planning to - but did not get a chance. Currently our team cannot spend time on superset :(

**Comment by rusackas** [comment]
What DOES seem to work in 2.0.1 (and probably other versions) is:
• Go to a dashboard
• Add the standalone param
• Create a permalink
The param is respected when accessing the permalink

What's NOT supported:
• Creating a permalink in with or without `standalone`
• Changing that value by appending the param to the permalink itself.

I would argue that a permalink shouldn't take params... it's intended to be a reflection of the dashboard in a particular state. You can create two permalinks, with and without the param, if that's what's needed.

It also might be worth noting that the structure of permalinks have changed since this ticket was opened. They now look like:
http://localhost:8088/superset/dashboard/p/5QJdyG2lVbm/

I think we can close this issue as "stale" at least, or "not a problem" at best. If people feel strongly this is a bug, let's re-open it! If it's a feature request, let's take it up again as a Discussion instead. 

Pinging @michael-s-molina to fact check me on all of this since I think there are more than one flavor of permalink supported by superset (which maybe we could simplify for 3.0!).
