### ISSUE TITLE
Customize superset, How to add a new number format(Indian number format) option in the charts.

### ISSUE THREAD

**Issue by piyush-singhal** [apache/superset#10559]
Hey Team, 

I am new to superset customization so need some guidance, I want to change the number format option available inside the chart, I want to add or modify existing format to indian number format. I will write the logic in javascript to change the original number to indian number format, but I don't know where to write my code for this.

Could you please guide me, how can I get it done. I found that superset is using D3 format and a superset-ui-number-format package is there for it. but next don't know how to modify it. Let me know if you need more information on this problem.

**Comment by etr2460** [comment]
You should be able to customize the locale of the number format by overriding the config in the NumberFormatterRegistry: https://github.com/apache-superset/superset-ui/blob/cdd6990092248b184c9c625d9caa66c3b79df8c3/packages/superset-ui-core/src/number-format/NumberFormatterRegistry.ts#L55

There's more details on customizing the number formatter here: https://github.com/apache-superset/superset-ui/blob/cdd6990092248b184c9c625d9caa66c3b79df8c3/packages/superset-ui-core/src/number-format/README.md#L11

Closing since this should allow you to do what you need

**Comment by adwaitpande11** [comment]
@piyush-singhal Have you successfully implemented the new number format? If so, can you please raise a pull request to master?
