### ISSUE TITLE
Y axis bar values are overlapping with each other in apache superset bar chart

### ISSUE THREAD

**Issue by piyush-singhal** [apache/superset#10662]
When I try to show the bar value in the bar chart of apache superset, y axis bar values overlap with each other.

To fix this issue, I want to rotate the y-axis values with 45 degree so that those values will look vertically and won't overlap with each other, just like it is there in x-axis values.

![image](https://user-images.githubusercontent.com/5344732/90985535-498e2c80-e59a-11ea-833d-a0abcdf3f9c8.png)

Can someone suggest me a way to fix this issue?

**Comment by Neel-rishabhsoft** [comment]
Still facing this issue. Please suggest any way to resolve this

**Comment by etr2460** [comment]
Hi @piyush-singhal, looks like there's no support for this yet. While this could probably be fixed through a change to the NVD3 plugin (https://github.com/apache-superset/superset-ui/tree/master/plugins/legacy-preset-chart-nvd3) we plan to migrate to echarts in the future and will track supporting this feature

I'm going to close this since there are no plans to fix this with the current nvd3 implementation. Feel free to open a PR to address this yourself and tag me for review if you want though!

**Comment by jayakrishnankk** [comment]
Isn't the plugin now moved to https://github.com/apache/superset/tree/master/superset-frontend/plugins/legacy-preset-chart-nvd3 ?

**Comment by jayakrishnankk** [comment]
The plugin is now moved to https://github.com/apache/superset/tree/master/superset-frontend/plugins/legacy-preset-chart-nvd3 .
