### ISSUE TITLE
when i execute oracle sql statements like update in SQLLAB, get "oracle error: not a query"  error

### ISSUE THREAD

**Issue by chuancyzhang** [apache/superset#10703]
### Expected results

it should be success.

### Actual results
get error  "oracle error: not a query"
![image](https://user-images.githubusercontent.com/23111194/91517359-28be3200-e920-11ea-902e-1935a0383d1c.png)

#### Screenshots

![image](https://user-images.githubusercontent.com/23111194/91517293-02989200-e920-11ea-8650-d5d4b12ccc18.png)

### Environment

(please complete the following information):

- superset version: `0.36.0`
- python version: `3.6`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this one out since
* It hasn't had attention in years, sadly
* It's in reference to an old version of superset that is no longer supported.
* There are insufficient details in the Issue description in order to properly reproduce and diagnose the issue.

If you're still facing this, let's open a new Issue with updated/repeatable reproduction steps using a newer version of Superset. Thanks!
