### ISSUE TITLE
[Explore] Educate users on table viz multi-sort

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#10730]
**Is your feature request related to a problem? Please describe.**
Currently the table viz only allows to sort based on 1 column.

**Describe the solution you'd like**
Ability to sort on multiple columns in the table vis. 
Example in this screenshot the 1st column is sorted (Z-->A) and then user needs the ability to sort the 2nd column, either ascending or descending. Currently the 2nd column is sorted randomly (US is last while UM is first). 
![Screen Shot 2020-08-29 at 2 43 43 PM](https://user-images.githubusercontent.com/61221714/91646682-a492aa00-ea06-11ea-9ea9-2493ebfe8bac.png)

It would be great to allow users to sort on up to 2-3 columns, similarly like tools like google spreadsheets, excel.

**Describe alternatives you've considered**
None

**Comment by zhaoyongjie** [comment]
@zuzana-vej In explore page, you can specify orderby options.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/2016594/91679596-62d74000-eb7b-11ea-820b-d71076f3f775.png">

**Comment by zuzana-vej** [comment]
Yes, thanks for the screenshot. The feature request from our users was for people who might not necessarily have permissions to edit the chart, who are either viewing the chart (table viz) in Explore, or on Dashboard, where it's possible to sort but only for 1 column.

**Comment by JunlinC** [comment]
🏷 chart

**Comment by zhaoyongjie** [comment]
@zuzana-vej you can rewrite table viz, adding this function, such as ag-gride-react.

**Comment by junlincc** [comment]
@zuzana-vej did Yongjie's suggestion solve this issue?

**Comment by ktmud** [comment]
Be careful with rewriting things from ground up. The table chart might be more complex than you think. Current table chart was overhauled only a couple of months ago. It took me about 3 weeks to bring it to full feature parity and comparable performance to the previous table chart that is based on [jQuery.Datatables](https://datatables.net/). We also had a failed attempt to replace it with another table library last year, which had to be reverted because of performance issues and edge cases.

The same library (react-table) has been the foundation of the new list view and there's also [ongoing work](https://github.com/apache/incubator-superset/pulls?q=is%3Apr+react-table+is%3Aopen) to replace almost all other tables within Superset with the same library. `react-table` is here to stay, at least in the near future. So I would strongly advice against bringing in yet another table library.

As to the feature request to this PR: actually, current table chart already supports multi-sort. It's just users have to do "Shift + Click". The library has an API to [override](https://react-table-omega.vercel.app/docs/api/useSortBy) this behavior (`isMultiSortEvent`). We can either add a control option to remove the requirement of shift + click, or add a tooltip to educate users about this behavior.

**Comment by zuzana-vej** [comment]
@junlincc no - I am not planning to rewrite anything. 
It looks like user education issue - we didn't know about "Shift + Click" so I think @ktmud's suggestion to add the tooltip will solve the users problem.

**Comment by junlincc** [comment]
resolved and closing in favor of https://github.com/apache-superset/superset-roadmap/issues/83
