### ISSUE TITLE
[CRUD VIEW] thumbnail not enabled

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#11523]
When I enable `ENABLE_REACT_CRUD_VIEWS` but not enable `THUMBNAILS`, dashboard (or chart) list will look like this:
<img width="1246" alt="Screen Shot 2020-11-02 at 1 10 15 AM" src="https://user-images.githubusercontent.com/27990562/97850285-aac43180-1ca8-11eb-809a-a15ed64c965d.png">

### Expected results

For data security reasons, many companies may not want to show thumbnails for charts/dashboard. It doesn't make sense to show thumbnails when there is no thumbnails. The `thumbnail view` control should be associated with THUMBNAILS feature flag, and only show this control when THUMBNAILS feature is enabled.

### Environment

master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @nytai @junlincc

**Comment by junlincc** [comment]
@benceorlai

**Comment by nytai** [comment]
@graceguo-supercat There is a feature flag that controls the default view for the listviews, `LISTVIEWS_DEFAULT_CARD_VIEW`. I think some users may still want the option to switch over to the card view, even if thumbnails are disabled. 

@dpgaspar raised an issue regarding the frontend making a lot of api requests for the thumbnails that are 404ing (due to the feature flag not being enabled). We should definitely not be making the api requests if the feature flag is not enabled, but I'm not sure we should disable the view completely.

**Comment by benceorlai** [comment]
@graceguo-supercat what is the nature of the security concern about thumbnails?

**Comment by graceguo-supercat** [comment]
for example, a chart's data is form a datasource that I do not have access. when i open chart list page, do i see the thumbnail/screenshot of the chart?

**Comment by graceguo-supercat** [comment]
> @graceguo-supercat There is a feature flag that controls the default view for the listviews, `LISTVIEWS_DEFAULT_CARD_VIEW`. I think some users may still want the option to switch over to the card view, even if thumbnails are disabled.
> 
> @dpgaspar raised an issue regarding the frontend making a lot of api requests for the thumbnails that are 404ing (due to the feature flag not being enabled). We should definitely not be making the api requests if the feature flag is not enabled, but I'm not sure we should disable the view completely.

That's what i experienced. I did not enable `LISTVIEWS_DEFAULT_CARD_VIEW`, i still see tons of requests to get thumbnails. No matter THUMBNAILS feature flag is enabled or not, I think it is necessary to have an option to disable card view.

**Comment by benceorlai** [comment]
@graceguo-supercat it seems to make sense to disable Thumbnails, however, I am not sure if it should be a systemwide setting (i.e. a flag) or a per-user setting or a permission. My concern with a flag base approach is that it turns off an important discoverability feature for users who otherwise would be able to see the charts. Any thoughts?

**Comment by graceguo-supercat** [comment]
@benceorlai Thanks for the reply. 
what is `an important discoverability feature for users who otherwise would be able to see the charts`. If you mean the chart image, that's probably the reason some company disable thumbnails feature, because we do not want users see chart image if they do not have permission. in cardview, it took 80% of page showing an identical placeholder, this also prevent users from discovering their own charts.

**Comment by nytai** [comment]
Carrying on the discussion from the meetup, let's try to explore a version of cards that's still useful even when thumbnails are not enabled. Disabling entire views because of a lack of thumbnails could lead to vastly different superset experiences which I  don't think is desirable. 

We could start by removing the entire thumbnail section and just render the bottom portion as a start, when `THUMBNAILS` feature flag is disabled.
<img width="524" alt="Screen Shot 2020-11-13 at 10 32 22 AM" src="https://user-images.githubusercontent.com/10255196/99118418-93841e80-259b-11eb-87be-0f28a297e672.png">


looping in @Steejay and @mihir174 for thoughts on a thumbnail free card

**Comment by junlincc** [comment]
https://github.com/apache/superset/pull/13683

**Comment by EVNIKHIL** [comment]
How to set the default listing style as Card view? Can anybody help
