### ISSUE TITLE
Scatterplot deck.gl, header of point size popup does not change when field is changed

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#11696]
When changing the point size field of a scatterplot deck.gl, the header of the popup menu does not get changed what can create confusion. 
### Expected results
When changing a field, the header should be updated accordingly
### Actual results
When changing a field the header does not change, but the query is constructed correctly. 

#### Screenshots

![2020-11-13_08-26-34 (1)](https://user-images.githubusercontent.com/58375897/99077478-ce318b00-258a-11eb-8c40-3fbd44cd55a2.gif)

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
to add on it, the dropdown is all messed up in the point size field. 
I can't think about a good candidate to work on these issues now, maybe it's time to open up tasks around data viz to the rest of team, since half of the charts have all sorts of different issues. @mistercrunch 
<img width="333" alt="Screen Shot 2020-11-13 at 8 04 28 AM" src="https://user-images.githubusercontent.com/67837651/99093091-e1daf280-2586-11eb-80d7-2d83e9c6e528.png">

**Comment by rusackas** [comment]
Closing this as a "won't fix" not because the issue is invalid... I'm sure it is. Closing because this DeckGL plugin needs a LOT of love. This work is not prioritized at the moment (though we're taking volunteers and will happily review PRs!). This issue hasn't gotten traction in over a two years, and is probably just a minor detail on a major overhaul that needs to be roadmapped.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/812905/213310488-d0b3e5fb-314d-4dcc-919e-e93fc06e0df6.png">

The above is basically a design system travesty. CC @kasiazjc and @jess-dillard to put this somewhere on their mental radar, in hopes that we can one day revisit the control panel layouts in this area.
