### ISSUE TITLE
[chart]: linechart unable to scroll tooltip to see highlight when SERIES LIMIT is large

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12030]
Expected behavior: 
when user hover on a specific line/group in line chart, user can see highlight of the selected group in tooltip. 
<img width="1321" alt="Screen Shot 2020-12-13 at 9 05 44 PM" src="https://user-images.githubusercontent.com/67837651/102042605-1c52cd80-3d87-11eb-9d33-ca7747414c2c.png">

Issue: 
when Series Limit is large, tooltip overflows and users have no way to scroll and view all

Actual result: 
user can not see the highlight of selected group/line when it is not in the view. 
<img width="1347" alt="Screen Shot 2020-12-13 at 9 10 59 PM" src="https://user-images.githubusercontent.com/67837651/102042841-badf2e80-3d87-11eb-823e-4d31636c0676.png">

**Comment by rusackas** [comment]
This is still an issue with the Legacy NVD3 chart, but since that is on the path to deprecation with the advent of the ECharts Line Chart and the Generic Chart Axes implementation (behind a feature flag now, but not for long), I'm going to close this as a "won't fix". If anyone sees reason to re-open this, I'm happy to.
