### ISSUE TITLE
Columns list are not updated on chart editor after updating SQL Query on Edit Dataset

### ISSUE THREAD

**Issue by zsellami** [apache/superset#12170]
### Expected results

After updating a query on the edit Dataset by adding alias or other columns in the query of a Table Chart or any other type of chart (screen 1) I expected to have the list of these columns on the Query Option (screen 2)  

### Actual results
The list of available columns are not updated after editing the query of the datasource of the chart.

#### Screenshots
screen 1
![Screenshot_20201222_100139](https://user-images.githubusercontent.com/22955406/102870360-394d6780-443d-11eb-8d68-dc61a9da88df.png)

screen 2
![Screenshot_20201222_100236](https://user-images.githubusercontent.com/22955406/102870389-410d0c00-443d-11eb-827a-2f103e458cbf.png)

### Environment

(please complete the following information):

- superset version: `0.38`
- python version: `3.6.9`
- database : postgres
- web browser : firefox or chrome

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by eugeniamz** [comment]
You are right, after SAVE the columns should be automatically updated. 
The workaround to resolve the issues is to save the new virtual dataset and then sync the columns. 
I explain it in a [video](https://youtu.be/8rKk727UM7s) here

**Comment by kamalkeshavani-aiinside** [comment]
I faced the same issue today in Superset 1.0.0. Although I can see from Euginea's video, that it is expected behavior that user needs to 'Sync' columns again after saving the changes to dataset, but I would still say the flow can be improved.

I am not sure how heavy is the task of columns sync, but I guess one way could be to always sync columns when a change in dataset(change in SQL or change to/from physical-virtual) is saved.

**Comment by rusackas** [comment]
Agreed this flow could probably be smoothed out significantly (cc @jess-dillard @yousoph) since the "sync columns" button is not very discoverable since it's not visible on that tab, and arguably you might just want to sync columns automatically when editing the underlying query. That said, proposals to change this would be a new feature, and a good thing to open in the Ideas area of the Discussions tab. This particular issue is quite stale, and the feature works as originally designed, so I'll close it for now.

**Comment by mvilrokx** [comment]
For those looking for the "sync columns" button, it is [explained in the documentation](https://superset.apache.org/docs/frequently-asked-questions/#what-if-the-table-schema-changed) (and yes, this is still neccesary)
