### ISSUE TITLE
Multiple tables join queries to produce a single chart

### ISSUE THREAD

**Issue by zpi1223** [apache/superset#12203]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the business department has requirements change, the previously prepared single Table cannot be required (N tables need to be combined). In view of this situation, data can only be processed manually at present, and then feedbacks can be made to the business department.

**Describe the solution you'd like**
Whether we can consider to realize this function in the future: multiple tables can be aggregated to generate a Charts.

**Describe alternatives you've considered**
For Chart production, you can select multiple tables and add a drop-down list for association selection (left/right/full join...)..
After the selection, the filter consolidation is passed to the back end for data query.This is just my preliminary idea.If thank you, welcome to discuss and exchange.

**Comment by Mhs-Aaron** [comment]
@altef  I wonder if you are interested in this topic, or if you can help me with @ related personnel.Thank you

**Comment by nytai** [comment]
You should be able to achieve this via a SQL view, or by forming your query in SQL Lab and then clicking “explore”

**Comment by Mhs-Aaron** [comment]
@nytai Later I went to try the way you said, but at the moment our SQLLab or only the admin can operate, so in view of the scene I said, can't let business people operating on a graph, it would greatly increase the workload of the admin staff, if SQLLab open to business people, they do not have time to learn the relevant operation is grammar, this is to let a person helpless.

**Comment by zpi1223** [comment]
@amitmiran137 I'd like to know why you closed this issue. Do we have any plans for this issue in the future?

**Comment by amitmiran137** [comment]
For the time being in order to perform sql join between tables is via a virtual dataset which can be create from the sqlLab screen.

And yes you need to be familiar with SQL.
If you would like

I think it  can be nice to have to support conjuring a join between multiple tables from the explore page  but I don't see it prioritized higher with other critical taks among superset commiters .

If you would like to write a detailed SIP that have accurate definitions on how it would work especially on the frontend wide (explore page) this would help promoting this 
But someone would also need to implement that 


cc: @villebro @betodealmeida  any thoughts here ?

**Comment by betodealmeida** [comment]
I mention this briefly in https://github.com/apache/superset/issues/14909, but I would like to improve the semantic layer of Superset so that we can define relationships between tables within Superset. But this would be for simple many-to-one or one-to-one relationships between 2 tables only, so that if you're exploring a fact table (say, `sales`) you can filter or group by user attributes (`age`, eg) automatically joining by `user_id`.
