### ISSUE TITLE
[Dashboard] Chart dropdown list should overflow

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12281]
### Before
<img width="1310" alt="Screen Shot 2021-01-05 at 9 24 07 AM" src="https://user-images.githubusercontent.com/27990562/103678949-0de87380-4f39-11eb-9bf5-e2de81ec1c38.png">

### Current

<img width="1254" alt="Screen Shot 2021-01-05 at 9 31 44 AM" src="https://user-images.githubusercontent.com/27990562/103678968-1640ae80-4f39-11eb-93eb-dd8206655a27.png">

#### How to reproduce the bug

1. Open dashboard, with a few charts in a row
2. Click on dropdown icon on each chart title

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Note, this regression was introduced a couple of month ago. 

@junlincc @zuzana-vej

**Comment by zuzana-vej** [comment]
Related to this issue: https://github.com/apache/incubator-superset/issues/12004

**Comment by junlincc** [comment]
https://github.com/apache/superset/pull/12153 this open PR should fix both #12004 and #12281
we tested, spotted some other issues in Dashboard but not related. do you feel comfortable merging this PR? 
@graceguo-supercat

**Comment by maloun96** [comment]
Tested with the latest code from master.

![Kapture 2021-01-06 at 14 32 07](https://user-images.githubusercontent.com/8277264/103769749-87fa2480-502d-11eb-9d4b-26409861acf9.gif)

**Comment by junlincc** [comment]
confirmed, this issue has been fixed by  @maloun96 https://github.com/apache/superset/pull/12169
<img width="1802" alt="Screen Shot 2021-01-07 at 6 32 28 PM" src="https://user-images.githubusercontent.com/67837651/103967381-bef83500-5116-11eb-9e81-fa507486169f.png">
<img width="1322" alt="Screen Shot 2021-01-07 at 6 31 43 PM" src="https://user-images.githubusercontent.com/67837651/103967384-c1f32580-5116-11eb-8b82-9f255bab0997.png">
<img width="1785" alt="Screen Shot 2021-01-07 at 6 31 20 PM" src="https://user-images.githubusercontent.com/67837651/103967387-c3245280-5116-11eb-92d5-772f973aac40.png">
