### ISSUE TITLE
[cosmetic][explore] Filters popup on Explore - confusing UI experience

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12294]
## Screenshot

![Screen Shot 2021-01-05 at 3 52 06 PM](https://user-images.githubusercontent.com/61221714/103712203-0a231400-4f6e-11eb-8bd2-c8b8779dca82.png)

![explore-where](https://user-images.githubusercontent.com/61221714/103712051-ae588b00-4f6d-11eb-99ed-6ba77dcc4cd0.gif)

## Description

The behavior of the new filter dropdown specifically for "IN" condition is a bit confusing:

## Design input
1. when user wants to remove an item they click on the "check mark" rather than a "cross" - this seems confusing
2. when adding new values, user needs to carefully click out within the filter box to be able to see the save button

Note: the screenshot is based on master as of 12/17/2020 so there is a possibility this has been addressed in the meanwhile.

**Comment by junlincc** [comment]
we can make that work~!

**Comment by michael-s-molina** [comment]
@junlincc We have some decisions to make. 

Let's start with item 1:

The check mark is a pattern adopted by AntD and actually it makes sense when you analyze the context. Look at the following picture:

<img width="378" alt="Screen Shot 2021-01-06 at 9 24 13 AM" src="https://user-images.githubusercontent.com/70410625/103768269-f7a5ea80-5000-11eb-9f01-3c8b1e2acf07.png">

This filter has value suggestions and the check mark is indicating which of these suggestions are selected. It gets a little strange when we don't have suggestions enabled (`Autocomplete Filters` disabled in dataset config) because only the selected items appear. So we have two options: leave as it is or hide the dropdown when the suggestions are disabled. Like this:

<img width="336" alt="Screen Shot 2021-01-06 at 10 30 24 AM" src="https://user-images.githubusercontent.com/70410625/103773700-3a1ff500-500a-11eb-8b57-403c8a64bebd.png">

To resolve item 2 what we can do is limit the height of all select items and create the necessary space to accommodate the options. Like this:

<img width="375" alt="Screen Shot 2021-01-06 at 9 12 13 AM" src="https://user-images.githubusercontent.com/70410625/103774295-18733d80-500b-11eb-8da4-feb3b9bf5d26.png">
<img width="373" alt="Screen Shot 2021-01-06 at 9 12 37 AM" src="https://user-images.githubusercontent.com/70410625/103774302-1ad59780-500b-11eb-83a5-eb8d393ca252.png">
<img width="369" alt="Screen Shot 2021-01-06 at 10 54 26 AM" src="https://user-images.githubusercontent.com/70410625/103776002-98020c00-500d-11eb-9531-0d3569db0f79.png">
<img width="367" alt="Screen Shot 2021-01-06 at 10 48 22 AM" src="https://user-images.githubusercontent.com/70410625/103775458-d5b26500-500c-11eb-9b44-0b2f888c6791.png">
<img width="369" alt="Screen Shot 2021-01-06 at 10 59 08 AM" src="https://user-images.githubusercontent.com/70410625/103776459-3db57b00-500e-11eb-9c62-d79f2786aa24.png">

If I had to choose between higher selects on top of buttons vs scrolled selects with buttons always visible I would choose the first one. In fact we have a bunch of selects that cover some part of the UI when they are open.

Let me know what you think 😉

**Comment by junlincc** [comment]
1. @zuzana-vej this styling comes with the AntD component which I also agree that the design makes sense within context. This component is also being used in Native dashboard filter and other places in the future. the effort of changing it in Explore is relatively low, but keeping the consistency across the product will be hard. Can we simply hide the check marks for now, and revisit general issue in the near future?

**Comment by zuzana-vej** [comment]
Thanks for the details. Also I m not a designer I found that confusing and wasn't sure if it's bug or as-designed. I think in the first case as explained by @michael-s-molina the checks make complete sense. The only thing that is weird is that when you click on the check the item unselects. But this might be less confusing if the suggestion is enabled. Is this disabled across for everyone or is this setting per dataset or setting per Superset installation? (if you know the answer if now we can look into it). - I am okay to keep it and we can see if users have other reactions or feedback.

For point 2 we can also keep what we have and see users reactions or feedback.

**Comment by junlincc** [comment]
Discussed with @michael-s-molina, any changes here could introduce regression in other areas. To ensure we meet Superset 1.0 release timeline, we need to hold off on making suggested changes. We also spotted related issues in Dashboard, and will provide a general solution based on your user reactions and feedback for all in Q1.  @zuzana-vej 

replacing `p1 `tag with `hold!`
