### ISSUE TITLE
[Explore]deck.gl latitude dropdown appears behind the popover 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12309]
affecting Scatterplot, Arc, Grid, Screen Grid

<img width="1789" alt="Screen Shot 2021-01-06 at 9 47 47 AM" src="https://user-images.githubusercontent.com/67837651/103802602-43a65e80-5004-11eb-9395-c0f0a87dd4a9.png">

This is issue is NOT introduced by recent https://github.com/apache/superset/pull/12258
Thanks for spotting it @geido

**Comment by geido** [comment]
This is caused by the menuPortalTarget using the document body as a target for the single-choice dropdowns and the z-index of the popover being too high. The menuPortalTarget option was set for the multi-choice dropdowns already which suffered from the same issue when used within the popover. I am going to tackle this one for both single and multi-choice dropdowns.
