### ISSUE TITLE
[Explore] Users should be able to clear custom label for adhoc metric

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12380]
#### Screenshots

<img src="https://user-images.githubusercontent.com/335541/104086441-ff39df00-520c-11eb-8d92-0b9cea2e6935.gif" width="600">

#### How to reproduce the bug

1. Add an adhoc metric, give it a custom label
2. Try clear the custom label
3. The label should revert to the default auto-generated label, instead of reverting to the already-cleared custom label.

### Environment

Latest master.

This is in table chart's percent metrics.

**Comment by junlincc** [comment]
Confirming this issue is resolved in latest master 01/09/2021 @ 10:58am (UTC)

Remaining related issues will be addressed by rc2 
[[Explore] Custom labels for new adhoc metric should be empty](https://github.com/apache/superset/issues/12379)
[[Explore] Saved metrics label overrides not working](https://github.com/apache/superset/issues/12375)
cc @graceguo-supercat @ktmud @zuzana-vej @mistercrunch
