### ISSUE TITLE
[sql_lab]Display Rows Returned / Clarify when LIMIT is reached

### ISSUE THREAD

**Issue by eschutho** [apache/superset#12436]
**Is your feature request related to a problem? Please describe.**
- Users can't easily understand how many rows their query returned
- Users can't easily tell when the SQL Lab LIMIT is reached, so they don't know if they are only seeing a partial result set. This leads to users accidentally exporting partial datasets to CSVs

**Describe the solution you'd like**
Show rows returned in south pane of sql lab when they run a search

(https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=90%3A71)

**Comment by eschutho** [comment]
@S-YOU can you help with designs?

**Comment by junlincc** [comment]
@eschutho 
thanks for filing the issues, could you please follow the label guideline below, and use [sql_lab] as issue prefix, thanks! 

_As you might have noticed, all labels(212 total) are now specified with prefix and color-coded by types and product area.
By tagging the right labels, you can help us more efficiently sort, identify and prioritize issues, questions, and PRs, ultimately helping us build a better product for the community!

https://github.com/apache/incubator-superset/labels?page=5&sort=name-asc

Here are some labels applying rules we recommend the community to follow -
select one label describing the product area (e.g. install:dependencies, viz:explore:savemodal, viz:chart:nightingale)
if you are reporting a bug, select a label describing the specific type of bug (cosmetic, performance, regression)
if you are using the enhancement request, use enhancement: committed to indicate you are working on this request, otherwise use enhancement: request
if you are working on a raised issue that needs more details or other inputs, etc., use the label starting with need: (e.g., need: screenshot)
some labels are 'reserved' for a small group of people who actively maintain the repo and direct resources. 1. assigned:_____ 2. attn:blocking and attn:rush 3. P0, P1, P2_

**Comment by eschutho** [comment]
> @eschutho
> thanks for filing the issues, could you please follow the label guideline below, and use [sql_lab] as issue prefix, thanks!
> 
> _As you might have noticed, all labels(212 total) are now specified with prefix and color-coded by types and product area.
> By tagging the right labels, you can help us more efficiently sort, identify and prioritize issues, questions, and PRs, ultimately helping us build a better product for the community!
> 
> https://github.com/apache/incubator-superset/labels?page=5&sort=name-asc
> 
> Here are some labels applying rules we recommend the community to follow -
> select one label describing the product area (e.g. install:dependencies, viz:explore:savemodal, viz:chart-nightingale)
> if you are reporting a bug, select a label describing the specific type of bug (cosmetic, performance, regression)
> if you are using the enhancement request, use enhancement: committed to indicate you are working on this request, otherwise use enhancement: request
> if you are working on a raised issue that needs more details or other inputs, etc., use the label starting with need: (e.g., need: screenshot)
> some labels are 'reserved' for a small group of people who actively maintain the repo and direct resources. 1. assigned:_____ 2. attn:blocking and attn:rush 3. P0, P1, P2_

@junlincc I don't have access to create labels, but thanks for the heads up. Are you proposing an issue prefix in addition to the label? If so, maybe we can mention that in the issue template. That could help guide people.

**Comment by junlincc** [comment]
agree! will get to it soon! @eschutho

**Comment by Steejay** [comment]
wanted to share this mockup here that shows a row returned indicator with additional info upon hover. I positioned the indicator under the results tab since it has a direct relationship with the result table. 

The indicator displays w a success check icon when the row returned matches the limit dropdown or the limit specified in the query w a tooltip that adds context.

The indicator displays with a warning icon when the row returned _does not_ match the limit dropdown w a tooltip that describes why.  ie "The number of rows displayed is limited by the flag DISPLAY_MAX_ROWS = 1000".

![Frame 254](https://user-images.githubusercontent.com/60786102/106502182-e5409480-6478-11eb-9e07-4814ea5a9282.jpg)

![Frame 255 (1)](https://user-images.githubusercontent.com/60786102/106503021-ffc73d80-6479-11eb-8750-1dafbe2684a0.jpg)

cc @yousoph @tooptoop4 @himanshpal @ramyarajasekaran

**Comment by tooptoop4** [comment]
@Steejay if less rows than limit returned does it show the number returned?

**Comment by Steejay** [comment]
@tooptoop4 yes. anytime a query runs successfully there will always be a row returned indicator. here is another exploration that exposes the copy so that it does not rely on hover and hopefully simplifies the logic a little more.

_row indicator_ shows anytime a query successfully runs
_warning_ shows anytime the result is limited from the server side (config)
_message_ shows anytime the result is limited by something from Superset  (config, limit dropdown, query)

![Frame 285](https://user-images.githubusercontent.com/60786102/106528219-45493200-649d-11eb-9c38-e184dbf51623.jpg)

**Comment by yousoph** [comment]
Thanks @Steejay ! I like the indicator + messages in the second exploration you shared 

cc @zuzana-vej as well, this is related to #10330 that you raised

**Comment by Steejay** [comment]
Figma spec: 
https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=90%3A0

**Comment by yousoph** [comment]
Let's use this issue to just add the number of rows returned, ie x rows returned (https://www.figma.com/file/5db2MpaKNnC1c7MK9ysdeV/SQL-Limit-Indicator?node-id=90%3A71) 

Related follow up tickets to add the additional indicators and messaging: 
#13018 and #10330

**Comment by zuzana-vej** [comment]
Most of the feature described in this GH# was addressed; there is one more case (I don't want to unnecessarily open a new GH# for it) which is about displaying a warning when user clicks "Download CSV" if there is a limit applied - oftentimes people click on download CSV with the default limit of 1000 and then have to rerun the query again. (let me know if new GH# should be opened specifically for this request).
