### ISSUE TITLE
[Dashboard] native filter and dashboard edit mode

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12486]
## Screenshot

A couple of cosmetic issues with dashboard edit mode and native filters:

<img src="https://user-images.githubusercontent.com/335541/104417246-e9d4f580-5529-11eb-9ca9-f2e4e4e80c5a.png" width="800">

Card controls is cramped with the native filter container.

![Snip20210112_126](https://user-images.githubusercontent.com/335541/104417315-04a76a00-552a-11eb-877f-bcfee8c16c6f.png)

Drop indicators are a little off. Both position-wise and length-wise.

![Snip20210112_127](https://user-images.githubusercontent.com/335541/104417345-0ec96880-552a-11eb-8924-abe61a206e04.png)

**Comment by kkucharc** [comment]
Hi @ktmud as you mentioned fix: [row component handler is visible #12498](https://github.com/apache/superset/pull/12498) addresses the first issue with icons. I just added PR for the rest.

I've got 2 additional questions.
1. I am wondering if this indicator line is in correct place?
![Screenshot_2021-01-18_at_18_03_16__2_](https://user-images.githubusercontent.com/2536609/104947200-ad871680-59bb-11eb-886d-1b7e6aa8033d.png)

2. Should this right indicator behave like this (disappear only when we move cursor to the top or bottom?)
![Large GIF (1068x574)](https://user-images.githubusercontent.com/2536609/104947583-43bb3c80-59bc-11eb-9935-7a40a4dc0957.gif)

**Comment by junlincc** [comment]
@kkucharc thank you for the additional questions. 
1. the line should start to show when the card border gets very close to the row or column, instead of half way through.
2. i believe not. users should be always seeing either 1) one vertical line on the left to indicate the row position, 2)one horizontal line on the top to indicate the column position, 3)or top horizontal + left vertical line together(top left corner) to indicate card's exact position.. but again, should lines should show when card gets close, not half way through.

<img width="1792" alt="Screen Shot 2021-01-18 at 10 14 43 AM" src="https://user-images.githubusercontent.com/67837651/104950720-0a5fde00-5976-11eb-8ce0-c108f9d2d8e2.png">

ktmud thoughts?

**Comment by junlincc** [comment]
1. I am wondering if this indicator line is in correct place?

The line should show when the top of the card is getting close to the row, and when the left side of the card is getting close to the column, instead of half way through

2. Users should be 1. only seeing one horizontal line to indicate the row position. 2.only seeing one vertical line to indicate the column position. 3. one horizontal line + one vertical line on the left that create top left corner to indicate the exact position. 
but again, line shows when the border of the card gets close, not half way through. I believe. 

ktmud thoughts? 
<img width="1109" alt="Screen Shot 2021-01-18 at 10 16 58 AM" src="https://user-images.githubusercontent.com/67837651/104951388-40ea2880-5977-11eb-9822-771190681f2d.png">

**Comment by ktmud** [comment]
1. The indicator line preferably should show at least below the bottom border of the current tab. 
2. The indicator line should only show at where the container will be places when users release the drag & drop. Therefore the right indicator should not display if releasing the dragged component does not put it into the right column.

**Comment by kkucharc** [comment]
I will open separate PRs for those improvements just to make those changes small and easy revertable.
