### ISSUE TITLE
Add docs for the new time/date filters

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12500]
**Is your feature request related to a problem? Please describe.**

#11418 added a bunch of [custom date functions](12408) but there is no documentation on how to use them. 

**Describe the solution you'd like**

We should add a user-tutorial page in https://superset.apache.org/ on how to use the new time picker. Explaining:

1. The definition of Previous/Last periods
2. Free text shortcuts, e.g. "now: last 7 days"
3. Custom time functions
4. Anchor for relative dates

**Comment by junlincc** [comment]
it's currently WIP!

**Comment by rusackas** [comment]
While this isn't well-covered in the Superset docs, it is covered a bit in the [Preset docs](https://docs.preset.io/docs/time-configurations).

Also, while the time range selector covers most use cases pretty well, it's acknowledged that the UI needs a revamp. @kasiazjc and @lauderbaugh are looking into this and gathering data points, along with others. 

Some of the nomenclature/tooltips in this UI have been updated a few times since this issue was created, which hopefully helps at least _a little_. 

Given the above, @ktmud do you think this needs to remain open as an issue? I wonder if it'd be better suited as an Ideas discussion than an Issue (i.e. bug), but I'm curious your thoughts.

**Comment by rusackas** [comment]
Closing this since it's not a bug, it's quite stale, and there are numerous ways to contribute or request changes on docs these days.
