### ISSUE TITLE
[dashboard]cancel creating native filter confirmation(edge case)

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12645]
Scenario:
Go to native filter
add 2 filters and save
Open edit modal again and add new filter (without filling data) and delete name of first filter
Cancel edition - confirm you want to lost your changes

_Originally posted by @adam-stasiak in https://github.com/apache/superset/issues/12554#issuecomment-764007447_

**Comment by rusackas** [comment]
This seems to be lacking a bit of detail/screenshots, so I'm a little confused by this report. That said, a LOT has happened in filters since this was filed, so I'll assume by the radio silence that this has been worked out. If anyone sees this problem resurfacing in currently supported versions of Superset, let's re-open and add clarifying details!
