### ISSUE TITLE
[explore][discussion]short & long term solutions for displaying truncated info in Explore and Dashboard

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12640]
We had naming rules for metrics, so that many metrics have same prefix. In the adhoc filter dropdown list, it only shows same prefix, there is no way for our users to pick the right metric from dropdown list:

<img width="1175" alt="Screen Shot 2021-01-20 at 5 42 54 PM" src="https://user-images.githubusercontent.com/27990562/105268664-77769d80-5b47-11eb-8b2a-12e1593dfd18.png">

### Expected results

Should add hover effect or tooltip for every item in the dropdown list.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @junlincc

**Comment by zhaoyongjie** [comment]
Hi, @graceguo-supercat 
There is a resize icon available to zoom in and out the metric(and filter) popover.

![image](https://user-images.githubusercontent.com/2016594/105269504-067ac880-5bcf-11eb-92bf-d48f279b9f38.png)

**Comment by ktmud** [comment]
I'm pretty sure 90% of users would not think of using that resize button when they see truncated options.

**Comment by junlincc** [comment]
Then the question becomes, how to teach Superset users this new pattern. feature tutorial and on boarding are absolutely areas that we have room to improve. 

As we made all Explore components resizable, including data panel, data table, charts, control panel and popovers, users should have much greater flexibility operating in Explore than ever before, so I think it might worth users time learning and adapting to this enhanced pattern. Happy to hold a training session with your users to introduce all the new features in Explore and get immediate feedback from them. 

I'm not sure adding tooltips everywhere to show truncated information is the best UIUX. If you can think of any better ideas, please let us know

**Comment by graceguo-supercat** [comment]
> Then the question becomes, how to teach Superset users this new pattern. feature tutorial and on boarding are absolutely areas that we have room to improve.
> 
> As we made all Explore components resizable, including data panel, data table, charts, control panel and popovers, users should have much greater flexibility operating in Explore than ever before, so I think it might worth users time learning and adapting to this enhanced pattern. Happy to hold a training session with your users to introduce all the new features in Explore and get immediate feedback from them.
> 
> I'm not sure adding tooltips everywhere to show truncated information is the best UIUX. If you can think of any better ideas, please let us know

I agree this. There are so many different users with different usage patterns, and some users may just use it once per a few month. You can't rely on one-time education or training.

**Comment by junlincc** [comment]
Feature tutorial and user guide are  definitely something we should start incorporating to the product. I will see what I can do in Explore.

**Comment by zuzana-vej** [comment]
Expecting users to resize this every single time they open the Metrics popup is unreasonable expectation. 

On the tutorial / education piece I agree there is space for improvement. One idea users suggested in the past is have some kind of "since you last visited" or "since last release" where they can have a summary. I am personally not convinced if this would be used (I never use this feature in other products) but we could explore this option a bit.

**Comment by mihir174** [comment]
I think there is room for this popover to be wider horizontally by default. I agree that it's unreasonable to manually expand every time. I think hovering for tooltips might get frustrating when combined with scrolling + scanning through a big list. What's a string character length that we'd want to fit into the menu without truncation?

**Comment by graceguo-supercat** [comment]
before we come up a perfect solution, will [title attribute](https://www.w3schools.com/tags/att_global_title.asp) be a simple solution?

**Comment by ktmud** [comment]
> before we come up a perfect solution, will [title attribute](https://www.w3schools.com/tags/att_global_title.asp) be a simple solution?

+1 title attribute should be the default in most places with potential truncation. I remember my job as a junior frontend engineer 10 years ago was adding "title" in a lot of places.

**Comment by junlincc** [comment]
if we do go with the solution of adding title attribute or tooltip, that will have to happen systematically, which takes time. 
the fastest/easiest solution will be increasing the width of popover by default. I remember the longest title you gave me is about 50 character long, to be safe, should we bump it to fit 70 character by default? @mihir174

**Comment by graceguo-supercat** [comment]
`increasing the width of popover` is stick to a fixed width, which probably still not guarantee all the cases. 

Same issue happens in dataset panel, user can not see the full metric name. You will see that even as wide as data panel with max width, a lot of metric names still get truncated.
<img width="581" alt="Screen Shot 2021-01-21 at 9 23 52 AM" src="https://user-images.githubusercontent.com/27990562/105387592-8eaa9f00-5bca-11eb-9460-6c3017fe16e2.png">

(Note: a couple of days ago the data panel can show horizontal scrollbar, but this behavior is changed now.)

**Comment by mihir174** [comment]
Agreed that all cases won't ever be guaranteed. My thought is we can increase the width so that more cases are covered and fewer will need to be treated with a title attribute. 

I also wanted to bring up truncation again - will it be more useful if metrics are truncated in the middle? I've noticed that many long metrics differ towards the end of their strings. Like so -
<img width="228" alt="Screen Shot 2021-01-21 at 9 49 03 AM" src="https://user-images.githubusercontent.com/64227069/105390440-e72f6b80-5bcd-11eb-9ab9-df8fe6f01cd5.png">

**Comment by graceguo-supercat** [comment]
Did you notice it also offers tooltip for the full name?
<img width="763" alt="Screen Shot 2021-01-21 at 9 54 26 AM" src="https://user-images.githubusercontent.com/27990562/105391145-abe16c80-5bce-11eb-9d6f-90a37335d7a8.png">

**Comment by zuzana-vej** [comment]
@graceguo-supercat  can you confirm if this has been resolved (and close this ticket if resolved)? Looks like there are PRs  linked here and last discussion in January.

**Comment by rusackas** [comment]
This might be a little heavy-handed and optimistic, but I think since the tooltips in the left pan have been broadly changed, and hopefully things are humming along well enough nowadays. Also we haven't heard any other input on this thread in quite some time, so it doesn't seem to be a hot-button issue and we can consider it "stale" in github terms. If anyone feels differently, perhaps we can open a design discussion in Ideas, speak synchronously, or re-open this with updated context if warranted.
