### ISSUE TITLE
[explore] Tooltip displays twice for Metric

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#12671]
## Screenshot
Issue 1: metric definision (logic) displays twice
![Screen Shot 2021-01-21 at 5 06 30 PM](https://user-images.githubusercontent.com/61221714/105431750-1fa16a80-5c0b-11eb-83ba-21022bcae95d.png)

Issue 2:metric description (text) displays over the definition (logic) - probably the logic should not appear in this case
![Screen Shot 2021-01-21 at 5 08 12 PM](https://user-images.githubusercontent.com/61221714/105431981-92aae100-5c0b-11eb-93ac-8006101d5dd8.png)

## Description

On chart Explore, sometimes the tooltip - metric definition (logic) - displays twice - I noticed it when user moves mouse from left to right. Another issue, if the metric definition (logic) displays and then user hovers over the (i) to see description, the description displays over the metric definition. Shouldn't the definition in this case disappear?

## Design input
Straightforward fix I believe as described in description

**Comment by junlincc** [comment]
For issue 1 - after changing label, description in Change dataset modal, i can see that  both tooltips display the sql expression. 
Expected behavior: 
1. the tooltip on top is supposed to display the complete label(especially when metrics label is truncated), instead of sql expression. 
2. mouse away label should make this top tooltip disappear 

<img width="940" alt="Screen Shot 2021-01-22 at 6 50 53 PM" src="https://user-images.githubusercontent.com/67837651/105566775-d58bb800-5ce2-11eb-86f1-b7d65baab469.png">

@zhaoyongjie @graceguo-supercat

**Comment by ktmud** [comment]
I'll vote for replacing the top tooltip with HTML `title` attribute of the full metric label (`verbose_name || metric_name`)
