### ISSUE TITLE
[explore] Dropdowns tooltip icon jumping when mouse is on label

### ISSUE THREAD

**Issue by adam-stasiak** [apache/superset#12689]
## Screenshot

https://user-images.githubusercontent.com/25153919/105512024-e7645f80-5cd0-11eb-80b6-e52abcacb445.mov

## Description

Tooltip icon blinks and jump when I put mouse on these fields.

Steps to reproduce:
Add chart with multiline viz type
Go to Y Axis Left section and put mouse on dropdowns

I would expect to not see this jumping - no action when mouse is on text/field and tooltip displayed when mouse on tooltip icon.

**Comment by michael-s-molina** [comment]
@junlincc Can you assign this to me? I'm working on it.

**Comment by michael-s-molina** [comment]
@adam-stasiak @junlincc I think this was already fixed because when running on master version this is how this control looks like:

<img width="318" alt="Screen Shot 2021-05-05 at 1 09 34 PM" src="https://user-images.githubusercontent.com/70410625/117173543-41ca8d00-ada3-11eb-84b5-ab34c6876f72.png">

Can you confirm that the bug is gone?

**Comment by rusackas** [comment]
This is still possible if the label reaches a certain length, and the tooltip span suddenly appears next to it on hover. A little absolute positioning should fix this. I'll open a PR with my idea and see if it works...

**Comment by michael-s-molina** [comment]
@rusackas Ok. Thanks. Don't forget to tag this PR to automatically close.
