### ISSUE TITLE
[chart]Apache Superset Deck.GL Multiple layer map bug

### ISSUE THREAD

**Issue by Geethanjali11** [apache/superset#12805]
### Expected results
Multi layer map with  coordinates near Houston.
[Multiple layer bug.zip](https://github.com/apache/superset/files/5885653/Multiple.layer.bug.zip)
### Actual results
Multi layer map with coordinates fixed on san Francisco sample data and is inflexible with any dataset change
what actually happens. 0 rows are being fetched.
#### Screenshots
![image](https://user-images.githubusercontent.com/78130557/106106817-19ac0c00-616c-11eb-9c64-60d8051fe1ad.png)
#### How to reproduce the bug

1.Upload the attached csv file . Open add new chart . Go to 'deck.gl multiple layers'
2. Click on 'scatter plot'

### Environment
- superset version: `Version: 0.999.0dev`
### Additional context
Please find attached the dataset used.

**Comment by VSZM** [comment]
Also why is it not possible to customize the individual layers?

**Comment by rusackas** [comment]
Closing this since it's one day shy of being inactive for two years. Good news is, I've managed to make a multiple layer chart as recently as yesterday. Bad news is, DeckGL plugins are massively in need of support, so PRs of any sort are welcome in this area.

**Comment by Yisel-Hernandez** [comment]
Good afternoon everyone.

What happens is that I am trying to filter a multi-layer graph.

Does anyone have an idea of ​​how I could do so that as the graphs that make up the multi-layer graph are filtered, it is also filtered with the changes of the other graphs?

The idea I had was in the same dashboard to add the graphs that make up the multi-layer graph, but only the graphs are filtered separately but it does not affect the multi-layer graph in any way.
