### ISSUE TITLE
Page routing does not respect next parameter

### ISSUE THREAD

**Issue by mayurnewase** [apache/superset#12834]
When I enter chart url directly without logging in,ui redirect to login page keeping chart url in 'next' parameter.
After logging in it redirects to homepage ignoring that url.
### Expected results
Should go to url which was used before logging in.

#### How to reproduce the bug
log in
open any chart,copy its url from address bar
log out
enter that url in address bar
log in,you would see homepage

**Comment by rusackas** [comment]
This seems to be working just fine in newer versions of Superset. Closing as fixed.

**Comment by rusackas** [comment]
Hmmmm... not sure what version I was using when I wrote that. I may well have been testing `master` at the time inadvertently. If that's the case, then it should be resolved in the 2.1 release, and can be tested on the latest release candidate. I'll try to do that when time allows. I'll leave this closed for the moment since we tend to close our issues based on merge rather than official version releases. If this is still happening on `master` or in 2.1.x, I'll happily re-open :)

**Comment by ryshoooo** [comment]
> Hmmmm... not sure what version I was using when I wrote that. I may well have been testing `master` at the time inadvertently. If that's the case, then it should be resolved in the 2.1 release, and can be tested on the latest release candidate. I'll try to do that when time allows. I'll leave this closed for the moment since we tend to close our issues based on merge rather than official version releases. If this is still happening on `master` or in 2.1.x, I'll happily re-open :)

Sorry for the spam, I thought we were just using pure Superset as is, but we are using quite a bit of custom configuration, which actually overwrites the default behavior for the /login/ view and ignores the `next` query parameter, which is why I was getting this behavior. So I actually don't know if it's still happening in Superset as I'm not really running Superset's code for this part, it probably works fine.
