### ISSUE TITLE
[table]save sort order of table column when saving/overwriting chart

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13085]
Currently in table chart, there is no way to save sort order of a column when saving the chart. 

Feature request: save column sort-by when saving(over-writing) a table chart. 

https://user-images.githubusercontent.com/67837651/107725141-63334580-6c9a-11eb-8d72-3d353dba1292.mov

**Comment by rusackas** [comment]
Since this hasn't seen any traction for almost two years, I'll reluctantly close it, noting that there's at least a workaround for the chart author of using the Sort By input field, and thereby saving that sorting as part of the query itself. If others want to see this as a feature, let's add it as an Ideas discussion.
