### ISSUE TITLE
[Explore]extra white space in dropdown list

### ISSUE THREAD

**Issue by junlincc** [apache/superset#13159]
## Screenshot

https://user-images.githubusercontent.com/67837651/108106215-7ea7a300-7042-11eb-889f-6e57f85aba68.mov

## Description

See extra white space in Bubble chart, Series and Entity dropdown.

**Comment by junlincc** [comment]
@ktmud is it related to https://github.com/apache/superset/pull/12649?

**Comment by ktmud** [comment]
Looks like your column type icons are missing:

<img width="247" alt="column-type-icons" src="https://user-images.githubusercontent.com/335541/108113916-f7136180-704c-11eb-91f6-a6f0953c5920.png">

My guess is you will see the same extra space in other viz types, too.

It is most likely because these calculated columns didn't have a data type set when created:

<img width="957" alt="no-data-type" src="https://user-images.githubusercontent.com/335541/108114341-891b6a00-704d-11eb-8f31-c0da3e611fd0.png">

Or their data types were not one of the three:

<img width="205" alt="not-one-of-the-three" src="https://user-images.githubusercontent.com/335541/108114463-ac461980-704d-11eb-98b5-538ddf2fe233.png">

**Comment by junlincc** [comment]
gotcha! thanks for explaining. closing this issue and will address it along with https://github.com/apache/superset/issues/12961
