### ISSUE TITLE
[explore] BigQuery DatabaseError surfaced as UnknownError with bad formatting 

### ISSUE THREAD

**Issue by mistercrunch** [apache/superset#13155]
BigQuery error is hard to read.

### Expected results

In Explore, when creating a bad expression (say `DATE_TRUNC(column_that_dont_exist, DAY)`) in BigQuery, the DatabaseError is shown as a UnknownError. In SQL Lab, DatabaseErrors are surfaced properly and make sure to use a monospace font so that the formatting is preserved. For most database, the formatting doesn't matter much, but for BigQuery it's important to preserve it.

#### Screenshots

In explore (where the issue shows)
<img width="1098" alt="Screen Shot 2021-02-16 at 8 02 26 AM" src="https://user-images.githubusercontent.com/487433/108088556-74c77500-702d-11eb-8034-dd9f46d8eed6.png">

In SQL Lab, where it's better formatted
<img width="1307" alt="Screen Shot 2021-02-16 at 8 04 41 AM" src="https://user-images.githubusercontent.com/487433/108088726-a6404080-702d-11eb-9421-ca0ca276faeb.png">

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
