### ISSUE TITLE
[Global] Revisit open menu on hover

### ISSUE THREAD

**Issue by ktmud** [apache/superset#13257]
We DON't have to change the current behavior, just creating an issue in case this comment got slip through the cracks.

---

@rusackas I'm finding a case where hovering to show menu might have become an inconvenience:

https://user-images.githubusercontent.com/335541/108138715-6439ed80-7073-11eb-8233-e56ef5a99322.mp4

When saving chart, I wanted to click on the "Save" button, but if I move the mouse too fast, it will trigger open the hover menu and when I moved back to the position of the "Save" button and click, I would accidentally click on the menu and lost all my changes to the chart---which is quite annoying.

I'm wondering if we can:

1. Increase the size of the run button area---it could use a little bit more margin around the buttons.
2. Move SQL lab to the second menu item so the hover menu doesn't overlap with the buttons.
3. Add a delay to open the menu on hover?

to avoid users accidentally clicking on the hovered menu item. We can do one or all of these if they make sense to you.

cc @junlincc @mihir174

_Originally posted by @ktmud in https://github.com/apache/superset/issues/12025#issuecomment-780207617_

**Comment by junlincc** [comment]
@ktmud
All make sense, what i was thinking is to  move run button to the bottom, move save to top right corner, once we simplify and reorganize the controls?

<img width="1591" alt="108141052-da405380-7077-11eb-9586-2e24e57bd0d9" src="https://user-images.githubusercontent.com/67837651/108633525-7c21c080-7429-11eb-8c0b-3d7e6b6c5ee4.png">

**Comment by rusackas** [comment]
In the long term, I'm a fan of @junlincc 's proposal... just moving to SIP-34's layout.

In the meantime, there are probably other places one might overshoot with the mouse and run into similar issues.

Option 2 is reasonable enough, but I'm not sure it will solve the problem in other areas. 

Option 3 is intriguing to me... we could do it with JS, or we might be able to do it with a little CSS like [this little demo](https://codepen.io/rusackas/pen/ZEBXKVb) I just scratched together.

**Comment by ktmud** [comment]
@rusackas CSS delay looks cool. I did some testing and felt 250~300ms is the most comfortable.

**Comment by junlincc** [comment]
"When creating/editing a chart, the save button lines up underneath a drop down to navigate to SQL Lab. The hover area that expands the drop down is pretty large. If a user (me) wanted to save their work on the chart (I did), they might inadvertently trigger the hover to expand the drop down and click through to the SQL editor losing their work on the chart (doh! it happened to me).
It's obviously not a huge deal. Maybe the hover could only be over the text instead of the area or the save button could be moved or a warning could allow the user to cancel navigating away from a chart with unsaved changes." 

cc @steejay we have an open ticket to track this issue. ^

**Comment by cooley-pe** [comment]
For what it's worth I would prefer to replace "open on hover" with "open on click". Open on click is a pretty common pattern in other apps and would prevent accidental menu opens. Hope this is the right place to share this kind of feedback/opinion.
