### ISSUE TITLE
Superset UI is doesn't escape / quote the search query and currently is not working with special characters 

### ISSUE THREAD

**Issue by bkyryliuk** [apache/superset#13708]
### Expected results
Superset UI e.g. should escape query search parameter for superset objects like charts, dashboards etc
Expected api call:
/api/v1/report/related/dashboard?q=(filter:%27[query]%27,page_size:2000)
![image](https://user-images.githubusercontent.com/5727938/111812538-75099900-8895-11eb-99b6-395070cf4134.png)

Actual API call:
https://superset.pp.dropbox.com/api/v1/report/related/dashboard?q=(filter:[query],page_size:2000)

![image](https://user-images.githubusercontent.com/5727938/111812598-83f04b80-8895-11eb-9633-0d06ecba6582.png)

#### How to reproduce the bug

1. open superset search 
2. search for `[query]`
### Environment

https://github.com/airbnb/superset-fork/tree/release--2021-03-10

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @dpgaspar , @villebro

**Comment by nytai** [comment]
This seems like a rison encoding as all calls should be going through `rison.encode`, we may have to fork and make updates to that lib

**Comment by rusackas** [comment]
@bkyryliuk is this still an issue?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by nicmrayce** [comment]
Hi @rusackas , just to let you know that apparently, Superset doesn't seem to escape the special characters again when filtering action is attempted.

One of our column values in our dataset has a single quote `'` character and it causes error across all charts when that option is picked.

An example here:
![quote_error](https://github.com/user-attachments/assets/1aa356bb-962d-465b-a407-73ecc32b148c)

And so the only quickest way we could think of is to perform the SQL REPLACE function in order to remove any possible occurrences single quote ' character.

And everything works as usual again:
![quote_removed](https://github.com/user-attachments/assets/5be1d986-8b64-405e-b119-9b0a33db5842)

However, the issue is the user may still have the tendency to type in their own value which may/may not contain special characters (we may never know as we can't predict user behavior).

Therefore, may I suggest considering an option called `'Disabled typing input/user input'` into the Superset filter options? This would allow us to have proper control over the possibility of user trying to type in weird characters into the filter.
![feature_suggestion](https://github.com/user-attachments/assets/e972409e-2110-4bbb-bcb2-d12b8e17f9f9)
