### ISSUE TITLE
1.0.1 change dataset cause https error

### ISSUE THREAD

**Issue by wenerme** [apache/superset#13768]
### Expected results
change dataset works

### Actual results / Screenshots
![image](https://user-images.githubusercontent.com/1777211/112275858-070d0980-8cbb-11eb-9d64-b249ce37bf34.png)
![image](https://user-images.githubusercontent.com/1777211/112275408-8bab5800-8cba-11eb-90cf-8fbef7340c56.png)

#### How to reproduce the bug

1. use https
2. change dataset

### Environment

(please complete the following information):

- docker images amancevice/superset:1.0.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

* related 

https://github.com/apache/superset/issues/12592

__http works__.

**Comment by junlincc** [comment]
@ktmud ^^ don't think it's related to your change, but you might have the answer. 🙏

**Comment by ktmud** [comment]
https://github.com/apache/superset/issues/12592  Could this be related?

**Comment by wenerme** [comment]
I thinks this is the same cause of #12592 , maybe same fix can solve this problem.

**Comment by junlincc** [comment]
@nytai can you confirm fix(dashboard|chart): use correct url for favorite_status and change … #13557 fixed this issue? closi

**Comment by nytai** [comment]
@junlincc I doubt that PR fixed this issue, but it is essentially the same problem. Superset is being served over https (likely by nginx or another proxy), however the superset webserver is likely not aware of it so it is returning http redirects. The fix is to make the superset server aware that it is being served over https. https://github.com/apache/superset/issues/12592#issuecomment-789172313 should fix this
