### ISSUE TITLE
[explore] Metric tooltip is necessary for long metric names

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#13821]
## Description
For long metric names, the tooltip can't be displayed, because the (i) which on hover displays the tooltip is out of range. The tooltip doesn't display the metric name (just the description)

For long metrics, this is hard to use - because users don't know what metric to select if they all start with the same substring.

Users need a way to see the full metric name on hover for metrics which are cut off in the Metrics Dropdown on chart explore page.

## Screenshots
![Screen Shot 2021-03-26 at 12 48 34 PM](https://user-images.githubusercontent.com/61221714/112686063-a7396e80-8e32-11eb-8d34-11639bfe2d4b.png)

**Comment by junlincc** [comment]
@mihir174 can we make the enlarge icon louder? for now as a workaround.. i understand this is not gonna solve the problem....

**Comment by ktmud** [comment]
I think we can just make the dropdown full-width with this antd option: `dropdownMatchSelectWidth`

**Comment by mihir174** [comment]
Some other solutions in addition to full width dropdown:
![Slice 4](https://user-images.githubusercontent.com/64227069/113056657-eb917b00-9160-11eb-9ad8-92969340f62e.png)
A - The hover area is the whole menu item
B - The (i) persists and we truncate just a few characters earlier
C - Full width dropdown (@ktmud)

I like A since users it won't demand much user precision to view the entire metric name. C might create awkward looking lists with a lot of white space if there's a large variance between metric character lengths. 

I also think that the resize icon shifts the buttons to a pretty awkward alignment. Resize cursors on the edge should suffice to indicate that the popover can be enlarged. Also unsure if there's a need for vertical resizing.
![Slice 3](https://user-images.githubusercontent.com/64227069/113056670-f0eec580-9160-11eb-9130-0f4c21d16c08.png)

**Comment by zuzana-vej** [comment]
https://github.com/apache-superset/superset-ui/pull/1066
