### ISSUE TITLE
Move to monaco-editor

### ISSUE THREAD

**Issue by rumbin** [apache/superset#13838]
### Current situation
There are several open issues that are related to the code editor, e.g. 
#12429
#9990

Switching to [monaco-editor](https://github.com/microsoft/monaco-editor) has been discussed several times and was mentioned as a post-1.0.0 task: #10254, #10267, #12423.

### Suggested change
Switch to monaco-editor, the editor behind VS Code.

Personally, I have worked with websites using this editor (dbt Cloud, dataform) and feel that it works very well.

### Alternative
Stick with the current editor or consider others.

**Comment by rumbin** [comment]
I'd like to raise this issue again.
I just gave a Superset/SQL training to our users and I could see how they were unhappy about the Ace editor.
Some even resort to different tools like the Snowflake web frontend for this reason.

**Comment by villebro** [comment]
@betodealmeida thoughts?

**Comment by betodealmeida** [comment]
@villebro I think we should give it a try (I also mention it in [SIP-68](https://github.com/apache/superset/issues/14909)).

**Comment by ktmud** [comment]
I plan to work on this this year.

**Comment by srinify** [comment]
Any thoughts on CodeMirror? @ktmud @rumbin 

https://blog.replit.com/code-editors#head-to-head

**Comment by ktmud** [comment]
@srinify Thanks for sharing the analysis! It seems their main reason of switching to CodeMirror 6 is that Monaco doesn't support mobile and they need to support a lot of languages. I don't think mobile support for code editing is that important for Superset so I'm still leaning towards Monaco for it's richness of config options and best-in-class autocompletion.

**Comment by srinify** [comment]
Ah interesting

**Comment by rusackas** [comment]
Anyone on this thread still have the intent to carry this forward and own the task? Wondering if whether should keep this open, convert this to a Discussion as a feature idea if we're looking for new volunteers, or close it if there's no longer any steam behind the initiative.

**Comment by rumbin** [comment]
This task exceeds my coding capabilities by far, but I'd assist with testing and discussion, if needed.

It would be so useful to switch to an editor that behaves like many of our users are used to from VS Code.

**Comment by ktmud** [comment]
Sorry for not carrying this forward. Had some priority shift internally and got pulled into other projects. Feel free to convert this into a discussion as it is a feature request and I think we now generally keep feature ideas as discussions.

If we ended finding a volunteer to work on this, I'd be happy to help with code review still.

**Comment by rusackas** [comment]
It's been another year since anything has happened on this thread. I think we should close this out as inactive/stale as well as because it's a feature request rather than a bug, per se (even if it would solve other reported issues). If anyone wants to pursue this, I think it might warrant a SIP or at least a discussion thread for lazy consensus, but there are indeed plenty of reasons to consider it. Say the word if you want to contribute and want any help in the process to make it happen!

**Comment by rumbin** [comment]
@rusackas I neither have the skills nor the capacity to make this happen. But still I feel that switching to Monaco editor would be a huge step forward for Superset/SQLLab.

**Comment by rusackas** [comment]
I don't imagine it'd be easy, but you're welcome to start a Discussion or take it to Slack and try to recruit interested parties around it, if you want to help make it happen :D

**Comment by chintanp** [comment]
I think closing this as "Completed" is incorrect. If it tracked elsewhere, then it is fine.as otherwise this is still a major issue as far as usability of Superset is considered. Code Editor is a very important requirement and the current editor is fairly buggy to be not useful. Please suggest alternatives, if possible.

**Comment by rumbin** [comment]
@chintanp our users are, to be honest, resorting to Snowflake's Snowsight web UI, as they are frustrated with SQLLab's editor.
Furthermore, we are using Grafana for time series charts if raw data and for histogram and CDF distribution charts. The OSS Grafana Snowflake connector is now using the Monaco editor...

 So these are our unpleasant workarounds.

**Comment by rusackas** [comment]
Admittedly, I default to "completed" more often than I should, rather than selecting the other issue methods... I'll try to be better about that.

Nonetheless, if anyone wants to replace Ace Editor with something better, we're all for a SIP proposal to detail the UI changes/challenges, alternatives considered, and technical/migration plan. Just open an Issue ith the SIP template and you can spearhead that project.

Otherwise, if there are issues with the current editor making things unusable, we'd love to see those filed as issues so we can tackle them, whilst other grand plans are being scaffolded.

CC @yousoph @betodealmeida @eschutho @justinpark who might care about such a project.

**Comment by betodealmeida** [comment]
I'd love to see this, but I'm currently working on SIPs 85, 95, and 117. Hopefully someone can take this work.
