### ISSUE TITLE
Allow enable/disable  Alerts and Reports frontend by user

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#13856]
**Is your feature request related to a problem? Please describe.**
Superset `Alerts and Reports` is a good feature. We want to enable it in airbnb but we have performance, security and stability concerns, so at this moment we just want to open it to a few selected users before make it available to thousands of users.

Superset offers `GET_FEATURE_FLAGS_FUNC` to enable/disable features by selected user. So here are config that i tried to enable `Alerts and Reports` for selected users (**Note** I have set other necessary `CELERYBEAT_SCHEDULE` and SMTP related config):

1.  `ALERT_REPORTS = False` for all users, but enable selected users by `GET_FEATURE_FLAGS_FUNC`. Result: No users can see `Alerts & Reports` menu.
2.  `ALERT_REPORTS = True` for all users, but disable all other users in `GET_FEATURE_FLAGS_FUNC`, only allow selected users pass. Result: feature is enabled for selected users, but other users will still see `Alerts & Reports` option from the dropdown. But when they click on it, they got 404 error.

**Describe the solution you'd like**
I am not sure this is a feature request or a bug fix for use `ALERT_REPORTS ` flag. Could we have a feature flag just used to enable front-end (show `Alerts and Reports` option and related records)?

cc @nytai @dpgaspar @zuzana-vej

**Comment by nytai** [comment]
The issue here is that the alerts/reports menu item is controlled via a permission and the route existence is based on the feature flag, so this creates an issue when enabling this for only certain users.

- If the feature flag is conditionally set, the permission does not exist and the menu item will no be there. 
- If the permission is set for all users, but the feature flag is conditionally set, all users will have the menu option but the route will 404 for some. 

This issue is not isolated to this feature, it is an issue for all routes that are conditionally enabled based on feature flag. 

One solution is to generate the permission for all users, but hide the menu item in the frontend. The users will still have direct access to the feature via the url, but the link will be hidden. I'm wondering if @dpgaspar has any other ideas as this issue is related to FAB permissions.

**Comment by dpgaspar** [comment]
Like @nytai said, at the app bootstrap, the routes get registered on Flask. Routes that get registered depending on a feature flag won't get unregistered if the feature flag mutates during a request, for example depending on the user that made the request.

The menu REST endpoint result depend on the registered menus and the user's permission to them, this depends dynamically on the user that made the request and his permissions.

A possible way, don't know if it feasible on Airbnb:
By default Alerts & Reports permissions are added to all roles, further roles can be created like AlphaNoAlertReports, GammaNoAlertReports and be given to those users. This can be done programatically, has well has the user registration to these roles

**Comment by graceguo-supercat** [comment]
Hi @dpgaspar In airbnb we didn't really use much of Superset `roles`. In airbnb we had a few thousands of users in hundreds of teams/organizations, we do not want Superset to manage extra `roles` for permission or access control. So everyone is `Alpha` or `Admin` role.

**Comment by zuzana-vej** [comment]
Related to https://github.com/apache/superset/issues/13954

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people (cc @john-bodley) are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
