### ISSUE TITLE
[csv] allow csv cell with separate line

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#13879]
**Is your feature request related to a problem? Please describe.**
We have a lot of users who want to upload csv format data into Superset. But currently Superset's csv parser only accept _comma separated_ content.

**Describe the solution you'd like**
Right now modern tools (like Excel etc) can parse more complicated content. According to CSV standard https://en.wikipedia.org/wiki/Comma-separated_values:
`More sophisticated CSV implementations permit them, often by requiring " (double quote) characters around values that contain reserved characters (such as commas, double quotes, or less commonly, newlines).`

Could we improve CSV support, which allows line break in the cell (use double quote around cell values)?

**Comment by junlincc** [comment]
Thanks for the request! 
@yousoph This seems to be helpful and relatively small effort. I think we should include this in roadmap?

**Comment by john-bodley** [comment]
It seems that Hive does not support multiline fields per https://stackoverflow.com/a/48764063. CSV files are notoriously troublesome and thus I wonder if we should: 

1. Have a mechanism within Superset to convert them to JSON and use the JSON row format (per the JsonSerDe ) as described. [here](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL).
2. Add a form for uploading of JSON files directly, given if we implement (1) we would be able handle/store JSON files. 

The one question/caveat is the CSV upload form is based on a FAB form and thus was wondering whether the whole import (from CSV, JSON) etc. should be modernized in React.

**Comment by villebro** [comment]
At the risk of going deep into a rabbit hole, I'm almost curious to understand why Hive doesn't support multiline CSV. I remember having worked with CSV importers on a JVM project a while ago, and the standard commons CSV handled even the wackiest CSVs just fine (I assume Hive uses this library for CSV import/export). So instead of fixing this downstream, perhaps we could open an issue on the Hive Jira and see if something can be done about this upstream?

**Comment by john-bodley** [comment]
Actually per [this](http://www.dbaglobe.com/2018/02/example-to-load-csv-with-newline.html?m=1) example using the Parquet format (as opposed to a text file) may resolve the problem. There are likely additional wins since the binary Parquet format should be significantly more performant from
a retrieval perspective than storing the data as a text file and parsing the CSV via the opencsc SerDe.

Note this change would serve as a perquisite for https://github.com/apache/superset/issues/14020.
