### ISSUE TITLE
[Design]Import chart/dashboard UI icon is misleading

### ISSUE THREAD

**Issue by krsnik93** [apache/superset#13920]
## Screenshot

![image](https://user-images.githubusercontent.com/13034472/113347164-b0dc3e00-932c-11eb-9ab9-3aa992a605a0.png)

## Description

Superset uses a "download" type icon for importing chart/dashboard. Problem is compounded by the absence of text next to the icon, as seen for creating a chart immediately to the left of it.

Instead of using a "download" icon (https://fontawesome.com/icons?d=gallery&p=2&q=download), Superset should be using either an "upload" icon (https://fontawesome.com/icons?d=gallery&p=2&q=upload) or an "import" icon (https://fontawesome.com/icons?d=gallery&p=2&q=import).

Adding a text label should be considered as well.

**Comment by junlincc** [comment]
<img width="1448" alt="Screen Shot 2021-04-01 at 4 15 19 PM" src="https://user-images.githubusercontent.com/67837651/113363351-7ad79380-9305-11eb-8b1d-165b85d3fc14.png">

not only the icon is confusing. it's not aligned with 2 buttons 😅

cc @rusackas @steejay

**Comment by Steejay** [comment]
Thanks for this feedback @krsnik93. Agreed, the icon should at least have a tooltip to help w understanding the action. We found some examples that interchanged some of the common icons associated with the dualities: export/import and download/upload. While selecting this icon we wanted to make sure that its opposite action (export) had an icon that was the inverse so that the relationship between the 2 was clear from purely a visual standpoint. With that being said we should take a further look into this to help clarify the action. Thank you @krsnik93 !

<img width="181" alt="Screen Shot 2021-04-01 at 5 19 06 PM" src="https://user-images.githubusercontent.com/60786102/113366553-6055e800-930e-11eb-9f22-7ad580cae0a7.png">

**Comment by krsnik93** [comment]
I see your point with wanting to have icons paired. However, just from these 2 screenshots, icons should at least be switched, so from:

- download icon representing import button (my screenshot)
- upload button representing export button (your screenshot)

to:

- download icon representing export button
- upload button representing import button

**Comment by Deninc** [comment]
Hi guys, what is the app version of this? I'm using 1.1.0 and there's no import button.

**Comment by rusackas** [comment]
Closing this as stale. 

CC-ing @jess-dillard @kasiazjc to provide a data point on the confusion that interpreting these icons may cause (it's not the first time I've heard it). 

Also, to answer @Deninc or anyone else encountering the "where even ARE these icons?" question, they show up when the `VERSIONED_EXPORTS` flag is turned on (which I'd highly recommend).
