### ISSUE TITLE
[JINJA]Filterbox should support alias columns

### ISSUE THREAD

**Issue by pkdotson** [apache/superset#13942]
The filterbox currently has not mapping when a user uses an alias for columns for example:

```SELECT  num_boys as from_value,  num_girls as to_value, name as the_name from birth_names```

When the user creates a virtual dataset in sql lab the mapping to the alias names gets lost because the original columns aren't passed in from SQL Lab. This in turn returns a incompatible filter to the filter indicators as shown from below:

<img width="1189" alt="Screen Shot 2021-04-01 at 1 06 12 AM" src="https://user-images.githubusercontent.com/17326228/113455156-c8fc9d80-93be-11eb-8fd2-00462ae4f690.png">

**Describe the solution you'd like**
During dataset creation from sql lab editor we need to save the original column as well as the aliases. We need a way to map these two.

cc: @zhaoyongjie 

**Describe alternatives you've considered**

**Additional context**

**Comment by zhaoyongjie** [comment]
![image](https://user-images.githubusercontent.com/2016594/113512951-bee2c680-9599-11eb-9df8-c72e8c6982a6.png)

Since virtual dataset and physical dataset is different dataset, 1) we shoud create the filterbox via the virtual dataset instead of physical dataset, 2) If we need to affect the virtual dataset by creating a filterbox on the physical dataset, I need to change the virtual dataset subquery.

cc: @junlincc @pkdotson

**Comment by rusackas** [comment]
Filterbox is deprecated and will be gone in 4.0. I'll close this out unless anyone wants to open a PR for legacy versions.
