### ISSUE TITLE
Google Sheet Error no such table: https://docs.google.com/spreadsheet/....

### ISSUE THREAD

**Issue by jessicaxyl** [apache/superset#13949]
My Google Sheet is already set as anyone with the link can view it. I can query and display results from the google sheet URL in Superset's SQL Editor, but once I clicked "explore" and it opens up a new tab for creating a chart, I have this error of no such table, and I can't create any chart. I've also tried to link the Google Sheet URL by creating a new dataset (physical) and it's still the same, can't create a chart. Anyone knows what I need to do? Btw, I followed the steps from here as well https://preset.io/blog/2020-06-01-connect-superset-google-sheets/
![image](https://user-images.githubusercontent.com/81961241/113563910-14bb7b00-963b-11eb-87b5-1b07ecee1190.png)

**Comment by srinify** [comment]
@betodealmeida are these instructions still relevant in the Google Sheets blog post? Should we instead point people to your new library (shillelagh) and update the post?

**Comment by jessicaxyl** [comment]
Hey @srinify @betodealmeida @junlincc , any updates on this?

**Comment by yairzack** [comment]
facing the same exact problem. I downloaded superset localy using docker and followed the same blog post.

**Comment by musthak24** [comment]
Facing same issue

**Comment by NgxHaiiDanx** [comment]
I'm facing the same issue although i still can query data from Gsheet. Is this normal?

**Comment by betodealmeida** [comment]
@NgxHaiiDanx can you create a ticket at https://github.com/betodealmeida/shillelagh/issues and share the spreadsheet URL so I can take a look?

**Comment by pavlozt** [comment]
Most likely you installed shillelagh incorrectly. You need to point the variant of shillelagh package .

That is, in docker mode, you should add this line to the file docker/requirements-local.txt :
shillelagh[gsheetsapi]

**Comment by rusackas** [comment]
Is anyone on this thread still facing this issue, or is it OK if we close this one due to inactivity?

**Comment by stevensuting** [comment]
This is probably caused by an interpretation loss created by this [tutorial](https://preset.io/blog/2020-06-01-connect-superset-google-sheets/), this issue is caused when you only install `gsheetsdb`

You need to install.
`pip install 'shillelagh[gsheetsapi]'`

See this [doc](https://github.com/betodealmeida/shillelagh#installation)

**Comment by rusackas** [comment]
Indeed that tutorial works (I just tried it the other day!), so I'll close this issue as solved or stale, since both seem to be the case :) If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
