### ISSUE TITLE
Import dashboard can import multiple times

### ISSUE THREAD

**Issue by samtfm** [apache/superset#14005]
When importing a dashboard, the dashboard will import multiple times if you click the button multiple times before the modal closes.

#### Screenshots

![Screen Shot 2021-04-07 at 3 12 04 PM](https://user-images.githubusercontent.com/12817097/113941304-b36ae780-97b3-11eb-8c5a-c5460d7560c5.png)
![Screen Shot 2021-04-07 at 3 14 18 PM](https://user-images.githubusercontent.com/12817097/113941446-f200a200-97b3-11eb-8722-5de4eb0aba77.png)

#### How to reproduce the bug

1. Go to the Dashboards list view
2. Click the import button in the top right corner (to the right of + Dashboard)
3. Select jinja json dashboard file, and then repeatedly click the import button.
4. The dashboard has now been imported multiple times

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
