### ISSUE TITLE
Allow override of label name for saved metrics

### ISSUE THREAD

**Issue by cooley-pe** [apache/superset#14595]
**Is your feature request related to a problem? Please describe.**
Being able to save metrics for a dataset is awesome! But sometimes I want to tweak the label for a particular context. e.g. `user_count` -> `active_user_count`.

**Describe the solution you'd like**
You can already override metric names for **Simple** or **Custom SQL** metrics. It would be great if you could do that for **Saved** metrics as well. Something like:

![Untitled drawing](https://user-images.githubusercontent.com/64038793/118052906-70fb7400-b338-11eb-95fd-9f7817aeccc8.png)

**Describe alternatives you've considered**
n/a

**Comment by rusackas** [comment]
This seems like it's still an issue, but I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still concerned with this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
