### ISSUE TITLE
Unable to clear default value in native select filter

### ISSUE THREAD

**Issue by villebro** [apache/superset#14713]
### Expected results

When setting a default value to a select filter and clearing it, the `extraFormData` isn't cleared. This is happening because AntD form isn't able to set a nested object to empty, but rather leaves the old one in place. See a related discussion here: https://github.com/ant-design/ant-design/issues/8806#issuecomment-379543118

what you expected to happen.

### Actual results

what actually happens.

#### How to reproduce the bug

Add a default value:
![image](https://user-images.githubusercontent.com/33317356/118826590-4a06ea00-b8c4-11eb-8b8c-d3b66ffdbb44.png)

Remove default value:
![image](https://user-images.githubusercontent.com/33317356/118826544-3eb3be80-b8c4-11eb-9610-b05e40f3fe5c.png)

When going back to the dashboard, notice how the filter state is empty, but it's trying to apply `extraFormData` to charts:
![image](https://user-images.githubusercontent.com/33317356/118826676-5c812380-b8c4-11eb-8d70-521e2087ee08.png)

Check Redux and see, that `extraFormData` was not reset to an empty object, despite having been updated by `setDataMask`:
![image](https://user-images.githubusercontent.com/33317356/118826399-23e14a00-b8c4-11eb-82d7-09ffe1f20559.png)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment]
@villebro After investigation I found that the problem happens because of the way `rc-field-form` handles the objects comparison in `src/utils/valueUtil.ts`:

```
function internalSetValues<T>(store: T, values: T): T {
  const newStore: T = (Array.isArray(store) ? [...store] : { ...store }) as T;

  if (!values) {
    return newStore;
  }

  Object.keys(values).forEach(function (key) {
    var prevValue = newStore[key];
    var value = values[key];

    var recursive = isObject(prevValue) && isObject(value);
    newStore[key] = recursive ? internalSetValues(prevValue, value || {}) : value;
  });
  return newStore;
}
```

Since we're setting the property value to an empty object, the `Object.keys(values)` will return empty and the old value will be returned.

Investigating more, I found these issues in Ant Design Github:

https://github.com/ant-design/ant-design/issues/30212
https://github.com/ant-design/ant-design/issues/28314
https://codesandbox.io/s/antd-reproduction-template-forked-mghsg?file=/App.jsx

This behavior is by design. To fix the problem we should use `setFields` instead of `setFieldsValue` in `superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/utils.ts`

```
form.setFieldsValue({
    filters: {
      ...formFilters,
      [filterId]: {
        ...formFilters[filterId],
        ...values,
      },
    },
  });
```

```
form.setFields([
    {
      name: 'filters',
      value: {
        ...formFilters,
        [filterId]: {
          ...formFilters[filterId],
          ...values,
        },
      },
    },
  ]);
```

https://user-images.githubusercontent.com/70410625/118994963-2479ef00-b95d-11eb-8d56-0728b7961358.mov

**Comment by villebro** [comment]
Awesome detective work @michael-s-molina - please open a PR to claim due credit for this!
