### ISSUE TITLE
Change number of Roles user can select

### ISSUE THREAD

**Issue by CaptainHoangLe** [apache/superset#14733]
I am using superset ver 0.36.0
I have create a role "Manager". He can create user with all roles except "Admin" and "Manager". So I want to change the number of roles, user can choose in form.Specifically,i want if user has role "Manager" , "Admin" and "Manager" will be hidden in dropdown Roles.
![image](https://user-images.githubusercontent.com/53038465/118948215-46d23380-b982-11eb-8c22-32bd44884bbc.png)
I overrided class FormWidget by my class CusFormWidget. But i don't know how to continue.
Please any one can give the solution for me.
I am looking forward to recieving from you.
Thanks all !

**Comment by dpgaspar** [comment]
Hi @CaptainHoangLe,

Superset does not support this out of the box, and overriding behaviour this way could be challenging to maintain.
Having said that.  

There are several different ways to achieve this. You need to create your own `UserModelView` and a custom `SupersetSecurityManager` with just the override for the user model view, 
for the role filter you can probably use `add_form_extra_fields`.

This is a Flask-AppBuilder question so I'm going to close the issue here, feel free to reopen on: https://github.com/dpgaspar/Flask-AppBuilder

**Comment by CaptainHoangLe** [comment]
> for the role filter you can probably use `add_form_extra_fields`.

Thank you so much for your help
