### ISSUE TITLE
[cosmetic][bar chart] bar value overlap and not in the correct bar section when stacked

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#14876]
## Screenshot
<img width="1161" alt="Screen Shot 2021-05-26 at 10 52 44 PM" src="https://user-images.githubusercontent.com/81597121/119866256-7c6ea380-bed1-11eb-844a-ce495ed4fd83.png">

**Comment by suddjian** [comment]
Can we get some clarification of how this should behave when the bars are shorter than the text size?

**Comment by junlincc** [comment]
probably no show text in this case, otherwise is gonna be hard to read(too small) or hard to refer to it(text live outside the bar) The information is available, as long as hovering to show tooltip works. @suddjian @jinghua-qa we will implement this(or better alternative) in new echarts, giving up the NVD3 😛

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and if there IS an issue with the current situation, it's different from the bug initially reported. Anyone is welcome to open a new Issue with updated context, or raise a PR to address the problem. Thanks!
