### ISSUE TITLE
Problem uploading CSV to Athena db Connection

### ISSUE THREAD

**Issue by pratikshetty94** [apache/superset#15191]
1) Using Athena database.
2) Trying to upload a CSV to create a table.
3) Have enabled DML and CSV_UPLOAD to the database.

### Expected results
A new table available in SQLLAB from the uploaded CSV file.

### Actual results
we get the following error:
Unable to upload CSV file "nps_new.csv" to table "csv_table" in database "Athena". Error message: __init__() got an unexpected keyword argument 'bind'

what actually happens.
![Screenshot from 2021-06-16 15-30-37](https://user-images.githubusercontent.com/85993840/122200752-f5519180-ceb8-11eb-97ac-f11781386b3a.png)

#### How to reproduce the bug
1. Go to 'Data --> Upload a CSV'
2. Choose Database with Athena Connection.

### Environment
- superset version: `1.2.0`
- python version: `python 3.7.9
- Docker: `20.10.4`

### Checklist

- [ y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ n] I have reproduced the issue with at least the latest released version of superset.
- [ y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Works well when using the 'examples' database.

**Comment by srinify** [comment]
Hi @pratikshetty94 I'm not 100% sure if CSV upload works for Athena. It's done at a database-by database level and not all of them support this specific feature (CSV upload).

**Comment by rusackas** [comment]
Closing this as stale, but perhaps it's worth noting that there have been a few Athena bugfixes and driver updates since this thread was last active. If anyone _knows_ that Athena _should_ support this, and we have a bug in Superset 2.0.1, let's re-open or open a new issue with updated context. If Athena does not support this, then... maybe someone would be interested in opening a PR on the documentation to add a line or two with that caveat?
