### ISSUE TITLE
[dashboard] make tab titles unique

### ISSUE THREAD

**Issue by villebro** [apache/superset#15195]
## Screenshot

![image](https://user-images.githubusercontent.com/33317356/122233270-96921500-cec4-11eb-98e9-53bca5b46672.png)

## Description

Currently it's possible to create many tabs with overlapping names. The ideal solution would be to increment a number when creating new tabs, e.g. "Tab title", "Tab title (1)", "Tab title (2)", also making it impossible to save tabs with duplicate names.

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by rusackas** [comment]
@villebro this is still an issue, but it's an old and quiet one... wanna keep it open?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
