### ISSUE TITLE
Jinja Incompatible Filter Warnings

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#15209]
Warning signs appear when applying jinja filter. The functionality works but it would be nice visually if there weren't warnings appearing.
### Expected results

Jinja filter hopefully will eventually work without filter warnings appearing. 

### Actual results

https://www.youtube.com/watch?v=dE1QlhunWMs (skip to end to view warnings)

**Comment by lilila** [comment]
I understand it is not so easy to detect if a filter has been used through jinja filter. But it would be nice to add an option to hide the warnings

**Comment by ArmenShamelian** [comment]
This is supposedly fixed in https://github.com/apache/superset/pull/12742, the regex to find column names in the jinja template expects the format ` filter_values('colname',)` (comma required). Then sometimes the incompatible warning filter disappears, but sometimes the warning still shows up even though the column is in the jinja template with the correct format according to the regex.

**Comment by saurabhshishodia** [comment]
DO we have any solution to remove warning ?

**Comment by SatyukovED** [comment]
Hello! I'm new to Superset. I needed to create date selector and used Jinja to do it. Although the issue above was resolved, I stacked with same problem. A comma was added but warning didn't disappear.
![image](https://user-images.githubusercontent.com/47986860/130445051-b1cee11d-9fa8-4579-bfdb-4fb8bbdc5b4b.png)
