### ISSUE TITLE
Change Country map chart base on filter on dashboard

### ISSUE THREAD

**Issue by CaptainHoangLe** [apache/superset#15211]
I am using superset ver 0.36.0
i am having a request about changing map of Country map chart on dashboard.Anyone can give a optimal solution for this problem.

**Comment by zufolo441** [comment]
I searched for a solution, last year, but there isn't. I had to write a web service that edits JSON of slices.

**Comment by CaptainHoangLe** [comment]
> I searched for a solution, last year, but there isn't. I had to write a web service that edits JSON of slices.

So sad @@. thanks for your reply

**Comment by rusackas** [comment]
@CaptainHoangLe this bug is a bit of an antique. I'm closing it in hopes that you found some sort of workaround/solution. If anyone can validate that this is still an issue in Superset 2.0.x with Dashboard Native Filters (rather than the deprecated Filter Box component), we can revisit/reopen this with updated context. Thanks!

**Comment by zufolo441** [comment]
For my company, I partly solved my using handlebar chart, with an iframe inside that opens a country map chart using a variable with map name.
