### ISSUE TITLE
Cannot create histogram of metrics

### ISSUE THREAD

**Issue by Timonzimm** [apache/superset#15525]
### Expected results

I expect to be able to create an histogram of metrics but only "COLUMNS" can be selected.

### Actual results

Only COLUMNS can be selected when choosing "Histogram" visualization type.
#### Screenshots

![image](https://user-images.githubusercontent.com/5808319/124283179-e969fe80-db4b-11eb-9e4d-1a1746919197.png)

### Environment

I am using the docker-compose `non-dev.yml` file.

- superset version: `Superset 0.999.0dev`
- python version: `Python 3.7.9`
- node.js version: `bash: node: command not found`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Deninc** [comment]
+1, not possible in 1.2 too.

**Comment by akshat-92** [comment]
+1

**Comment by ankitdatta** [comment]
+1

**Comment by rusackas** [comment]
This legacy NVD3 chart has not been getting a lot of maintenance effort, and since this is arguably a feature request, we're not that likely to see it happen in this plugin. Leaving this issue open for now since it seems like a valid shortcoming, but if anyone wants to see this functionality, I think the effort would be best applied toward making an ECharts-based histogram plugin. If anyone wants to volunteer some time in this effort, please hit me up here or on Slack!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
