### ISSUE TITLE
Datasource columns don't auto update when updating data source

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#15602]
When you update a query, new columns aren't automatically added to the dataset. You have to navigate back to edit dataset and manually refresh to sync the new columns to the dataset.

### Expected results
The columns added by the edited query to be automatically added.

### Actual results
The columns added by the edited query don't automatically appear. You have to reopen the dataset and then refresh the sync. 

#### How to reproduce the bug

1. Edit dataset that adds selected columns
2. Save
3. New Columns don't automatically appear
4. Have to open edit dataset again.
5. Sync Columns from source
6. New Columns Appear

**Comment by junlincc** [comment]
@matthewphua if it's preset prod bug, please either validate it on master or label version as Preset Production in the template. thanks!

**Comment by ypankovych** [comment]
Have the same issue, when new columns are added to the data source, they don't appear in the dataset till I click refresh. 

It'd be nice to have an auto-sync option.

**Comment by treygilliland** [comment]
Wanted to bring this back to attention. We had a prod-breaking bug because a timestamp column type changed from DATETIME to TIMESTAMP which broke our time grain and time range filters causing 400 errors across our dashboards. Manually syncing the columns on all of our datasets fixed this. 

It would be great if there was an option to opt-in to column sync

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering a bug in current versions (currently 3.x) please open a new Issue or a PR to address the problem, or you can open an Ideas discussion here on github to suggest new features (like a new workflow for column syncing).
