### ISSUE TITLE
[native filter] numerical range filter with all null value column not allow to set range

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15671]
When setup a Numerical range filter for COVID example dashboard , select a column with all null value will not allow to set range

### Expected results
a column with all null value is not able to select in the numerical range filter configuration

### Actual results

a column with all null value is able to select, then the numerical range filter is not able to select range

#### Screenshots

https://user-images.githubusercontent.com/81597121/125536485-c4e9c3fd-e5a0-49bb-8b24-34226581dcff.mov

#### How to reproduce the bug

1. Go to example COVID Vaccine Dashboard
2. Setup numerical range filter in configuration tab and select the column in drop down menu (only one available)
3. numerical range can not select

### Environment

- superset version: master
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
@jinghua-qa thanks for filing! good catch please add to test case🙏
It would be also good to know if this is db specific? do we have different dataset to test numeric col with all NULLs?

**Comment by jinghua-qa** [comment]
I reproduce the same issue with FCC 2018 Survey, select a column with data 1 and null, wont be able to set range for numerical range filter either.
<img width="1157" alt="Screen Shot 2021-07-13 at 8 01 43 PM" src="https://user-images.githubusercontent.com/81597121/125554371-d850d4ea-4c93-4173-a49b-f8a0b92b0188.png">
<img width="1792" alt="Screen Shot 2021-07-13 at 8 00 39 PM" src="https://user-images.githubusercontent.com/81597121/125554384-808b3501-a810-4668-9413-045e324a818e.png">

**Comment by rusackas** [comment]
I think this is OK to close as a "won't fix" since I wouldn't expect the range control to work when there is only one value in the column (in this example, 1). The range would be... 1 to 1, which doesn't make much sense for it to work. 

We could take on a small design task to figure out if there's a better way to explain some context here, e.g. "Range filter cannot be used when there is a single numerical value in the column" but I'm not sure if it's worth the effort or not. @kasiazjc may have feelings here.

I tried this with columns that have null values and a range of numbers, and all seems to work just fine.
