### ISSUE TITLE
[Explore]Server side pagination for charts again and again

### ISSUE THREAD

**Issue by imsuresh97** [apache/superset#15860]
Hi ,

I'm still facing the issue in server side pagination ... I'm not able to navigate to different pages ... I have attached the video recording ...

https://user-images.githubusercontent.com/39001149/126752697-2af7f2ac-2bce-4086-bb2a-0b5d7866a635.mp4

**Comment by junlincc** [comment]
Hi, just looked at latest master, i have no idea why server side pagination is broken again... sometimes the pagination doesn't show, sometimes it's not clickable.....

@simcha90 can you please take a look? 

https://user-images.githubusercontent.com/67837651/126841496-fe8639da-3ad6-47df-a800-da0c6895d582.mov

**Comment by junlincc** [comment]
https://github.com/apache/superset/issues/15857

**Comment by Veonms** [comment]
Same issue as #15706 and #15478.

**Comment by junlincc** [comment]
@amitmiran137 @simcha90 lmk if you are gonna work on it thanks!

**Comment by pkdotson** [comment]
@simcha90  it seems that the datamask is linked to the crossfilters and nativefilters feature flag and when these are turned off pagination no longer works in table chart. Is there a way to do pagination without using the datamask since it's more of native filters mechanism.

**Comment by simcha90** [comment]
@pkdotson hi it's based on same flows as crossFilters and native filters works, so we can't detach it from dataMask. but we can remove all these Feature Flags from Explore page, because I think there is no side effects for these flags on Explore page.  @villebro Can you please confirm if this change is ok?

**Comment by villebro** [comment]
@pkdotson I agree with @simcha90 - pagination is really just using `dataMask` as that's the mechanism we use for this type of behavior. So we can't really detach pagination from it.

Since `dataMask` is becoming (or arguably has become) a foundational feature within the application, I think we're approaching a point where we should just remove the native filter and cross filter feature flags and move any contentious features into the `DASHBOARD_FILTERS_EXPERIMENTAL` feature flag. Thoughts @junlincc @amitmiran137 @rusackas @kgabryje ?

**Comment by amitmiran137** [comment]
Sounds good to me

**Comment by suddjian** [comment]
I think it'd be a good idea to start putting together a list of such upgrades as the basis for releasing Superset 2.0

**Comment by rusackas** [comment]
> I think we're approaching a point where we should just remove the native filter and cross filter feature flags and move any contentious features into the `DASHBOARD_FILTERS_EXPERIMENTAL` feature flag.

@villebro While I'm quite excited by the prospect, but it's hard to draw the line on what's contentious. I think this would require some level of community support - lazy consensus at a bare minimum, but perhaps a full vote. This would, as @suddjian suggests, probably become a 2.0 discussion, especially if removal of these flags involves migration from FilterBox or anything contentious like that. But... that's a topic _just a little_ too big to explore fully this thread. 

@simcha90 / @villebro am I understanding correctly that @simcha90 's approach works with the flags as they exist today? If so, @simcha90 do you have bandwidth to follow through with the plan?

**Comment by suddjian** [comment]
Due to https://github.com/apache-superset/superset-ui/pull/1251, it appears that this issue could be considered resolved. In order to access server side pagination, somewhat unintuitively, the `DASHBOARD_NATIVE_FILTERS` feature flag is required.
