### ISSUE TITLE
Pivot table conditional formatting breaking change

### ISSUE THREAD

**Issue by etr2460** [apache/superset#15961]
This chart visualization used to have a formatting option to fill the pivot table cells with color based on the cell values (relative to each other).  At some point in the last couple weeks, this functionality disappeared:

When I went into the chart to see what happened, now I'm only seeing a "Customize Metrics" section in the chart "Customize" menu that only allows to set static rules (e.g. color red if > 0) but no longer fills colors based on a relative continuous scale across all values on the table.

Note: without the coloring the chart is really difficult to interpret, verging on unusable.

**Comment by Delfins** [comment]
UPPPPP!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
