### ISSUE TITLE
[chart list] Simply explore a chart makes that chart shows as modified on chart list

### ISSUE THREAD

**Issue by rosemarie-chiu** [apache/superset#15990]
I simply explore a chart and hit run, then the chart shows last modified by me without me doing any changes. That makes me anxious thinking I modified something.

### Expected results
Without clicking save button, should NOT update chart last modified history

### Actual results
Simply run on chart will update chart last modified history

### Steps:
1. Explore an existing chart
2. Click run
3. Return to chart list
4. Observe that now that chart shows last modified by you
#### Screenshots

https://user-images.githubusercontent.com/52086618/127707198-c8388592-2c8f-4994-a696-37490eb3bc40.mp4

**Comment by jinghua-qa** [comment]
saw the same issue on superset master

**Comment by junlincc** [comment]
@pkdotson did we change the logic while we altered homepage? 🙏

**Comment by pkdotson** [comment]
No this would not be related to homescreen changes.

**Comment by suddjian** [comment]
Still not sure what the root cause of this is, but here's what we've found so far in the course of debugging:

- The steps listed above are not actually required to reproduce the issue. All that is required is viewing a chart in explore. It would seem that loading the explore page somehow writes the chart to the db.
- The chart list view is using the `changed_on` database field, which gets set to `now` automatically any time the `Slice` model is written in the db.
- Loading the chart in Explore a  _second_ time does not trigger the same update to the `Slice`. This issue might only apply to example charts, if they have some special condition that organically-created charts do not. Needs further testing.

**Comment by jinghua-qa** [comment]
test cases update
