### ISSUE TITLE
Implement a DB connector for Cloud Spanner

### ISSUE THREAD

**Issue by jinnig** [apache/superset#16055]
**Is your feature request related to a problem? Please describe.**
Cloud Spanner is a distributed SQL database from Google Cloud Platform. It would be great to have the Cloud Spanner integration with Superset.

**Describe the solution you'd like**
Here is the sqlalchemy driver for Cloud Spanner developed by Google: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy
I want to work on implementing a new DB connector based on the official sqlalchemy driver.

**Comment by rusackas** [comment]
Closing this since it's not a bug, but I too encourage the effort, whether it's in the form of a PR, or an Ideas thread on the Discussions tab. :)

**Comment by wthorp** [comment]
If anyone finds themselves here in the future, this shouldn't be too big of a lift.  There's a SQLAlchemy project for Spanner, so its not hard to get things _almost_ working.

Add these package lines to docker/requirements-local.txt
```
sqlalchemy-spanner
google-cloud-spanner
```

Configure your GCP service account in docker/.env
```
GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_creds.json
```

Include your GCP credentials in the Dockerfile
```
COPY --chown=superset:superset gcp_creds.json /app/gcp_creds.json
```

You should be able to add a database using the SQLAlchemy URI features with a format like
```
spanner+spanner:///projects/{project_id}/instances/{instance_id}/databases/{database_id}
```

This should correctly populate the Database and its Schemas, but not the Tables.  SQL Lab works as well.
The Table listing issue is likely due to Spanner disallowing `information_schema` queries inside transactions.
It's trivial to make SQLAlchemy happy in test code, but I haven't had luck driving the Superset configs yet.
```
    with engine.connect() as connection:
        connection.execution_options(isolation_level="AUTOCOMMIT")  # This is the fix
        result = connection.execute(text("SELECT table_name FROM information_schema.tables WHERE table_catalog = ''"))
```
