### ISSUE TITLE
Switch to directory susperset-frontend and execute the command npm i & npm run dev with an error

### ISSUE THREAD

**Issue by hanyueqiang** [apache/superset#16216]
## Screenshot

[drag & drop image(s) here!]

## Description
ERROR in ./src/datasource/DatasourceEditor.jsx 113:2
Module parse failed: Unexpected token (113:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```js
| const checkboxGenerator = (d, onChange) => (
>   <CheckboxControl value={d} onChange={onChange} />
| );
| const DATA_TYPES = ['STRING', 'NUMERIC', 'DATETIME'];
```

[describe the issue here!]

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by DionSun** [comment]
hi, do you run it on windows.  I have some issue on windows. Then I try build it on WSL, it can build pass. maybe you can have a try. 
https://github.com/apache/superset/blob/master/CONTRIBUTING.md#frontend

**Comment by rusackas** [comment]
Hi, closing this since it's gone inactive for so long. Hopefully, you've managed to resolve this, but I know it works since it's a common occurrence. That said, if it _was_ happening on Windows, that would be difficult to troubleshoot. Windows is officially unsupported, but we'd welcome PRs for any improvements that make it incrementally more possible/stable to do so.
