### ISSUE TITLE
[Explore] wrap %s around selected value to implicitly indicate LIKE clause

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16277]
As a Superset user, when I use the LIKE filter, it would be helpful the ad hoc filter can automatically apply % % on each end of the value input to implicitly indicate the LIKE clause. 

Cursor can be placed in between %%, please make sure the query is not being affected after adding them. 
<img width="347" alt="Screen Shot 2021-08-16 at 11 16 25 AM" src="https://user-images.githubusercontent.com/67837651/129611774-982d3283-cc6d-4106-a5b6-b1d8e98f5590.png">

**Comment by zhaoyongjie** [comment]
Currently, `like` or `ilike` operator in filter, I think there are some flaws. 

The query does not contain `%` in where clause. For this query, it is basically equivalent to `=` operator.
![image](https://user-images.githubusercontent.com/2016594/129660277-992a22bb-f329-47a4-a53f-da7628e2b744.png)

In addition to show `%` in the UI, I suggest putting `%` in the query.

**Comment by junlincc** [comment]
> In addition to show `%` in the UI, I suggest putting `%` in the query.

definitely!

**Comment by junlincc** [comment]
@zhaoyongjie to eliminate confusion to business users, let's only add %% to the query, and not do anything on UI.

**Comment by rusackas** [comment]
Closing this out since it's not a bug. The like/ilike option has been brought up a few times, but gets shot down as a default for a number of reasons, but mainly performance. I think we can add additional configuration options to the filter to support this, but we should take it up in an Ideas thread on Discussions if anyone is interested in doing so.
