### ISSUE TITLE
Can Read data from Athena table, but not able to create Dataset

### ISSUE THREAD

**Issue by Kiezer** [apache/superset#16282]
I've created the connection to Athena and am able to query the Athena tables. However, When I try to create a Dataset from the athena table it fails with the error.

superset_app             | 2021-08-16 22:04:03,786:ERROR:root:'Engine' object has no attribute 'connection'

### Expected results

To create a Dataset from athena table.

### Actual results

Fails with the ERROR:root:'Engine' object has no attribute 'connection'

#### Screenshots

![image](https://user-images.githubusercontent.com/29813899/129638893-3cc737c2-6643-4e42-85ad-25bab98208e0.png)

![image](https://user-images.githubusercontent.com/29813899/129638942-b0b0087a-aa07-48e5-8d44-a85d2daa9523.png)

### Environment

(please complete the following information):

- superset version: `superset version`  == 0.0.0dev
- python version: `python --version`  = 3.7.9
- node.js version: `node -v`   == v14.17.4
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hi there @Kiezer can you share your database connection string (anonymized of course)?

I can't see your full error but it seems like the connection string you're giving Superset may be incorrect. This part looks potentially problematic: `theast-2}.amazonaws.com`

Connection strings shouldn't have braces like `{}`. It looks like we have braces as variable-placeholders in our docs (https://superset.apache.org/docs/databases/athena) but that's more to convey the fact that these are variables not literal values! 

**For future reference, I recommend copying & pasting your stack trace (hiding sensitive data ofc) instead of putting a screenshot. This will make it easier for the community to help you! 🙏**

**Comment by rusackas** [comment]
Closing since we never heard back and this has gone stale.
