### ISSUE TITLE
Bigquery SQL Engine Cannot Handle Strings with Apostrophe

### ISSUE THREAD

**Issue by jamesrayoub** [apache/superset#16378]
When filtering on a string dimension which contains an apostrophe (i.e. family name - O'Brien), the sql engine generates a `WHERE` statement which uses single quotes instead of double quotes which leads to:

`400 Syntax error: Parenthesized expression cannot be parsed as an expression, struct constructor, or subquery`

### Expected results

`WHERE project_name IN ("Beverly O'Brien")`

### Actual results

`WHERE project_name IN ('Beverly O''Brien')`

### Notes
Using a BigQuery database connection

**Comment by jamesrayoub** [comment]
@junlincc

**Comment by jamesrayoub** [comment]
@junlincc @daniel10012

**Comment by junlincc** [comment]
Thanks @jamesrayoub for moving the convo to the public as this change request maybe contentious. 

@michellethomas @ktmud @amitmiran137 and community, want to get your thoughts on this.

**Comment by john-bodley** [comment]
I wonder if there's an issue with the BigQuery SQLAlchemy dialect as it should handle the necessary string escaping/formatting.

**Comment by etr2460** [comment]
noting as well that `WHERE project_name IN ('Beverly O''Brien')` is the standard way of escaping quotes in SQL (https://stackoverflow.com/questions/1586560/how-do-i-escape-a-single-quote-in-sql-server). I don't know what dialect of SQL BigQuery speaks, but i would agree that this seems to be more of a sqlalchemy connector/dep issue than at the superset level.

We can't simply use double quotes everywhere here because that's not supported by Presto/Hive

**Comment by villebro** [comment]
I believe we should escape string values that are entered into the adhoc filter field. In this case "O'Brien" should become "O''Brien" like @etr2460 said. We also need to make sure native filters and filter box do the same when emitting filters.

**Comment by villebro** [comment]
Btw, I just tested this with Sqlite, and it works as expected:
![image](https://user-images.githubusercontent.com/33317356/130312295-485db0a9-4683-4f14-b01c-6cd3a45a27ad.png)

So this should really be handled in the dialect as @john-bodley suggested.

**Comment by etr2460** [comment]
Sounds like this is probably an issue with the sql alchemy library then. I'd recommend filing this issue with https://github.com/googleapis/python-bigquery-sqlalchemy (feel free to link this one with context) and then once it's fixed in that library you should be able to pull in the fix with a library version bump. I'm going to close this ticket now, but feel free to reopen/open a new one if the maintainers of `python-bigquery-sqlalchemy` send you back to us
