### ISSUE TITLE
Cannot user a dashboard inside a iframe

### ISSUE THREAD

**Issue by gustavoaalves** [apache/superset#16409]
I had this issue when i tried use my dashboard inside an iframe. Look at the screenshot below:

![image](https://user-images.githubusercontent.com/11478696/130511345-b0b1a791-9e31-4991-ba29-165aa0b83668.png)

Code from my HTML:

`<!DOCTYPE html>
<html lang="en">
	<head>
		
	</head>
	<body>
		<iframe height="1500" width="1500" frameBorder="0" scrolling="no" src="http://192.168.0.109:8088/r/12?standalone=true" title="description" style="overflow:hidden" ></iframe>
	</body>
</html>`

### Expected results

Open my dashboard without errors in some iframe.

### Actual results

This error in two of three widgets from my dashboard:

![image](https://user-images.githubusercontent.com/11478696/130511571-8e47089d-535d-4790-ac63-da5df93f48fa.png)

Unexpected token < in JSON at position 0

#### Screenshots

Above!

#### How to reproduce the bug

1. Embed a Dashboard inside a Iframe

### Environment

(please complete the following information):

- superset version: latest
- python version: Docker container (https://hub.docker.com/r/apache/superset)

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by arkitpatel** [comment]
I had a similar issue and it was due to permissions for the user used to display the dashboard. I am using the following permissions though some are specific to the use case we need but maybe you can give it a try. Another issue could be that permission is not synced correctly so maybe you can try the DB upgrade and then init command.

![image](https://user-images.githubusercontent.com/20540199/131601048-2430c1fc-47e6-4073-afa0-c2e640edb1dd.png)

**Comment by amitmiran137** [comment]
We're you able to resolve the issue?
