### ISSUE TITLE
[edit dataset] error will show if change dataset from edit dataset modal

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16552]
When i try to change dataset in edit dataset modal, the columns of old dataset and new dataset got messed up and the change are saved to my old dataset, then when i try to do the chart, error msg will show also the dashboard with old dataset is broken.

I think if user is not supposed to change dataset in edit modal we should get warning msg before we save, or maybe disable the drop down list in edit modal so that user wont be able to do the change?

https://user-images.githubusercontent.com/81597121/131720932-f35bb622-0b11-415c-8374-5a8e78c474f5.mov

<img width="1781" alt="Screen Shot 2021-09-01 at 10 40 24 AM" src="https://user-images.githubusercontent.com/81597121/131720950-86b025d5-5e26-412e-b48d-911c498ec7d1.png">
<img width="1792" alt="Screen Shot 2021-09-01 at 10 33 23 AM" src="https://user-images.githubusercontent.com/81597121/131720953-52e92f24-9d77-4e22-9e10-ceabfcaef995.png">

**Comment by junlincc** [comment]
expected behavior: user should use Change dataset modal ONLY to perform task of changing dataset. We do need to add some roadblock to prevent users from coming down the wrong route by adding one line below the dropdown - "Please change dataset in the Change dataset modal. Selecting a different table or dataset will cause error in existing chart and dashboard." (?) something like that...

**Comment by rusackas** [comment]
I don't believe this issue is a concern anymore, but if you feel I'm mistaken @jinghua-qa , please feel free to re-open it!
