### ISSUE TITLE
Grouping of a bunch of lines in SQL Lab

### ISSUE THREAD

**Issue by yourssvk** [apache/superset#16599]
Problem Description;

Editing long SQL script in SQL Lab has been challenging, as the editor does not provide advanced editing options or integration with some editor that provides features like grouping bunch of lines in a SQL (shrink/ expand a section of a query)

Workaround/ Resolution:

We end up editing SQLs outside of Superset etc

**Comment by rusackas** [comment]
Closing this issue since it's gone a long time without any backers, and it's more of a feature request than a bug report. If there are specific features/designs you'd like to see implemented, I'd suggest taking those up in an Issues thread on the discussion tab, so we can hash out the details and see if anyone is interested in opening incremental PRs. Thanks!
