### ISSUE TITLE
User activity dashboards for admins with ability to kill user queries

### ISSUE THREAD

**Issue by yourssvk** [apache/superset#16602]
Problem Statement:

For SQL Lab, there is a query history, but admins do not have the ability to kill queries. It will be good to analyze user activity on Superset, to determine the user query performance metrics, find out queries that could be automated in a pipeline instead of running ad-hoc queries etc.

Workaround/ Resolution:

We end up pulling the information from the database side

**Comment by djouallah** [comment]
yes Please I love to be able to see all SQL history not only the one from SQL Lab only

**Comment by rusackas** [comment]
Closing this since it's more of a feature request than a bug report, but if you're still interested in this, I suggest opening a Discussion thread (of the Issues variety) or opening a SIP if you want to implement something like this in Superset. 

CC @yousoph @kasiazjc in case we ever dig further into activity streams / logs.
