### ISSUE TITLE
Improve 403 Forbidden page when user doesn't have access to Dashboard

### ISSUE THREAD

**Issue by duynguyenhoang** [apache/superset#16611]
**Is your feature request related to a problem? Please describe.**

If we enable Dashboard RBAC and user doesn't have access to it, the plain text returns to user.
We would have a page to handle this kind of response.

![image](https://user-images.githubusercontent.com/7106179/132253744-649c904e-5006-401f-90ab-0d91ef68b9a2.png)

**Describe the solution you'd like**
Create an 403 page similar to 404 or 500 page

**Comment by rusackas** [comment]
Thanks for the PR on this! Trying to get it some renewed attention!

**Comment by rusackas** [comment]
@duynguyenhoang is there still a need for this? The PR seems to have failing tests and merge conflicts, but this is also the only report I've heard of this problem.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
