### ISSUE TITLE
Metadata synchronization across dbt and Superset

### ISSUE THREAD

**Issue by danisola** [apache/superset#16635]
**Is your feature request related to a problem? Please describe.**
Many companies now use [dbt](https://github.com/dbt-labs/dbt) to model, test, and document their datasets. It would be great to have an easy way to synchronize the dbt metadata with Superset.
It's also worth noting that in Superset the columns descriptions are discoverable and useful, but the 'description' field in datasets is not visible anywhere. At least I couldn't find it in Superset 1.1.0

**Describe the solution you'd like**
A convenient way to solve this would be for Superset were to read the field description from the table and column comments. Something like:

* Enable [persist_docs](https://docs.getdbt.com/reference/resource-configs/persist_docs) in dbt, which stores the descriptions as comments in tables and columns
* Superset reads and populates the column and datasets descriptions when synching metadata from the DB

**Describe alternatives you've considered**
Another way would be to have a system that synchronizes the dbt metadata using the [Superset API](https://superset.apache.org/docs/rest-api)

**Comment by one-data-cookie** [comment]
@danisola I was able to achieve this via Superset API and open-source it as a part of [`dbt-superset-lineage`](https://github.com/slidoapp/dbt-superset-lineage). 😉 

Also, I'd note that column descriptions are visible upon hovering over an "i" icon next to column names when creating/amending charts in Explore.

**Comment by danisola** [comment]
That's great, we'll check it out!

**Comment by rusackas** [comment]
Closing this as stale, and also because we've started using Discussions for feature requests rather than Issues (which at least for now, we're trying to whittle down to bug reports). 

That said, I'm pinging @shreesham to see if there's anything that needs updating on this thread (e.g. if there are any relevant updates since this was filed) or if this acts as a data point for a useful feature request since dbt is a hot topic these days!
