### ISSUE TITLE
[dashboard] Transparent Background option not working

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#16658]
## Screenshot

![background](https://user-images.githubusercontent.com/74634977/132803100-057cfcfa-2249-471f-8275-9c585f79bba9.gif)

## Description

'Transparent background' setting does not work when using inside a tab(which is not a top level tab).

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by kamalkeshavani-aiinside** [comment]
Keeping this active

**Comment by rusackas** [comment]
Interesting... I could go either way on this one. On one hand, sure, I can see the allure of tabs having a transparent background, so that the background of the dash shoes through consistently. On the other hand, the area of a tab is kind of a "widget" in a dashboard in its own right... and if you took away the white background it'd be a bit ambiguous where the tab area ends and the charts below begin. 

If we want to keep the tab area opaque (which I think might make more sense than transparent, actually), perhaps we should hide/remove this control for chart rows within the tabs, since it's irrelevant unless the row is moved out. Thoughts @kasiazjc?

**Comment by kamalkeshavani-aiinside** [comment]
@rusackas Got your point. Our concern with the current behavior of tabs is that all the big number charts in a tab are almost merged in white background, but with transparent background we can make it out where a certain chart or a column/group of charts end.
I guess the best solution would be to bring in a new feature of 'Borders' to each widget in dashboard. We can set the borders to whichever bunch of elements we prefer.

I had raised it as a feature request a long time ago, https://github.com/apache/superset/issues/15161. Although some of them can be achieved with CSS(I think), but still it requires an extra skill to be able to personalize a dashboard. A bunch of format features in the dashboard can be considered. Just like position_json, we can have a format_json holding format settings(border, title text size, title text color, etc..) of each widget in the dashboard.

Let me know what you think and I can start a discussion for the same.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering seeing this as a bug in current versions (currently 3.x) please open a new Issue or a PR to address the problem. We're also happy to discuss deprecating/adding/redesigning these features as a Github Discussion or a SIP. Thanks!

**Comment by gn02097230** [comment]
I have the same bug found, i am unable to fix it even through CSS
