### ISSUE TITLE
Time-series Line Chart - Time Grain - does not work if time is not a string

### ISSUE THREAD

**Issue by frafra** [apache/superset#16832]
"Time-series Line Chart" can show timeseries where the time column is a bigint, but it fails when trying to set the time grain.

### Expected results

It should work.

### Actual results

```
Error: function date_trunc(unknown, bigint) does not exist LINE 1: SELECT DATE_TRUNC('year', year) AS __timestamp, ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. 
```

#### How to reproduce the bug

1. Load default/examples datasets
2. Go to "Games per Genre over time"
3. Set the time grain to "Year"
4. Click "Run"
5. See the error

### Environment

(please complete the following information):

Latest Docker image.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

`date_trunc` is used over the time column, which can be a string or can be an integer-like column. "Time grain" fails if the date column is not a string.

**Comment by junlincc** [comment]
@villebro confirm! it's also happening on Echarts time series. please take a look?

**Comment by rusackas** [comment]
This issue is a bit of an antique, and representing a version of Superset that's no longer supported. A LOT of updates have been made to the Timeseries (ECharts) plugin AND how time is handled by both the backend and viz control panels in general. Since this is stale, I'm going to close it, but if anyone is still experiencing similar issues in current-era Superset, we can most certainly re-open this!
