### ISSUE TITLE
deck.gl multiple layers chart not working when imported from JSON

### ISSUE THREAD

**Issue by Anushka-Hapukotuwa** [apache/superset#16830]
- I have created 2 deck.gl charts - one from deck.gl polygon and the other from deck.gl grid.
- Next I have added those 2 charts to a deck.gl multiple layers chart.
- I have added all 3 charts to a dashboard and I exported the dashboard to a JSON file using the export function on superset.
- When I import the JSON using the import dashboards option, the deck.gl multiple layers chart does not link the 2 other charts as expected. The other 2 deck.gl charts are imported as expected.

When I navigate to the deck.gl multiple layers chart, what I get is shown below in the screenshot:
![deck-gl-multiple-layers-not-linking](https://user-images.githubusercontent.com/87460606/134660016-54202f84-f2a3-4f33-8565-9d48cbc0a69f.png)
I am using superset v1.2

**Comment by rusackas** [comment]
Closing due to age, inactivity, and the bug being filed on a no-longer-supported version of Superset. I'm suspecting that this is fixed in newer versions of Superset, particularly with the `VERSIONED_EXPORTS` feature flag turned on, but if that's not the case, please open a new ticket with updated repro steps and hopefully we can get it sorted out! Thanks!
