### ISSUE TITLE
[setting menu] [profile] favorited column should be 'created column' under CREATED CONTENT tab

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#16845]
In Profile page,  favorited column should be 'created column' under CREATED CONTENT tab

### Expected results

CREATED CONTENT tab should show created charts and dashboard information

### Actual results

CREATED CONTENT tab have a column name 'favorited'

#### Screenshots
<img width="1791" alt="Screen Shot 2021-09-26 at 10 33 55 AM" src="https://user-images.githubusercontent.com/81597121/134818081-12ae693d-1f30-4975-9fbe-ae238acfbcae.png">

#### How to reproduce the bug

1. Go to profile page under setting
2. Click on 'CREATED CONTENT' tab
3. See error

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: superset 1.3 RC2

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this since it's stale, and we're probably not likely to invest in the current version of this page. We'll be (eventually) moving this into the React Single Page App (SPA) rather than the server generated page. If you want to fix the bug on the current page, we'll happily review a PR. If you want to contribute to the SPA effort, please hit us up on [Superset Slack](http://bit.ly/join-superset-slack) in the `#improving-superset` channel
