### ISSUE TITLE
define a Metrics that ignore a particular filter 

### ISSUE THREAD

**Issue by djouallah** [apache/superset#16890]
**Is your feature request related to a problem? Please describe.**
I would like to define a Metric for example sum(Quantity) ,all(date), it means the metric should return the sum and ignore any external filter on date, 

**Describe the solution you'd like**

**Describe alternatives you've considered**
it works fine using jinja parameter but a bit more complex
**Additional context**
I am a PowerBI developer and currently playing with superset and literally this is the first thing I tried, in PowerBI we have a DSL called DAX and a user can simply define a metric as something like sum(x), all(date) and the metric will ignore the external date filter.

**Comment by rusackas** [comment]
Closing this since it's gone stale for over a year, but if you're still interested in pursuing this, let's take it up in an Ideas thread under the Discussions tab, or on Slack. Thanks!

**Comment by djouallah** [comment]
this is disappointing, closing an issue will not make it disappear

**Comment by rusackas** [comment]
Well that's just it, I think it's more of a feature request than a bug if I'm understanding you correctly. Adding the capability to ignore filters sounds like it might cause as many data interpretation issues as it solves. But I might just be misunderstanding the use case, and need some examples. This is why I didn't just close it, but suggested another venue (a Discussion thread) to pick this back up. It hasn't received any comments in over a year and a half, so that might give it a better chance of discovery/engagement.
