### ISSUE TITLE
Custom string suffix for metrics 

### ISSUE THREAD

**Issue by Ayesha-Siddiqa2** [apache/superset#16954]
Adding custom string suffix to metrics using D3 format

**Expected results**
Being able to add suffixes like (GB,Mbps, dBm) using D3 format
Example: I should see xx GB when I query a particular metric

**Actual results**
Not able to add any string suffix in the d3 format input 
Example: 826328149525 (Invalid format: 'GB')

**Screenshots**
<img width="1136" alt="Screen Shot 2021-10-04 at 15 52 54" src="https://user-images.githubusercontent.com/72965913/135835465-e4853a65-2337-4c9a-8857-197f44b03986.png">

**Environment**
superset version: 1.3

**Comment by jhult** [comment]
Bump

**Comment by mdeshmu** [comment]
I want to display bytes (how much size an s3 prefix is using) and now it is misleading when it format it in billion or trillion like 900B or 1.5T which isn't accurate.

**Comment by sunsikai** [comment]
+1

**Comment by rusackas** [comment]
We're a lot closer to this now, as you can _kind of_ do this with currencies. I _believe_ you can add additional currencies in config.py. I admit, Mbps is not a currency, but you can jury rig it a bit. We'd be open to proposals/PRs that change this UI to be some sort of "metric" rather than just currency... maybe people want to add kPa, or who knows what measurements as a suffix.

<img width="1071" alt="image" src="https://github.com/apache/superset/assets/812905/f3674f7a-aac5-4e09-ac6d-b7f96efe7f84">

Closing since it's a feature request rather than a bug, but again, happy to keep the discussion going or review a PR :D
