### ISSUE TITLE
Database Impersonification with PostgreSQL not working anymore

### ISSUE THREAD

**Issue by Karlodun** [apache/superset#17074]
PostgreSQL impersonification is not working anymore

#### How to reproduce the bug

1. Edit database -->Security-->Impersonate logged in user
2. Wrong password for [logged_in user]

### Expected results

When Impersonate logged in user is enabled the connection should use login **and** password from logged in user and not from configuration.
(it was working couple of minor versions ago)
### Actual results

1. It uses appropriate login, from logged in user
2. It uses wrong password, the one configured in connection.

### Environment

(please complete the following information):

- superset version: 1.3.1
- python version: 3.8.10

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Karlodun** [comment]
https://github.com/apache/superset/blob/master/superset/db_engine_specs/base.py, lines 1050-1061
```
 @classmethod
    def modify_url_for_impersonation(
        cls, url: URL, impersonate_user: bool, username: Optional[str]
    ) -> None:
        """
        Modify the SQL Alchemy URL object with the user to impersonate if applicable.
        :param url: SQLAlchemy URL object
        :param impersonate_user: Flag indicating if impersonation is enabled
        :param username: Effective username
        """
        if impersonate_user and username is not None:
            url.username = username
            
```
I think what is missing here is something like:
url.password = password  # this line is not sufficient

Either this is missing, or probably it was never there and my bugreport should be replaced by a feature request.

**Comment by mayurnewase** [comment]
@Karlodun how did it work previously?
Currently I see it takes username of logged in user and password from database connection.
Previously it used password of logged in user to connect to db?
No idea how it worked since password is encoded.

**Comment by betodealmeida** [comment]
@Karlodun unfortunately I don't think this used to work the way you described. We only store the hash of the user password, and the impersonation has always worked by only replacing the username. Some databases have custom impersonation, but not Postgres.

One way to get this working would be via the `DB_CONNECTION_MUTATOR` function in `superset_config.py`. You could write a function that replaces username and password in the SQL Alchemy URI based on the logged in user, but you would have to read the passwords from somewhere other than Superset.

**Comment by chcharlet** [comment]
Hi,

I think this feature working would be a huge benefit in almost every enterprise context. We are just starting into our project, and we are missing it already!

I have been looking at this , and I don't think logging the authorized superset user into postgres using their password is a realistic option (it just makes all kinds of headaches worse). But it would be perfectly possible to have superset use "[SET SESSION AUTHORIZATION](https://www.postgresql.org/docs/current/sql-set-session-authorization.html)" when connecting to postgres.

The bad news is that that has to happen at a different point in time (and hence code).

Would people be interested in a pull request on this?

**Comment by tooptoop4** [comment]
@chcharlet did u solve?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by tooptoop4** [comment]
@chcharlet did u solve?

**Comment by chcharlet** [comment]
@tooptoop4  Unfortunately I was wrong, and betodealmeida was right. Postgres does not support a model of impersonation that is strong enough to be used here. If you want to (securely) be connected as a different user, you need to establish a separate connection for that user, no other way.

**Comment by berlicon** [comment]
I have the same problem. If user watches shared dashboard and he has dbs.impersonate_user = true in Superset DB, then he gets error: DB::Exception: admin: Authentication failed: password is incorrect, or there is no user with such name. 

The route cause of the error in these rows:
        if impersonate_user and username is not None:
            url = url.set(username=username)

It seems in addition we should add rows like this:
user = security_manager.find_user(username=username)
url = url.set(password=user.password)

... But unfortunatelly, user.password containd encoded value like this:
scrypt:32768:8:1$iVy4M6mkGXr5y0AT$1b5eff974069e11d5e5d623d2d3428ed23cdfcb321167a9b7af2175b2e92c56cec16285cc9193edc9b1a1eda5638d7749c8b3fcf88fd4253ef4a41692f5d9e6f

... And I don't know how to decode it.

I checked and add this row: url = url.set(password='8i^hO$0g') # it is decoded value of password
... and user can load the dashboard. But decoded password I can see in this line:
effective_username = self.get_effective_user(sqlalchemy_url)
# here I can see decoded password in this variable: sqlalchemy_url.password
... but it happens when user load his own dashboard.
