### ISSUE TITLE
[explore][time-series chart] Can not see all labels on hover chart

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#17324]
#### How to reproduce the bug

1. Make a dataset with high-cardinality.
2. create a Time Series chart, and add group by the high-cardinality column. for example, this chart shows population group by country:

<img width="1216" alt="Screen Shot 2021-11-02 at 10 48 29 AM" src="https://user-images.githubusercontent.com/27990562/139918883-eb8c4cca-3d10-4562-8515-1f35d0f0d96d.png">

3. Hover on the chart, the tooltip can not display all countries, more than half of them are out of visible area. There is no scrollbar in the tooltip, so there is no way for users to see all the values.
4. This issue makes this data visualization misleading. People may read hover tooltip to find largest / smallest / etc, value for a given group-by, but we only display half of all the values.

### Expected results

display all the values for the given group-by column.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @junlincc @villebro

**Comment by stephenLYZ** [comment]
Here may need to consider supporting tooltip scrolling. We should make sure the tooltip doesn't disappear when the mouse moves over it.

**Comment by srinify** [comment]
This may be a controversial opinion here ... but having a chart with *this* many labels is a poor reader experience. The primary goal of a visualization is to make it **easy** to compare values, in this case compare the lines between countries.

So until this is resolved a different way, I would honestly recommend either:

- Visualizing a lot of lines without country tooltips enabled
- Having a few charts with maybe 5-10 countries each in your dashboard

The other feature that would be cool to have in Explore is to enable the behavior of hovering showing only the specific country / label (instead of showing ALL labels and highlighting)

**Comment by srinify** [comment]
This may be a controversial opinion here ... but having a chart with *this* many labels is a poor reader experience. The primary goal of a visualization is to make it **easy** to compare values, in this case compare the lines between countries.

So until this is resolved a different way, I would honestly recommend either:

- Visualizing a lot of lines without country tooltips enabled
- Having a few charts with maybe 5-10 countries each in your dashboard

The other feature that would be cool to have in Explore is to enable the behavior of hovering showing only the specific country / label (instead of showing ALL labels and highlighting)

**Comment by Blaize-Rhodes** [comment]
Can I suggest that when you mouse over the line it displays the line value.
Put the key somewhere else like all the other graphs in the world?

**Comment by rusackas** [comment]
I think since this has been inactive for so long, we can safely close it as a won't fix. 

It's also important to mention that since this was opened, the ECharts timeseries charts have become the de facto standard, and these legacy charts aren't getting significant updates. If anyone wants to open a PR, we're more than happy to review, but otherwise it's more likely that these charts will be removed than fixed in the near-ish term.
