### ISSUE TITLE
Got error while exporting csv in dashboards

### ISSUE THREAD

**Issue by lukelin780902** [apache/superset#17381]
I was trying to export the data from dashboards by clicking Export CSV, like below, but got error saying `{"message":"Error: Error (planning_exception): {'error': {'root_cause': [{'type': 'planning_exception', 'reason': 'The maximum LIMIT for aggregate sorting is [65536], received [100000]'}], 'type': 'planning_exception', 'reason': 'The maximum LIMIT for aggregate sorting is [65536], received [100000]'}, 'status': 400}"}`

![image](https://user-images.githubusercontent.com/85915449/140958516-d8aed43c-b956-45cc-afc4-0c61fbc392cd.png)

However, if I go to 'view chart in Explore' and exporting csv by click 'CSV icon', then the whole queried data can be exported successfully. Does anyone know how it was caused and how to solve it?

### Expected results

export and download CSV from the dashboards tab.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ V] I have reproduced the issue with at least the latest released version of superset.
- [ V] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment]
Please provide version? @lukelin-linkernetworks

**Comment by lukelin-linkernetworks** [comment]
> Please provide version? @lukelin-linkernetworks

I directly pull the latest docker image few days ago, and the sha is `3c3cb8e7f2249b0427470253788ec3dc5fd5c5caad74d35ca42e0243f9b4f444`

however, when i go with `sperset version`, it shows `Superset 0.0.0dev`

**Comment by junlincc** [comment]
gotcha, thanks for the info. @jinghua-qa can you double check and add test:case? thanks!

**Comment by jinghua-qa** [comment]
I tried latest master and it seems csv download work fine in dashboard, can you provide more detail of repro steps?

https://user-images.githubusercontent.com/81597121/141395686-1a4f44c3-68b3-4f57-8789-f71cb378bde3.mov

**Comment by lukelin-linkernetworks** [comment]
I directly pulled the image and deployed on machine instead of using the latest master branch, but I think this isn't the version difference unless the image version is far behind the master branch. Also, I was using Elasticsearch api to connect the superset with database, and others should be pretty normal as making dataset, aggregating, making chart. The most important weird thing is that you can download csv in charts but not in dashboard, so any idea why it shows the error `The maximum LIMIT for aggregate sorting is [65536], received [100000]'` ?

**Comment by eschutho** [comment]
@jinghua-qa the error is specific to elasticsearch, so we'll need to be using that as a db connection to repro, fyi.

**Comment by lukelin-linkernetworks** [comment]
Hi @eschutho, @jinghua-qa, @junlincc, any update for this issue?

**Comment by lukelin-linkernetworks** [comment]
Hi @eschutho, @jinghua-qa , @junlincc,again, any update for this issue? or anything I can provide to better understand this issue? thanks

**Comment by jinghua-qa** [comment]
@rosemarie-chiu can you try to reproduce? thanks

**Comment by sowo** [comment]
I am able to reproduce this issue on 2.0.1 with an Elasticsearch backend. In our environment, we set ROW_LIMIT=200000 and SQL_MAX_ROW=200000. The chart has ROW_LIMIT set to 50000. 

Now, Elasticsearch has a limitation that for sorted queries, the maximum LIMIT is 65535 rows (https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-limitations.html#_sorting_by_aggregation)

The problem seems to be introduced in: https://github.com/apache/superset/blob/65fffe974b6d881dabbf6600fe034f1e5ae809f0/superset-frontend/src/dashboard/components/gridComponents/Chart.jsx#L354 where the chart row limit is overwritten with maxRows property. 

We've patched Chart.jsx so that the chart property does not get overwritten and verified that the export is working.

**Comment by Enzozzzz** [comment]
This problem caused by your Elasticsearch server query limit,  just update superset config params `SQL_MAX_ROW , the value less than  65536 , it can deal your problem. my Elasticsearch server limit is 10000, so i set  SQL_MAX_ROW=9999

**Comment by Enzozzzz** [comment]
This problem caused by your Elasticsearch server query limit.
just update superset config params SQL_MAX_ROW , the value less than 65536 , it can deal your problem. 
my Elasticsearch server limit is 10000, so i set `SQL_MAX_ROW=9999`.

**Comment by Enzozzzz** [comment]
This problem caused by your Elasticsearch server query limit.
just update superset config params SQL_MAX_ROW , the value less than 65536, (you can config Elasticsearch server query limit number also) it can deal your problem.
my Elasticsearch server limit is 10000, so i set SQL_MAX_ROW=9999.

**Comment by sowo** [comment]
Thank you for the suggestion. I was aware of this solution. But, in my case it doesn't work as we need the 200000 limit for other charts.
