### ISSUE TITLE
[Prophet]Leverage predictive analytics to trigger alerts

### ISSUE THREAD

**Issue by exemplary-citizen** [apache/superset#17510]
**Is your feature request related to a problem? Please describe.**
Would love the ability to trigger alerts if new data falls outside of the confidence intervals. Would also like to display confidence intervals without enabling the forecast.

<img width="494" alt="Screen Shot 2021-11-22 at 8 44 26 AM" src="https://user-images.githubusercontent.com/51683050/142902552-86170dc1-4cb5-4023-a9b5-d6744b3a918d.png">

**Describe the solution you'd like**
this probably requires input from the superset team but possibly setting up alerts from within the `predictive analytics` tab by selecting a button.

cc: @villebro @junlincc @bkyryliuk

**Comment by bbarclay** [comment]
is this prophet? did you get it to work in docker?

**Comment by junlincc** [comment]
Heyhey, thanks for the request, this new feature is gonna be epic! I'm not sure how many people are using prophet in the community, let's kickoff a discussion and see how wider audience think. (We will post it in next weekly announcement) @villebro and I are very supportive on this!

**Comment by rusackas** [comment]
Closing this as stale, since it hasn't gotten any attenti0on in over a year. That said, it's certainly a fantastic feature request idea. If you're still hoping for this, I'd echo the suggestion to start an Ideas thread in Github Discussions, and see if it gets any traction/volunteers. 

CC @villebro just for fun since he added the Prophet feature and would probably love to know people are using it and hope to expand on it :)
