### ISSUE TITLE
[Explore][Design] Adding multiple time columns in Time section 

### ISSUE THREAD

**Issue by kasiazjc** [apache/superset#17635]
**Is your feature request related to a problem? Please describe.**
Users cannot add multiple time columns to Time section in Explore. Currently time column is added automatically as a default (and used as X-Axis if applicable) and the only action user can take is switch the time column to another one. If they want to add another time columns they have to configure them and add as filters. 

**Describe the solution you'd like**
As a first stage it would the best to make the ability to add multiple time columns in the Time section in explore. This would be easier to ready for users and allow them to configure each time column easily with adding time ranges etc.

*Main changes*
1. Time column is required and added by the user (there will be prompt/tip, required field will be highlighted)
2. The first column added is automatically set as X-Axis in Time Series Charts ("X-Axis" is added to the time columns fields in control panel)
3. User can later choose other X-Axis when they have multiple time columns added 
4. Each Time column can have its own Time Range and Time Grain if applicable (Contextual Time Grain overrides the general chart settings)

![time columns ](https://user-images.githubusercontent.com/36897697/144464610-209526a4-47a4-47ad-a8fe-46b264e656f5.gif)

*Additional Information* 
→ To make things easier for the user there will be added contextual tooltips to the time grain, x-axis
→ X-Axis check box in the modal may be hidden if not relevant to the chart 
→ Flow is available [here](https://www.figma.com/proto/pjtuSQAGRIu1PE9dYKWaUg/Data-Insights--%3E-Explore?page-id=253%3A42551&node-id=257%3A42560&viewport=241%2C48%2C0.11&scaling=min-zoom&starting-point-node-id=257%3A42560) - there are some tooltips added, the fields that you can click on will highlight once you click on the prototype

**Comment by zhaoyongjie** [comment]
Thanks for the proposal! 

There are some design/technical debts in the time-range section. Adding some backgrounds and ideas to make sure we made a conscious decision:

1. Superset was the first BI tool to support Apache Driud, so there are some Druid specific features that influenced Superset's early design. Druid is a OLAP system that uses temporal dimensional aggregation, so Druid must always include a timestamp partition(or column). Due to this [feature](https://druid.apache.org/docs/latest/ingestion/data-model.html#primary-timestamp) we have introduced time range and time grain. For other BI products, time range and time grain just a date(or datetime) filters.

2. The time dimension can be added to Groupby and selected by time column, which causes confusion for users. In fact time grain is not enabled in non-timeseries chart.
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/2016594/144837661-bfcbc4b6-1b40-4e44-b5ff-055af8755976.png">

3. categories for x-axis or timeseries for x-axis should consider.

**Comment by kgabryje** [comment]
@zhaoyongjie I think @kasiazjc proposal retains feature parity with our current solution since we can select the main temporal column (with "Use as X-Axis" checkbox) and the main time grain.
The other time column would serve only for filtering purposes.

**Comment by kasiazjc** [comment]
thanks for the comment @zhaoyongjie 🙏 

I think the things you are mentioning will be introduced in phase 2 that I'll be working on - the solution I am proposing is easier and faster to implement at that moment. As Kamil mentioned, when categorical X-Axis will be merged we will be able to remove the x-axis check box from the modal. Later on we will combine filters + time section to make it easier for the users. So taking it all step by step

**Comment by rusackas** [comment]
I'm removing the `need:consensus` label here - I don't think that this change is big enough to warrant asking the entire dev@ list to draw their attention to it. I think this is merely a necessary step toward a larger vision of a more generalized categorial/temporal x-axis, and we should just proceed if there will not be any breaking changes made (which I do not foresee here).

**Comment by rusackas** [comment]
This was floated to the dev@ list as part of a weekly announcement. Closing this, and calling it OK to proceed :)
