### ISSUE TITLE
No translation key found in apache superset

### ISSUE THREAD

**Issue by harisraj92** [apache/superset#17742]
I am new to apache superset and I install in ubuntu server 20.0

I'm facing an issue **No translation key found** when i create new chart in apache superset 

kindly help me

<img width="955" alt="image" src="https://user-images.githubusercontent.com/96099215/145931751-f587f53e-961a-4066-a2ef-af71b70e09ab.png">

**Comment by geido** [comment]
Hello @harisraj92 which Superset version are you running?

**Comment by rusackas** [comment]
Closing due to lack of follow-up information after nearly a year.

**Comment by foreground-voice** [comment]
this comment from jed.js can help us:

<img width="499" alt="image" src="https://github.com/user-attachments/assets/0930b841-776c-447b-b22d-af644d5ef97d">

I had the same error. Because you accidentally trying to get translation of empty text "". Just patch t() function to return empty string backward in this case.
