### ISSUE TITLE
"Initial connection" randomly fails on Edge (Win11, with Docker + WSL2). Works on Firefox.

### ISSUE THREAD

**Issue by acirulis** [apache/superset#18194]
After setting up Superset in WSL2 environment with Docker, everything works as expected on Firefox browser. However, on Edge, it randomly fails to connect with "Initial connection" never finishing. I have never had similar problems with Edge before, so I am creating issue here, even it may not be related to Superset.

#### How to reproduce the bug

1. Install Superset on Windows 11 with latest updates, Docker, WSL2, and Ubuntu distro setup. (from master branch)
2. Start Edge browser (latest Version 97.0.1072.69)
3. Open http://localhost:8088
4. Login with admin:admin credentials and start browsing

### Expected results

Everything works

### Actual results

Around 40% (subjective) of network requests fails during "Initial connection" phase. Please see screenshot.
If I switch to other browser (e.g. Firefox), problem is gone.

Nothing in docker logs, as these failed requests don't reach app. Only reason I am creating this issue is because I haven't had similar problems with Edge on any other Docker based projects/environments I am using.

#### Screenshots

![image](https://user-images.githubusercontent.com/27766961/151327205-1f2ce5ae-7fc3-4ed5-abbf-6b5f81d04bf4.png)

### Environment

(please complete the following information):

- Edge browser (latest Version 97.0.1072.69)
- superset version: Docker container reports: `Superset 0.0.0dev`. But I am using image apache/superset  pulled on Jan25`22
Launched from docker environment with docker-compose-non-dev.yml

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment]
Hey @acirulis as a heads up, WSL isn't a testing target for Superset (although we generally expect things to "just work" because it's WSL is trying to mirror a Ubuntu environment). Neither is Microsoft Edge, but again in theory it should be similar to Chrome because of the underlying engine choice.

Re: `0.0.0dev` you're spot on that this just means you're using a non-versioned release. It's an attempt to follow semantic versioning protocol but essentially convey "dev" version.

Without logs or errors, this is going to be super hard to replicate. Let us know if you're able to interrogate this further or if you come up with any other hints that allow someone else to replicate this and maybe fix this. Of course, we'd also appreciate your contribution here as well :)

**Comment by acirulis** [comment]
Ok, so I decided to try Chrome as well, since it uses same engine as Edge. The problem was even worse. Then I found https://github.com/microsoft/WSL/issues/4340 which seems related - after switching from http://localhost to http://127.0.0.1 or http://my-custom-hostname.local.io problem disappeared. I guess problem is hidden somewhere in between browser / WSL / webserver (Flask) connections. I will be closing the issue for now but maybe it will help somebody with same problem.
