### ISSUE TITLE
Login paged shows even though I use only one oauth provider

### ISSUE THREAD

**Issue by EinavDanielDX** [apache/superset#18573]
Keycloak is my only oauth provider, yet login page asks me to select auth provider.

#### How to reproduce the bug
1. set up login with keycloak auth provider
2. login

### Expected results
Superset should skip the provider selection under /login/ and redirect straight to the provider login page and from there to app

### Actual results
I am being redirected to /login/ and has to choose the oauth provider

#### Screenshots
![image](https://user-images.githubusercontent.com/97506919/152376426-19629caa-87af-4acd-aeb6-fa99c831b3c9.png)

### Environment

(please complete the following information):

- browser type and version: chrome Version 97.0.4692.99 
- superset version: Superset 1.4.0
- python version: Python 3.8.12
- keycloak version: 15.0.2

### Additional context
According to [this](https://github.com/dpgaspar/Flask-AppBuilder/pull/1618) MR, skipping the login page should be enabled by default when using Flask-AppBuilder > 3.3.1

**Comment by kamalkeshavani-aiinside** [comment]
@EinavDanielDX 
This is not a bug.
A new PR in FAB 3.3.4 changed the OAUTH login flow, you can read more about it here:
https://github.com/dpgaspar/Flask-AppBuilder/pull/1707

**Comment by EinavDanielDX** [comment]
Thank you for the quick response.
Is there any way to override this behavior with superset settings?

**Comment by EinavDanielDX** [comment]
Hi,
Since this  issue seems to be FAB related we went for a different approach, implementing SSO with OIDC instead of OAuth, using [this guide] (https://naween-banuka.medium.com/apache-superset-security-implementing-using-keycloak-2fbaa182fb2c)

Would be awesome if you make it work using simple configuration instead of adding these scripts!

**Comment by rusackas** [comment]
Closing this out since (a) the original author seems to have found another way around this (b) whether or not it's a bug seems to have been settled, and (c) the issue has gone cold for upward of a year. If needed, we can re-open or start a new issue/discussion as deemed appropriate.

**Comment by oldchurch12** [comment]
Hi, I am using 3.1.0 and also 3.1.1 - I have not found any workaround,, and the behavior is  annoying to the customer. Is there anyway to reopen the discussion ?

**Comment by felpasl** [comment]
Im implementing a iframe with superset dashboard and keycloak authentication, at first view of application, the login button has showing at first, annoying

**Comment by Mistuke** [comment]
I also would like the automatic sign in worklow to come back as an opt in thing. Modifying the views is messy and makes upgrades hard.

**Comment by c0da** [comment]
Please refer to [this comment](https://github.com/dpgaspar/Flask-AppBuilder/issues/2225#issuecomment-2074682623) for the details and code on how to resolve this issue. It worked for me, at least.

**Comment by Mistuke** [comment]
> Please refer to [this comment](https://github.com/dpgaspar/Flask-AppBuilder/issues/2225#issuecomment-2074682623) for the details and code on how to resolve this issue. It worked for me, at least.

Thanks, that worked for me as well!

**Comment by rusackas** [comment]
If there's a code fix, I would recommend opening a PR (even if iti's to the Docs site)! It's open source, so contributions are always welcome so others don't get stuck.

**Comment by user1500177** [comment]
@c0da  , @Mistuke 

Is it working for you guys in the superset version  6.0.0

The same appraahc in the comments(https://github.com/dpgaspar/Flask-AppBuilder/issues/2225#issuecomment-2074682623) used to work for me until version 5 , but in superset version 6.0.0 it is not which is why i am asking 
Could someone say they have found an alternative which is scalable and doable from superset_config.py ??

Also earlier i was able to add some columns to the superset ab_user table and all like custom_fields and by keeping the edits within the FAB i was able to add some more things like in the userinfo page it used to come UP those custom fields , But now it not shouwing up  - I had made a detaild dicussion here @( https://github.com/apache/superset/discussions/36925) , If anyone have found something usefule could you guys help me 

I noticed that in the newer version that a call is being made to the api/v1/me which wasnt there in the version 5 , Now without modfying the other CORE codes of superset and just making changes from a config level is it possible to do or achevie this ?
