### ISSUE TITLE
use db2 connect driver but return an error

### ISSUE THREAD

**Issue by RoderickAdriance** [apache/superset#18614]
![image](https://user-images.githubusercontent.com/31174431/152940152-08368c72-f1ee-43cc-a8ee-a9de6745075c.png)

I have been installed db2 driver and use official command 'pip install ibm_db_sa' to install.
please tell me how to resolve it !

**Comment by rusackas** [comment]
Looks like there are two ways to connect to DB2: https://superset.apache.org/docs/databases/ibm-db2/

Since this doesn't seem to be a bug (or at least a corroborated one), but more of a configuration issue, I'll close this as stale since it hasn't gotten attention for nearly a year. Please feel free to reach out on Slack or open a Discussion thread if this still needs revisiting. Thanks!
