### ISSUE TITLE
TLS with Config Store Postgres

### ISSUE THREAD

**Issue by dmosruby** [apache/superset#18797]
**Is your feature request related to a problem? Please describe.**
We would like to be able to bring our own postgres for Superset config store but the helm chart doesn't support TLS parameters. and neither does the superset CLI.

**Describe the solution you'd like**
Support TLS configuration for the postgres config connection. Specifically:
* The init job will need its own set of admin certs since it creates the users/roles/table structures with an elevated user.
* The superset deployment will need to take in certs to be able to connect to the config store with its own user.

**Describe alternatives you've considered**
In order to use our own postgres with superset, we would need to downgrade the TLS for the rest of our ecosystem which isn't ideal.
Today, instead we just let superset bring its own postgres but that is a waste of resources that we would like to avoid.

**Additional context**
Postgres TLS Auth Type Certificate Authentication requires the common name to match the username you are using to log in with so this is why the Init Job & the normal running application will need separate certs to connect with. [Postgres Certificate Authentication](https://www.postgresql.org/docs/14/auth-cert.html)

**Comment by rusackas** [comment]
Closing this because (a) it has gone inactive for over a year, and (b) we're whittling Github Issues to be just bug reports, and taking Feature requests over to Discussions. 

If you'd like to continue seeking community support of this feature request, please open a new [Ideas thread](https://github.com/apache/superset/discussions/categories/ideas) in our [Github Discussions](https://github.com/apache/superset/discussions) area.
