### ISSUE TITLE
[Native Filter] default number filter is not showing properly when user choose max/min in single value

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#18985]
When user setup a default value for number filter, then user select single value for the number filter and change the number to be maximum or minimum, the default value did not stay on the selected value.

#### How to reproduce the bug

1. Go to native filter and setup a number filter
2. Select single and choose max or min
3. Select default value for the filter and save changes
4. Go back Native filter configuration, and check default value
5. Change the single value and save
6. Check the default value on native filter on dashboard view

### Expected results

1, in native filter, default value will be in <= single value or >= single value range 
2, in dashboard view, native filter default value will reflect the change

### Actual results

1, default value bar will change to max or min number, not reflecting the correct range
2, in dashboard view, native filter default value did not reflect the change

#### Screenshots

https://user-images.githubusercontent.com/81597121/156213408-097c4e05-268f-414a-a7dc-9b2f55799790.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by volhahedranovich** [comment]
I face the same issue. Please fix it.

**Comment by rusackas** [comment]
@volhahedranovich which version of Superset are you running, just so we know. I'm guessing this IS still an issue in Superset 3.x, but since it's a bit of an edge case, I doubt any core contributors will be getting to it anytime soon. If anyone reading this wants to open a PR, we'll be happy to review it.

**Comment by rusackas** [comment]
Ohhh... actually, I just realized that comment was from Jan 2023, where I thought it was from 2024. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still seeing this as a problem in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
