### ISSUE TITLE
Pivot Table v2 - missing pivot table type dropdown in v1.4.0

### ISSUE THREAD

**Issue by Shubham21k** [apache/superset#19151]
Hi all,

We are facing an issue in customising superset pivot table v2 charts.

In superset version 1.1, we used the row formatting feature through _table row heatmap_ option in `pivot table type` dropdown.
<img width="325" alt="Screenshot 2022-03-15 at 5 57 05 PM" src="https://user-images.githubusercontent.com/85898765/158377555-fbcb94dc-fa11-4a7c-82a6-03289ad19400.png">

Now in version 1.4.0, dropdown is missing, but only column formatting dropdown is available.
<img width="503" alt="Screenshot 2022-03-09 at 6 37 37 PM" src="https://user-images.githubusercontent.com/85898765/158378218-5f9f5db7-2d22-4f0e-8f6f-40b7a7d8d960.png">

Please help fix this

**Comment by kgabryje** [comment]
That's correct, pivot table type control has been replaced by conditional formatting. We also added a migration script to make the transition smoother (cc @villebro)

**Comment by Shubham21k** [comment]
@kgabryje Is there a way to perform `row formatting`(Pivot table type : table row heatmap) in v1.4.0

**Comment by kgabryje** [comment]
@Shubham21k I think that you can only perform formatting corresponding to the old "table heatmap" (not "row") by using None operator - that will highlight values with colors based on min/max values in the whole table rather than current row.
I can see how this might be a blocker for you and your team - I'd suggest you open a feature request for row/column heatmaps. As of now I can't commit to a specific timeframe to implement that feature, but I'll keep you posted when it's being worked on.
CC @rusackas

**Comment by rusackas** [comment]
Sounds like this issue is effectively addressed. If we're in need of new features here, we can open an "Ideas" thread in the Discussions area.
