### ISSUE TITLE
slug is not updated when importing dashboard via API

### ISSUE THREAD

**Issue by srinisubramanian** [apache/superset#19268]
The slug is not set when importing a dashboard

#### How to reproduce the bug

Set a slug and export a dashboard using the export API.  Import the dashboard using the /import API.  The slug is not set after import

### Expected results

Slug should be set to the value in the json

### Actual results

Slug is not set

### Environment

(please complete the following information):

- API superset version 1.4.1
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment]
@srinisubramanian have you enabled the `VERSIONED_EXPORT` feature flag, or are you using the old JSON import/export?

**Comment by srinisubramanian** [comment]
I had not set VERSIONED_EXPORT as I thought it was defaulted to True and hence was doing the JSOn stuff.

Anyways I now added it to superset_config.py and cleared out the database and reinitialized the test instance.  Also changed dev landscape to include the VERSIONED_EXPORT.  The export API now downloaded a zip file.

Then attempted the import via the API.  THrows a 500 error:
```
2022-03-21 14:20:56,235:INFO:werkzeug:127.0.0.1 - - [21/Mar/2022 14:20:56] "POST /api/v1/dashboard/import HTTP/1.1" 308 -
Command failed validation
2022-03-21 14:20:56,358:INFO:superset.dashboards.commands.importers.dispatcher:Command failed validation
Error importing dashboard
2022-03-21 14:20:56,358:WARNING:superset.views.base:Error importing dashboard
2022-03-21 14:20:56,361:INFO:werkzeug:127.0.0.1 - - [21/Mar/2022 14:20:56] "POST /api/v1/dashboard/import/ HTTP/1.0" 500 -
```

**Comment by srinisubramanian** [comment]
@villebro  I did make some more progress.  Rather than using the API I imported using the UI and I was prompted for the password.  Looks like the database to connect to seems to be validated by connecting and in my case the same user was not existing.  Once I set that up the import went through.  I did a reimport and that prompted for an overwrite without prompting for password and did go through.  

In this case the slug was also set.  I will check more with API now, thanks.

**Comment by srinisubramanian** [comment]
@villebro  While I am able to import new dashboards created and some really simple dashboard examples, some other dashboards that I created BEFORE the VERSIONED_EXPORT was turned on, I am not able to import.  It keeps failing with a validation error.

Question:  Can dashboards created when VERSIONED_EXPORT was false, be exported and imported?  Looks like some uuid issues?

**Comment by villebro** [comment]
I believe they're incompatible, unfortunately. Are you able to re-export the old dashboards with the flag turned on?

**Comment by srinisubramanian** [comment]
I can re-export. But import keeps failing.

**Comment by srinisubramanian** [comment]
Details captured in #19297 .. closing this issue

**Comment by Naresh-Challa** [comment]
**Hi Team,**
We are facing an issue in Importing the Dashboard 
Export a dashboard with VERSIONED_EXPORT=true. export is working fine 
When I try to import a dashboard on the same instance or another instance and it fails with a **command validation error.**

**How to reproduce the bug**

**Create a dashboard, save and export it (VERSIONED_EXPORT = true)**
Try to import and fails with a validation error
import the dashboard using the /import API. 
The issue is that a simple dashboard with just one or two charts seems to work. A more involved dashboard such as the one I am building fails

**Expected results**
Import Dashboard should  be successful

**Actual results**
Fails import
**Error:**
Superset 1.5.0
**API Version:**
POST //api/v1/dashboard/import/ HTTP/1.1" 302 221 "-" "curl/7.65.0"

curl -k -X 'POST' 'https://superset-URL/api/v1/dashboard/import/' -H 'accept: application/json' -H "Authorization: Bearer $token" -H 'Content-Type: multipart/form-data' -F 'formData=@test1.zip;type=application/x-zip-compressed' -F 'overwrite=true' -F 'passwords={ "databases/MySQL_test.yaml":"Pwd", "databases/mysql_test2.yaml" : "PWD"}'


**Screenshots**
just Command error

**Environment**
UAT

**API superset version 1.501**
**any feature flags active:**
VERSIONED_EXPORT=True from superset_config file

please help on it, we are in trouble chasing it 

Thanks
Naresh Challa
