### ISSUE TITLE
[dataset] dttm will change to string type for virtual dataset in sqlite

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#19453]
dttm will change to string type for virtual dataset in sqlite, this issue is sqlite only, can not reproduce in other db 

#### How to reproduce the bug
1, connect to sqlite db
2, go to sql lab, select datetime column and run query
3, open dataset in explore
4, click dataset edit and look for the datetime column for data type

### Expected results
datetime column should show type in datetime in virtual dataset for sqlite

### Actual results
datetime column show type in string in virtual dataset for sqlite

#### Screenshots

https://user-images.githubusercontent.com/81597121/160977186-5dae1174-d4d6-468d-80cc-d7f903358792.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by bispaul** [comment]
Hi can this be assigned to me. Please let me know?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  

@bispaul if this is still an issue, please feel free to open a PR. Sorry I didn't see that comment sooner. 

CC @sadpandajoe for good measure.
