### ISSUE TITLE
Long dashboard native filters options are trimmed

### ISSUE THREAD

**Issue by aspedrosa** [apache/superset#19787]
## Screenshot

![Screenshot_20220420_100825](https://user-images.githubusercontent.com/23409890/164193711-4374e288-d65e-4eef-adfd-594c92af8113.png)

## Description

As you can see on the screenshot above, all the displayed options are trimmed. This becomes more problematic in our case since there is a great similarity between options. As a workaround, the user can of course do a mouse over to see the full text, but I think this is not evident.

As an alternative, we could use a filter box component and stretch it out, but since the goal is to move away from the filter box component I don't think this is an option for the future.
![Screenshot_20220420_101821](https://user-images.githubusercontent.com/23409890/164195588-fea6813b-4faf-4e8c-8553-06b64b6b963b.png)

**Comment by rusackas** [comment]
Tempted to close this as stale, since I think the mouseover/tooltip solves this for most users. Wondering if @kasiazjc has any ideas of how this might be improved, though.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
