### ISSUE TITLE
how to add custom role that can assign spacific roles only to users not all the available roles

### ISSUE THREAD

**Issue by moathOSA** [apache/superset#19827]
the case that i have is
i want to create a role ex- admin
and this admin have the ability to add users and assign two roles only ex- viewer , publisher to the added users
how to do something like this ??

superset version 1.4.1
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this since 
• it's remained inactive for over a year
• it's more feature/how-to request than bug report.
• it's regarding a no-longer-supported version of Superset.

If you wish to keep digging into this, I'd suggest you bring it to [Superset Slack](http://bit.ly/join-superset-slack) or take it up in a Q&A thread in our [Github Discussions](https://github.com/apache/superset/discussions) area.
