### ISSUE TITLE
Bar Chart can not highlight item. 

### ISSUE THREAD

**Issue by ChunshengZhao** [apache/superset#19892]
Superset Version: 1.5

VISUALIZATION TYPE: Bar Chart

![图片](https://user-images.githubusercontent.com/9263377/165879550-a1aa101e-6a45-4488-96b9-c49a848b0766.png)

BTW: Time-series Bar Chart v2 is normal.

**Comment by AkashBoora** [comment]
This issue is related to NVD3 package, the events of chart is handled in the NVD3 package. For some charts like cumulativeLineChart the highlight property is added to the returned series object, but for the charts like multiBarChart this property is not getting added. And the function which handles events in the NVD3 package is not returning the event, so we dont have access to the mousePositions which tells us the item which got focused. 

I tried different way with the calssname, Actually the bar which is getting fouces have the class name name as 'hover'. So based on that i tried to get the series information. By adding following code am able to get the highlighted item in tool tip.

**Added code:**
**File Name**: ./superset-frontend/plugins/legacy-preset-chart-nvd3/src/utils.js
**Method Name**: generateCompareTooltipContent
  const hoverElement = document.getElementsByClassName('hover')[0];
  const parentElement = hoverElement.parentElement
    .getAttribute('class')
    .split('-')
    .slice(-1);
  d.series[parentElement].highlight = true;

Loom Video: https://www.loom.com/share/3ed6e28d62fe41328b6896d919c2c741

NVD3 package link: https://github.com/nvd3-community/nvd3/tree/gh-pages/src/models
Cumulative line chart: https://github.com/nvd3-community/nvd3/blob/gh-pages/src/models/cumulativeLineChart.js
MultiBarChart: https://github.com/nvd3-community/nvd3/blob/gh-pages/src/models/multiBarChart.js

So could you please tell me wether we can do like this or not, if not please tell me what we can do about this issue thanks!

**Comment by rusackas** [comment]
The NVD3 bar chart has already been migrated to the newer ECharts counterpart. Closing this as resolved.
