### ISSUE TITLE
Partition Chart can not group null value.

### ISSUE THREAD

**Issue by ChunshengZhao** [apache/superset#19891]
Superset Version: 1.5

VISUALIZATION TYPE: Partition Chart

Query: GROUP BY Name,ProjectName
Metrics: SUM(FQty)

Data Results:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<body link="#0563C1" vlink="#954F72">

Name | ProjectName | FQty
-- | -- | --
ZhangSan | P1 | 1
LiSi | P2 | 1
WangWu | N/A | 1

</body>

</html>

Bug：
Unexpected error
"['WangWu '] not in index"
![图片](https://user-images.githubusercontent.com/9263377/165879483-5887ae95-5518-491b-915d-9ba8adc2934e.png)

Temporary Solution:
Filters Add: ProjectName IS NOT NULL

**Comment by rusackas** [comment]
@ChunshengZhao is this still happening in current Superset (2.1.0)? I was tempted to close this as inactive, but I'm guessing not much has changed with this chart type.

**Comment by ChunshengZhao** [comment]
> @ChunshengZhao is this still happening in current Superset (2.1.0)? I was tempted to close this as inactive, but I'm guessing not much has changed with this chart type.

I am currently using version 2.0.0 and this issue still exists. Due to special reasons, I cannot test version 2.1.0. Thank you for your attention.

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x (which it may well be!), we can re-open this - just let us know. Or, feel free to open a new issue with updated context. As always, PRs are welcome from anyone to fix the issue if it still exists.
