### ISSUE TITLE
Superset not showing table name when connected spark sql.

### ISSUE THREAD

**Issue by pawar20396** [apache/superset#19952]
Hello, I connected superset using Spark SQL beeline ie jdbc:hive2://localhost:10000. I created two tables in my database. My connection is successfully connected. In superset, I can see database names. Superset shows database names multiple times even in the table name column so I am unable to select any table. Is there any solution for this?

**Comment by beat4ocean** [comment]
i also had this problem when i connected to spark_sql but not hive_sql

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
