### ISSUE TITLE
Sql lab search but don't have header. How can I solve it?

### ISSUE THREAD

**Issue by lqiuhong** [apache/superset#20038]
![image](https://user-images.githubusercontent.com/103475618/167993004-a597cb3b-f9da-4f28-b65d-d72b2e3abd4f.png)

**Comment by yousoph** [comment]
Hi @lqiuhong , 

Search in the SQL Lab text editor was enabled with this change: https://github.com/apache/superset/pull/19328 
Is that what you're looking for? 
If not, can you please clarify the issue and fill out the bug report template (below)? 

Thanks! 

-----

A clear and concise description of what the bug is.

#### How to reproduce the bug

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots

If applicable, add screenshots to help explain your problem.


### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Add any other context about the problem here.

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
