### ISSUE TITLE
If the DataGridView control's data source has a column of images,  then can images be displayed ?

### ISSUE THREAD

**Issue by SakshiTharkude** [apache/superset#20239]
Can we process an image in superset data grid ?
If yes, how ?

**Comment by SakshiTharkude** [comment]
If the DataGridView control's data source has a column of images,  then can images be displayed ?

**Comment by rusackas** [comment]
You can use HTML in the Table chart now, if that's what you're looking to do. 

Meanwhile, closing this issue as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
