### ISSUE TITLE
Superset bug doesn't work dashboard

### ISSUE THREAD

**Issue by jo1013** [apache/superset#20240]
#### How to reproduce the bug

After clicking on the dashboard, I go back in to check after updating the chart, but the dashboard does not work shows that the chart that I was trying to add has been added, so it is not clicked, so I cannot modify it.

**Comment by yousoph** [comment]
Hi @jo1013 , can you please fill out the bug template? In this case, a video might be helpful in helping us understand the issue that you're seeing. Thanks! 

Template below: 

A clear and concise description of what the bug is.

#### How to reproduce the bug

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots

If applicable, add screenshots to help explain your problem.


### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Add any other context about the problem here.
