### ISSUE TITLE
superset-frontend fail run in master branch

### ISSUE THREAD

**Issue by Bluestar123** [apache/superset#20246]
#### How to reproduce the bug

1. Go to  folder superset-frontend
2. npm i
3. npm run dev-server

### Expected results
run success
what you expected to happen.

### Actual results

what actually happens.

#### Screenshots
<img width="612" alt="image" src="https://user-images.githubusercontent.com/21274165/171677709-54e478e6-d165-4bbc-a291-09003fd01a71.png">

### Environment

(please complete the following information):

- browser type and version:  chrome
- superset version: `superset version`.  1.5.0
- python version: `python --version`
- node.js version: `node -v`. 14.19.0
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Hmm... not sure about this particular error, but I think we need to update mapbox-gl in those two plugins anyway since it's ancient. Are you perchance a developer with any bandwidth to handle a package bump? If not, I'm semi-optimistic that the package bumps on my radar will take care of this sooner or later. It looks like webpack completed nonetheless... are you able to run Superset and keep moving?

**Comment by userxxj** [comment]
The same problem, Superset did not move forward

**Comment by rusackas** [comment]
Should be all good nowdays, but let us know if that's not the case somehow.
