### ISSUE TITLE
very minor issue, padding between widgets sometimes not working

### ISSUE THREAD

**Issue by csamsel** [apache/superset#20303]
## Screenshot

![image](https://user-images.githubusercontent.com/914803/172553006-a8ea01de-fed2-42f4-a88b-6e0efac15dab.png)

## Description

Very minor issue: Sometimes (i think when widgets are arranged both vertically and horizontally), they overlap each other. It's only visible when hovering e.g. over filters so the widget frames are highlighted. 

## Design input
don't think this one requires specific input :)

**Comment by gbusch** [comment]
Some addition to Christian's description (working in the same team):
This happens when using tabs. 
The same dashboard with the same charts has vertical padding when it is not in tabs. 
As soon as we add tabs and move the charts to one of the tabs, the vertical padding vanishes and it appears as shown above.

**Comment by rusackas** [comment]
This is interesting... hopefully we can take a look at it at some point, but I'm not sure if/when it'll get prioritized. Any interest in digging a little deeper and opening a PR, perchance?

**Comment by csamsel** [comment]
unfortunately we are not very good at CSS and JavaScript and quiet busy with usual work, so this is not really a priority for me either.

**Comment by gbusch** [comment]
@rusackas Maybe this PR #20366 solves it already?!

**Comment by gbusch** [comment]
@csamsel was fixed in the PR above, can close this issue
