### ISSUE TITLE
Metric calculation error "Part of a Whole"

### ISSUE THREAD

**Issue by apecortes** [apache/superset#20335]
On Superset 1.5.0.

#### How to reproduce the bug

Giving the following dataset:

![image](https://user-images.githubusercontent.com/91876082/172872466-d147603b-d896-4673-aeae-3dce4820c5d3.png)

Having created the metric Users: COUNT(DISTINCT userId). We see that there are 4 DISTINCT userId. But the calculation at the level of the parent is a sum of the children, and it is not correct.

There is no difference between COUNT and COUNT DISTINCT.

### Expected results

The expected result is that at the level of the parent there will be 4 and not 5.

### Actual results

The end result is that COUNT(userId) and COUNT(DISTINCT userId) give the same result.

#### Screenshots

**COUNT**
![image](https://user-images.githubusercontent.com/91876082/172873875-220e0fdc-7c76-4e9b-bab9-a2a878cb31fe.png)

**COUNT DISTINCT**
![image](https://user-images.githubusercontent.com/91876082/172873729-086a4b35-8d06-41e6-82a2-283cfcc0bb48.png)

**Comment by rusackas** [comment]
I think this is behaving correctly. Since you're using the two GroupBy dimensions, you actually DO have 3 distinct users that share that category/course. The 5 at the top is merely a sum of what's displayed in the tree, which is accurate for the controls setup you're using. If you get rid of your GroupBy dimensions, you should see 4 in one, and 5 in the other. Closing this for now, but if you think I've misconstrued something, please keep the conversation going, and we can re-open.
