### ISSUE TITLE
i want contribute with translating json and markdowns to es, de, fr and it my languages domain

### ISSUE THREAD

**Issue by johnfelipe** [apache/superset#20341]
i want contribute with translating json to es, de, fr and it my languages domain

Pls tell me if i can PR or how can contribute or collaborate with this json and md files

**Comment by rusackas** [comment]
I assume you mean converting the Superset language strings of the UI into es/de/fr? If so, that would be very much welcomed! I would only ask that you separate each language into separate pull requests so that we can assign appropriate reviewers.

The basic documentation is here:
https://github.com/apache/superset/blob/master/CONTRIBUTING.md#add-translations

And you'll see in that short description there's a link to the more detailed documentation about how to generate the files needed for your eventual PR(s). 

Calling this closed, as I assume that's the help you needed, but if I've misinterpreted and there's something else you want to work on, let us know!

**Comment by johnfelipe** [comment]
In using GitHub desktop
How can create PR individual?
