### ISSUE TITLE
Superset converts min with max in the Tukey WHISKER/OUTLIER OPTIONS

### ISSUE THREAD

**Issue by wojciech-sak** [apache/superset#20454]
Hi, I'm using box plot to visualize my data in Superset. I have chosen `WHISKER/OUTLIER OPTION: Tukey` and it seems it has a bug, min is converted from max:

![image](https://user-images.githubusercontent.com/61534234/174807560-e6944eec-4bca-4678-8f2c-f7d793778f60.png)

As far as I know it shouldn't behave in this way, any other  `WHISKER/OUTLIER OPTION`  (`Min/max no outliers`, `9/91 percentiles`, `2/98 percentiles`) is ok. Here is `Min/max no outliers`:

![image](https://user-images.githubusercontent.com/61534234/174808779-68641920-ebc2-4d7c-ab79-1698753a6f91.png)

I would appreciate any tips on how to get around this, if possible.

I am using Superset v: 1.4.0.

**Comment by rusackas** [comment]
This issue might still exist (I'm not sure, it needs validation) but I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem — or we can re-ope this one.
