### ISSUE TITLE
[Histogram] A (unrelevant) sampling is done when building the chart

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#20532]
The histogram plot makes a sampling by reading only the 10k first rows.
By doing this, it takes the 10k first rows of the database, which is not random at all and the histogram is wrong.

#### How to reproduce the bug

1. Make a histogram on a database containing more than 10k rows
2. Display the results

### Expected results

The histogram shoud be made on the total database (using a GROUP BY function in the query for instance)

### Actual results

The histogram is made on the 10k first rows

#### Screenshots

/

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 103.0.5060.53 (Official Build) (x86_64)
- superset version: 1.5
- python version: 3.9
- node.js version: /
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

/

**Comment by rusackas** [comment]
Same as [this issue](https://github.com/apache/superset/issues/20533), I don't know of a standard means to get random rows, but we're open to proposals/PRs here. Meanwhile, closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog.

**Comment by ValentinC-BR** [comment]
Same as [this issue](https://github.com/apache/superset/issues/20532#:~:text=Same%20as-,this%20issue,-%2C%20I%20don%27t%20know), we should either fix it, or remove the chart if we can't fix it.

An idea would be to build the histogram inside the query.

**Comment by rusackas** [comment]
> Same as [this issue](https://github.com/apache/superset/issues/20532#:~:text=Same%20as-,this%20issue,-%2C%20I%20don%27t%20know), we should either fix it, or remove the chart if we can't fix it.
> 
> An idea would be to build the histogram inside the query.

As we move to ECharts, and away from some of the oddball dependencies that are part of the Histogram chart, I'm onboard with deprecating it in 5.0. ECharts doesn't have a direct replacement, since the bucketing logic isn't done by ECharts itself. 

If you have a proposal of how to do this better in a new plugin and support the random sampling you're after, we're VERY open to contributions/proposals in this area. We'd love the help.

I love the idea of grabbing random rows as part of the query, but unfortunately `ORDER BY RANDOM()` is different in a whole bunch of SQL flavors. Maybe @villebro knows if there's a way to accomplish that goal in the "BuildQuery.ts" layer so it automatically chooses `RAND()/RANDOM()/NEWID()/DBMS_RANDOM.VALUE/etc), but I sure don't.
