### ISSUE TITLE
Do you plan to support influxdb in the future?

### ISSUE THREAD

**Issue by lcwSeven** [apache/superset#20721]
Do you plan to support influxdb in the future?

**Comment by srinify** [comment]
hey @icwseven any SQL speaking database can be made to work in Superset but there needs to be a Python DB API 2.0 driver & SQL Alchemy dialect.

AFAIK the InfluxDB community hasn't created these yet, so that's prevented support for Influx in Superset. Even this is similar to SQLAlchemy syntax but not 100% adherent: https://github.com/amancevice/influxalchemy

Here's some background context on what's needed:

- https://preset.io/blog/building-database-connector/
- https://preset.io/blog/improving-apache-superset-integration-database-sqlalchemy/
