### ISSUE TITLE
Allow to define color schema at visualization level!

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20739]
Motivation:
For one dashboard I was need to create
2 country maps that should show metric in red gradation ,
one map was "sum" and one was "margin" 

In visualization editor it was all well (sum map was "red" where second was "pink") so it was very informal.

But after attaching to dashboard they get dashboard color schema (mostly blue)
and totaly lost all visual information that was based on color.

Color is not just "style" that should be "unified for dashbord for nice look", colors are informal itself, so if it's required - visualization should have own color schema!

**Comment by stasDomb** [comment]
You can resolve this in Edit Dashboard -> Dashboard Properties -> Advanced. There are JSON Metadata and here you can add the parameter **label_colors**:
  ```
"label_colors":{
    "2019": "blue",
    "2020": "black",
    "2021": "red",
    "2022": "green",
    "2023": "orange"
  }
```

**Comment by rusackas** [comment]
If you're saying what I _think_ you're saying, that a categorical color palette on the dashboard level is _overriding_ a sequential color palette as chosen by the visualization, then that could be considered a bug. 

If you're saying that you want to have a chart color palette _override_ the dashboard color palette, then that's a (surprisingly  complex) feature request.

I'm not sure which is the case, but I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering either of the above as a problem in current versions (currently 3.x) please open a new Issue with updated context and reproducible examples/screenshots, or raise a PR to address the problem. Thanks!
