### ISSUE TITLE
Mixed two-series chart - cannot define minimax for distinct Y scales

### ISSUE THREAD

**Issue by comdiv** [apache/superset#20740]
Looks like feature request, but it's so strange, and looks like bug.

Where is Mixed time-series chart, that can show 2 set of data on distinct 2 Y scales:

![image](https://user-images.githubusercontent.com/2387862/179446339-234779ac-d941-4ce3-9aab-a1b78cdccf97.png)

Both scales has own config expect... min-max! They share it!

So in example above i can set 10M-20M and lost line (it will be at bottom),
and I cannot set 0.3 - 0.6 because it will breack down bars!

I think it's BUG, because main goal of TWO-Y charts is to allow show 2 different rows with 2 different measurement at Y axis, and min-max is most freaquently used feature of such charts.... Lack of it here looks like bug

**Comment by rumbin** [comment]
Confirming this observation

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
