### ISSUE TITLE
Access denied/ Failed to Load Chart while opening/ Creating charts

### ISSUE THREAD

**Issue by adityashankar2016** [apache/superset#20763]
Hello All,
I am facing issues when i am editing charts. When clicking on three vertical dots i am getting error like failed to load charts. When clicking on datasets  and viewing any datasets(physical or virtual), i am getting error like Access is denied. I have all the admin privileges for creating charts. I have compared all the roles with my local superset installed.
This issues is coming from 18th July 2022. Before this there were no such issues.
Kindly provide your input on this.
Thank You!
Regards,
Aditya Shankar

**Comment by Always-prog** [comment]
+1 here.
I runned `superset init` , but it don't fix that problem.

**Comment by ohitsdoh** [comment]
@Always-prog did you ever find a solution to this?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
