### ISSUE TITLE
Multi-level Sankey diagram

### ISSUE THREAD

**Issue by mlmaverick** [apache/superset#20887]
Unable to get the multi-level sankey diagram even though I have my table in the format as recommended in the #3059 

source, target, count
step-1, step-2, 10
step-1, step-3, 30
step-2, step-4, 10
step-2, step-5, 30

#### How to reproduce the bug

1. Get the data in the above structure
2. Explore the data, and select Sankey diagram.
3. Select source and target in `Source / Target columns`
4. Use the metric as `SUM(count)`

### Expected results

![image](https://user-images.githubusercontent.com/105640903/181217688-5d634de4-a2c6-4db2-bcf6-c5fe7de9f3af.png)

### Actual results

![image](https://user-images.githubusercontent.com/105640903/181216749-4c81901b-862d-4e90-9949-edd846c17bb0.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome and Version 103.0.5060.134 (Official Build) (64-bit)
- superset version: `1.5.0`
- python version: `3.8.12`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  

The sankey definitely works... holler on Slack if you need help with it. [Superset Slack](http://bit.ly/join-superset-slack)

**Comment by ariel-sofi** [comment]
Opened https://github.com/apache/superset/pull/42477, which adds an optional ordered **Intermediate levels** column control to the Sankey chart. With it set, the query groups by `[source, ...intermediate levels, target]` and the transform emits links for each adjacent pair, so a flow spanning three or more dimensions renders as multiple levels of nodes from a single dataset.

This was closed as stale in 2024 rather than fixed, so noting it here for anyone still subscribed. Backward compatible: `intermediate_levels` is a new optional form-data key, so existing saved two-column charts are unchanged and no migration is required.

Related: #3059, discussion #38713.
