### ISSUE TITLE
Add Gradient Color Schema for World Map Charts

### ISSUE THREAD

**Issue by stefanocascavilla** [apache/superset#20899]
Superset currently offers some schema colors for the world map charts. The problem is that the color schema is not based on a single main color but on multiple (usually two for world map charts).
We'd like to have color schemas for world map charts based on a single color in order to be able to fill different countries with different gradients of the same main color (ex. green).

This is a visual example:
![image](https://user-images.githubusercontent.com/19977405/181481185-9e536e53-5522-488f-974e-7e22c6b1b10e.png)

**Comment by rusackas** [comment]
The maps use a scalar/gradient color palette. You can make one that's light green to dark green if you want all greens. If you're talking about the underlying map color where data is null, you can use a calculated column that replaces nulls with 0 to fill those in. Closing this since it's a (fairly stale) feature request, and we're trying to only have bugs as Issues these days.
