### ISSUE TITLE
In chart view, the saved adhoc_filters in query_b is missing

### ISSUE THREAD

**Issue by meyergin** [apache/superset#20952]
#### How to reproduce the bug
after upgrade to 6b0c3032b28a606fedefa7552823c6e18a95a563 from 5111011de9de614e68c3c373dc9e938a9df3791f,
when I used the query a and b of multi-series chart, the chart on the dashboard view works well
but the same chart on charts view miss the query b's adhoc_filter value (enter by clicking edit chart)
I check the query at dashboard page is correct which contains query b's adhoc_filter value while it's missing at chart page.

### Environment

(please complete the following information):

- browser type and version:  FireFox 103

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by meyergin** [comment]
has found the same Issue  #18998

**Comment by rusackas** [comment]
Looks like everything linked here has been closed/merged, and the issue has been quiet for an awful long time. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
