### ISSUE TITLE
Multi languages report

### ISSUE THREAD

**Issue by Vamshi4772** [apache/superset#20953]
How do we translate report into different languages in Superset for end user

**Comment by rusackas** [comment]
@yousoph @eschutho I don't believe this is currently a feature, is it? In effect, the screenshot-generating user would need to switch languages on demand (perhaps via URL params?). I'm guessing this would be set per-report, and I'm _guessing_ this would be a per-report setting (rather than inferred by the author or recipient's language setting). Maybe this should be an ideas thread rather than an issue?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
