### ISSUE TITLE
Dashboard too long to save

### ISSUE THREAD

**Issue by cisco90** [apache/superset#21012]
I cannot save dashboard with position_json more long than "text" mariadb field

#### How to reproduce the bug

 I create a dashboard that hit the default SUPERSET_DASHBOARD_POSITION_DATA_LIMIT, so i set it to 131070, after that the error change in `Data too long fo column 'json_metadata' at row 1` in superset logs.
without changing json_metadata, only delete a couple of markdown element filled with text, it works
I change manually the type on table superset.dashboard, column json_metadata, from `text` to `mediumtext` and it works perfectly.

I think there is a check on field light based on wrong column type something like a comparison between position_json content length with json_metadata type (text in that case)

### Expected results

Save dashboard that are longer than mariadb text type

### Actual results

I cannot save dashboard that are longer than mariadb text type

### Environment

(please complete the following information):

- browser type and version:
- superset version: `2.0` and also `1.4.2`
- any feature flags active: SUPERSET_DASHBOARD_POSITION_DATA_LIMIT= 131070

**Comment by rusackas** [comment]
Not sure about this, but can you just convert that column to be LONGTEXT? I haven't heard of folks using MariaDB for their metadata database, but it seems like it ought to work. Hopefully you found away around this by now, in any case. Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.
