### ISSUE TITLE
How to change mapbox language?

### ISSUE THREAD

**Issue by Vector-Cross** [apache/superset#21026]
## Screenshot
I already settle up mapbox, and it shows up English.
![image](https://user-images.githubusercontent.com/36829977/183597648-a6f05ad4-3929-48cb-8a32-79c6c8760fb6.png)
And I config a pulish mapbox style with Chinese languege. 
![image](https://user-images.githubusercontent.com/36829977/183598104-970b157f-478b-419f-8639-b151eb4ed508.png)

## Description
And I also config code with public style in such places.
```
/app/superset/static/assets/8135.bb65e8b8f57875c843eb.entry.js
/app/superset/examples/deck.py
/app/superset/examples/long_lat.py
# change  "mapbox_style": "mapbox://styles/mapbox/dark-v9" 
#     to      "mapbox_style": "mapbox://styles/zylj/cl6lt7lqp000m15lqjz6iztoj"
```
But it is in English anyway, what should I do?

**Comment by Vector-Cross** [comment]
mapbox如何配置中文显示，这似乎不难，但我搞不定
![06A6D3C4](https://user-images.githubusercontent.com/36829977/183599532-89c53149-f7f1-4e10-9276-511760979542.png)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  

I know there are other threads on Discussions/Issues about translating various charts, but I'm considering that more of a feature request than a bug. Please feel free to open some PRs or start Github Discussions in this area :)
