### ISSUE TITLE
When upload csv, Table exists could support clear and insert data? 

### ISSUE THREAD

**Issue by zhugw** [apache/superset#21120]
Upload csv, default is text type, and if text type and `mysql+mysqlconnector://`, in chart 2020-04 ==> b'2020-04' 
So I have to modify table 
```
alter table t modify column  `dt` varchar(20) ;
```
but if user upload csv again, and select `Replace (drop and recreate table)`, I have to execute modify sql again.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog, and it's unclear if this is still an issue in current Superset/MySQL. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.... or we can re-open this one with more details (versions, example data, etc)
