### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by DwijadasDey** [apache/superset#21145]
Hi 
I am getting "Failed to load API definition" error in the browser when trying to access API endpoint `http://SERVER_IP:8088/swagger/v1`

Swagger UI is enabled in config.py [`FAB_API_SWAGGER_UI = True`]

![Screenshot from 2022-08-22 13-36-56](https://user-images.githubusercontent.com/12824049/185871432-31cf8864-3f1a-4dba-858c-64a0b9d3bc18.png)

In the browse console, I can see the following two errors:

`GET http://SERVER_IP:8088/api/v1/_openapi 404 (Not Found)
`

and

`DevTools failed to load source map: Could not load content for http://SERVER_IP:8088/static/appbuilder/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

In the superset console:

`WARNING:superset.views.base:404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.`

Shall i have to enable any more feature flags to get it working or need to customise superset using flask app builder ?
If i need to extend superset using FAB for swagger REST API then where can i found the documentation ?

**Environment:**
Python 3.8.1 
Superset 1.4.2

**Comment by rusackas** [comment]
I'n hoping that there may have been a bug back when 1.4 was out that's since been resolved, but I was just able to test this on a completely vanilla build of `master` where the `FAB_API_SWAGGER_UI` feature flag is on by default, accessing http://localhost:8088/swagger/v1. Since I'm unable to reproduce, and this issue hasn't had any traction, I'll mark it as fixed. If you can reproduce this in newer versions, I'm more than happy to re-open it.
