### ISSUE TITLE
The end of the graph has gone off the screen

### ISSUE THREAD

**Issue by boryakbrk** [apache/superset#21162]
Hi! 
I am using two apache superset environments (docker-compose, image apache/superset:latest-dev). In one environment, the graph is displayed correctly, in another environment, the graph is drawn outside the screen. Can this be fixed?

Good.
![image-2022-08-22-17-44-34-029](https://user-images.githubusercontent.com/84574379/186174547-5792b12f-862d-4851-aec5-cad1f88c6262.png)

Bug.
![image-2022-08-22-17-43-46-310](https://user-images.githubusercontent.com/84574379/186174771-9f5f1f50-2144-4b18-ab11-4bcdba1da0c5.png)

**Comment by rusackas** [comment]
@boryakbrk are you able to reproduce this in newer versions of Superset, e.g. 2.0? There were a fair number of PRs since this issue was opened around chart padding. If it's still an issue, I suspect it's something to do with the placement and size of legend items, but there's not a lot to go on here Any additional details/context would be appreciated.

**Comment by rusackas** [comment]
Closing for lack of response from OP.
