### ISSUE TITLE
ParsedQuery to return tables within subselects

### ISSUE THREAD

**Issue by victorarbuesmallada** [apache/superset#21207]
Hi,

We are currently having some issues with SQL Lab permissions related to tables appearing in subselects.

Our Superset users have datasource permissions that are evaluated when the execute a query in SQL Lab.
Sql Lab uses the [ParsedQuery](https://github.com/apache/superset/blob/383313b105b0e82bea0f38cc971630eded5affe0/superset/sql_parse.py#L189) class to extract the tables on that query and then evaluates if a user can actually execute the query based on those permissions.

Since [ParsedQuery](https://github.com/apache/superset/blob/383313b105b0e82bea0f38cc971630eded5affe0/superset/sql_parse.py#L335) excludes subselects from the table parsing mechanism, a user could hide a particular table that he/she doesn't have access to inside a subquery and get away with that.

Our idea is to modify the ParsedQuery logic to actually include, or at least give the option to include, the subqueries when retrieving the tables involved in a query, would that be something sensible?

**Comment by Painyjames** [comment]
related to this [PR](https://github.com/apache/superset/pull/1598)

**Comment by Painyjames** [comment]
Turns out that the subselects are not excluded.
What happens instead is that tables that have the same name as aliases are removed form the list of tables in the SQL query. This causes issues when tables have restricted access, since users can circumvent this access check by just writing their query in a particular manner.
This [PR](https://github.com/apache/superset/pull/21535) sorts that issue.

**Comment by dpgaspar** [comment]
This was fixed by: #21535 and #26476

feel free to reopen if not
