### ISSUE TITLE
Dependabot config for pip and actions is incorrect

### ISSUE THREAD

**Issue by pavera** [apache/superset#21237]
The pip and github-actions ecosystem dependabot configs are incorrect and result in update job failures.

#### How to reproduce the bug

1. Fork the repo
2. Go to Insights->Dependency Graph->Dependabot
3. Click "Enable Dependabot"
4. Once the update jobs have run you can view the logs for each ecosystem to see the errors raised.

### Expected results

Dependabot runs successfully and creates PRs

### Actual results

Dependabot fails with errors and no PRs are created.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I'm opening this issue as I have a PR to fix same.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. It also looks like you might have moved on, since the PR was closed. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  Or we can re-open this one!
