### ISSUE TITLE
Feature request for configurable option to change the time grain for week start and end days.

### ISSUE THREAD

**Issue by chathawee** [apache/superset#21350]
It is possible to add a configuration option about time grain on the Time-series chart. Can we change the start and end day dynamically instead of standard Mon to Sun? Currently, the dropdown looks to have "Week starting Sunday", how about having "Week starting other days" or so?

**Comment by vdugnist** [comment]
@chathawee can you tell me where is this dropdown? (week starting sunday/monday)

**Comment by chathawee** [comment]
Hi @vdugnist thanks for the response. This is the thing that I mean https://github.com/apache/superset/pull/20091

**Comment by sunsikai** [comment]
+1

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and wasn't/isn't really a bug. If people are still encountering concerns around this in current versions (currently 3.x) please re-open this issue, open a new Issue/Discussion with updated context, or raise a PR to address the problem. Thanks!
