### ISSUE TITLE
Table Chart: Unable to select the complete row on On-Click on 1 column cell

### ISSUE THREAD

**Issue by PraveenVutukuri** [apache/superset#21462]
When I enable Cross Filter option and click on 1 Column cell it is selecting that particular cell but not the whole row. Please guide me if there is any option to select the complete row in a table chart. This is a blocker for our request given by Client

#### How to reproduce the bug

1. Go to 'Table Chart page'
2. Enable  'Emit Dashboard Cross Filters'
3. Go to the table and select any column cell
4. You could see only that cell is selected not the complete row in which the selected cell is present

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this because it's been silent for so long, and because it's a feature request rather than a bug report. That said, I'm curious the use case: clicking a cell and emitting a cross filter makes sense, because you're emitting a value as the filter. If you clicked the whole column, wouldn't that effectively select all the values, and thus not provide any filtering at all?
