### ISSUE TITLE
How can I add serviceAccount annotation??

### ISSUE THREAD

**Issue by unolife** [apache/superset#21478]
I got this when I try to add annotation on superset helm values.yaml:
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
superset:
- serviceAccount: Additional property annotations is not allowed

**Comment by jcicchella** [comment]
I found this error google searching "Additional property annotations is not allowed", so I apologize if this might not be the solution to your specific issue, but that specific error string is pretty unique and led me here. Hopefully, this can help someone else out. 

The issue is that there is some schema file that is validating the helm chart. The message is coming from schema validation. I was using the airflow chart, but the same principle should apply. In the chart there is a schema file like `values.schema.json` that's what is blocking the modification. In the airflow example, I was trying to modify the airflow flower helm chart to add pod annotations to allow Prometheus to scrape flower. 

If you look at the chart properties you see 
https://airflow.apache.org/docs/helm-chart/stable/parameters-ref.html#flower

`flower.podAnnotations` `Annotations to add to the Flower pods.`

So you can't override the annotations like you normally would in the values file, you need to override the property config. So it looks like this in my example: 

`airflow:
  flower:
    # Enable flower.
    # If True, and using CeleryExecutor/CeleryKubernetesExecutor, will deploy flower app.
    enabled: True

    podAnnotations: {
      prometheus.io/port: "5555",
      prometheus.io/path: "/metrics",
      sidecar.istio.io/inject: "false"    ,    
      prometheus.io/scrape: "true"

    }`

It is simply just a change in syntax. I'm not familiar with the superset helm chart, but I'm hoping this concept can help you find a solution to your issue or someone else who stumbles upon this from a google search.

**Comment by rusackas** [comment]
Hope the thread comments were helpful, but I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
