### ISSUE TITLE
superset-websocket container not running

### ISSUE THREAD

**Issue by mtv2102** [apache/superset#21509]
When I tried running the docker-compose up command, the superset_websocket container shows exited(1) status.

<img width="1017" alt="Screenshot 2022-09-19 at 10 04 35 AM" src="https://user-images.githubusercontent.com/112002949/190939368-a174a959-53da-44f6-9bff-ce233ec3af3a.png">

Note: There were no index.js file inside the dist folder under superset_websocket.

**Comment by jayhale** [comment]
Encountered this while following the docs here: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/

**Comment by BowenXiao1999** [comment]
Hi I encounter exactly the same issue. Have you work it out?

**Comment by mtv2102** [comment]
setting a jwtSecret in config.ts would resolve this issue

**Comment by aortiz-WW** [comment]
How can I add that secret to the config.ts file?

**Comment by aortiz-WW** [comment]
> setting a jwtSecret in config.ts would resolve this issue

How can I add that secret to the config.ts file?

**Comment by gangtao** [comment]
yes, same issue

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
