### ISSUE TITLE
Too many open files for bigquery 

### ISSUE THREAD

**Issue by AbhishekOnedigital** [apache/superset#21582]
I am using a big query  as a data source for connecting BigQuery I am using credntials.json from GCP. after 4 5 days of using it I am getting this error 
export GOOGLE_APPLICATION_CREDENTIALS=/usr/local/lib/python3.8/site-packages/superset/credential.json

![177517725-8eee5989-8004-45b8-96c5-65e3ac4b8210](https://user-images.githubusercontent.com/17587331/192201120-3a9164a1-9a30-488e-8c0c-198af1d8d89c.png)

any solution for this

**Comment by pritamps** [comment]
We are facing the same issue on our self-hosted superset. Any tips would be appreciated.

@AbhishekOnedigital have you found a solution?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
