### ISSUE TITLE
Superset showing offline or doesn't load

### ISSUE THREAD

**Issue by BalaMahesh** [apache/superset#21808]
Hello guys,

We are recently experiencing this issue while opening/loading the superset application. 

- When there are many number of queries submitted and running on trino(database) superset starts responding slowly and users experience lag or sometimes they won't be able to submit queries. 
- Even when the number of queries are less, it shows offline below the sql lab section. Restarts help sometimes. 

When I tried to inspect the network call, the request goes but the response stays blank . 

Can someone please help me understanding this kind of behaviour and possible reasons ?

<img width="783" alt="Screenshot 2022-10-14 at 9 00 06 AM" src="https://user-images.githubusercontent.com/25053668/195756012-57f280fa-ad81-469b-a195-d6f44019d226.png">

**Comment by RobLucchi** [comment]
@BalaMahesh 
did You solve this, and are you having problems with the UI doesn't respond to the users

**Comment by aikuyun** [comment]
did You solve this?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and as reproducible of a test case as possible. We're no longer supporting Superset 2.x or prior, and it's been a long while since this thread saw any activity, so I'm closing this as stale.
