### ISSUE TITLE
favstar. Favourities not deleted when deleting dashboard or slice

### ISSUE THREAD

**Issue by chernoslav** [apache/superset#21814]
Hi. Found two issues with favourities.

1) I create dashboard,
I mark my dashboard as favourite
I delete the dashboard.
The record in favstar table is not deleted. It should.

2) I have no dashboard with id=99999999
I make GET /superset/favstar/Dashboard/99999999/select/ 
The record in favstar table is created and it should not.

1)    Test
tests.integration_tests.dashboards.api_tests.TestDashboardApi.test_delete_dashboard
    does not check if favstar database is modified and a corresponding record is deleted.

2) Test tests.integration_tests.core_tests.TestCore.test_user_profile does not check negative scenario creating a record with fake id.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  

CC @john-bodley since he was somewhat interested in consolidating this with the Tags feature, which didn't exist when this Issue was opened.
