### ISSUE TITLE
SQL Lab: end_time isn't set in case a query fails

### ISSUE THREAD

**Issue by simonvanderveldt** [apache/superset#21887]
Often (not always) `end_time` isn't being set/written to the `query` table of the Superset database in case a query fails.
![image](https://user-images.githubusercontent.com/204286/196941768-3c9f3c1c-55c8-465e-bd85-66633f9042e4.png)
As can be seen here for all failed queries except the first one the `end_date` isn't set.

We use the query status as well as the runtimes (which we have to derive from by subtracting `start_time` from `end_time`) from the Superset database to monitor how well our Superset + SQL environment is doing. The lack of an `end_time` for failed queries means our reporting is incomplete and thus skewed because the runtimes of problematic/failing queries can't be included.

#### How to reproduce the bug

- Run a query that fails
- Check in the `query` table of the Superset database and see that it doesn't have `end_date` set

Note that I'm not sure why for some queries we do see an `end_time`.

### Expected results
`end_time` is always filled in, irrespective of if the query succeeded or not

### Actual results
`end_time` is pretty much never filled in when a query fails

### Environment
- Superset version: 2.0.0 (we're using the `apache/superset:2.0.0` Docker image)
- In case it matters we're using Spark Thriftserver as our SQL engine
```
FEATURE_FLAGS = {
    "SQLLAB_BACKEND_PERSISTENCE": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "ENABLE_TEMPLATE_REMOVE_FILTERS": True,
}
```

**Comment by rusackas** [comment]
I feel like this might have been solved a while back, actually, but this would need verification. Since we're now on 3.1, on the verge of 4.0, we're not supporting 2.x  or prior versions actively, so I'll close this for now. If anyone is experiencing this issue in current versions, please file a new issue with updated context and repro steps, or let us know to re-open this one. Thank you for understanding :)
