### ISSUE TITLE
Permission dropdown menus keep listing deleted/renamed databases

### ISSUE THREAD

**Issue by giovannipapini-agilelab** [apache/superset#21883]
## Screenshot

![image](https://user-images.githubusercontent.com/98460193/196928932-2ecef692-c5e0-49bb-801d-5f137138ed47.png)

## Description

Superset permission dropdown menus keep listing deleted/renamed databases (with not-anymore-reachable ids).

**Comment by sfirke** [comment]
Try adjusting the cache timeout values in your config file?

**Comment by rusackas** [comment]
Not sure if @giovannipapini-agilelab tried your solution, but I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
