### ISSUE TITLE
export, import dashboard error ..

### ISSUE THREAD

**Issue by ssuyong2** [apache/superset#21898]
## error
An error occurred while importing 대시보드: Error importing dashboard Please re-export your file and try importing again

![image](https://user-images.githubusercontent.com/57586951/196907749-63652afb-8296-4516-a28f-54d63c8d7cb0.png)
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I'm hopeful that he solution above helped. Meanwhile, I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
