### ISSUE TITLE
How to support adding mongosqld as data source

### ISSUE THREAD

**Issue by laik** [apache/superset#21989]
as title,

thanks

**Comment by ziggekatten** [comment]
We are nowadays using an docker Trino-cluster as the layer between Superset and MongoDB. Works very well. Back in the days we used Apache Drill, but it's lacking some features, and development seems to have slowed down.

**Comment by srinify** [comment]
+1 to what Zigge said. We recommend using Trino or Presto for this. We wrote about this a bit here: https://preset.io/blog/2021-6-22-trino-superset/

Supporting Mongo is challenging because of the current architecture of Superset, which uses SQLAlchemy under the hood and there isn't a MongoDB driver for SQLAlchemy: https://preset.io/blog/building-database-connector/
