### ISSUE TITLE
Roles are not listing in dropdown

### ISSUE THREAD

**Issue by kalyan4uonly** [apache/superset#22095]
Hi,

I have enabled the feature "DASHBOARD_RBAC":True in superset_config file but it is not listing any roles in the drop down. can anybody help me on this.

![image](https://user-images.githubusercontent.com/117740933/201281618-e275a5b3-40e2-42c3-9b38-ec46af741125.png)

**Comment by rusackas** [comment]
Not sure if that was ever tried, but I'm closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
