### ISSUE TITLE
possible error in date/time operation

### ISSUE THREAD

**Issue by mkur-ops** [apache/superset#22140]
Whenever I try to run query in SQL Lab, for example

`SELECT * FROM XYZ`

I receive `oracle error: ORA-01805: possible error in date/time operation`

Date and time in superset and db are the same.
#### How to reproduce the bug

Go to SQL Lab and run `SELECT * FROM XYZ`

### Expected results

Get correct results

### Actual results

 `oracle error: ORA-01805: possible error in date/time operation`

### Environment

(please complete the following information):

- superset running on openshift with custom image made from apache/superset:master
- superset version: `superset version` superset 0.0.0-dev
- any feature flags active: ALERTS & REPORTS

**Comment by sfirke** [comment]
Is this an Oracle-specific problem?  Maybe edit the issue title to reflect that if so.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
