### ISSUE TITLE
Microsoft SQL server as metadata is not suppoted 

### ISSUE THREAD

**Issue by AnanthaGopi0** [apache/superset#22215]
but I am getting errors doing the "Superset DB upgrade".

sqlalchemy.exc.ProgrammingError: (pymssql._pymssql.ProgrammingError) (208, b"Invalid object name 'alembic_version'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[SQL: UPDATE alembic_version SET version_num='b4456560d4f3' WHERE alembic_version.version_num = 'bb51420eaf83']

is there any alternate solution for that to configure the mssql server as metadata to the superset.

![image](https://user-images.githubusercontent.com/115773598/203705559-683b8ebc-8f5f-45b3-a935-fc5945fe5bbc.png)

- browser type and version:
- superset version: 1.3.0
- python version: 3.8.8
- node.js version: 
- any feature flags active: THUMBNAILS, ALERT_REPORTS, VERSIONED_EXPORT

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ok ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ok ] I have reproduced the issue with at least the latest released version of superset.
- [[ok](url) ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
No, MSSQL is not supported as a metadata DB.  See this FAQ: https://superset.apache.org/docs/frequently-asked-questions/#what-database-engine-can-i-use-as-a-backend-for-superset

> Superset is tested using Mysql, Postgresql and Sqlite for its backend. It’s recommended you install Superset on one of these database server for production.

> Using a column-store, non-OLTP databases like Vertica, Redshift or Presto as a database backend simply won’t work as these databases are not designed for this type of workload. **Installation on Oracle, Microsoft SQL Server, or other OLTP databases may work but isn’t tested.**

Since this isn't a bug, I believe this issue should be closed.  You could create a Feature Request in the Github Discussions for this functionality but realistically, I don't think any existing contributors are likely to prioritize it.  Your best bet is to use MySQL or Postgres for the backend db.
