### ISSUE TITLE
Users account sees all roles

### ISSUE THREAD

**Issue by SEDAManzana** [apache/superset#22225]
Hi everyone and sorry for my English.
I create a user "test_avmi_user"  and set roles:  test_user and Gamma.

![image](https://user-images.githubusercontent.com/117734616/203948895-adba9266-8ca1-414d-84af-d50d9f813b4f.png)
Gamma role - have default settings to use web SuperSet (all icons to menu)
test_user - this role narrows settings user account to create/select  dashboards on custom dataset/database.

Then I am creating dashboards, I can pick another role (sql_Lab) and see other data.  And this is bad. Because test_avmi_user must see just his data.
I disable on Gamma role settings about check ListRole and RoleModelView, but it´s not release my problem.

![image](https://user-images.githubusercontent.com/117734616/203952740-f11552ff-2565-4e1c-a539-da2b3625aa71.png)

How a can disable vision another role to user, who shouldn`t see them?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent/unvalidated for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
