### ISSUE TITLE
bug(dashboards): Selected tab is reverted after transitioning to Edit mode.

### ISSUE THREAD

**Issue by romagrog** [apache/superset#22391]
[Note this was filed as a SIP, but should be treated as either a bug, or a feature request (and migrated to Github Discussions)

### Motivation
This improvement will reduce the cognitive load on the user and increase the speed of his work with the interface.

### Description of the problem to be solved
When we work in any of the tabs of the current research except the first one and click on the "Edit dashboard" button, the editing mode screen opens. Then, even if we have not made any changes, when you click on the "Undo changes" button, the page is reloaded and the current state of the page is reset, namely, the focus shifts to the first tab. The user has to remember which tab he was on before, which increases the cognitive load.

#### Link to screenshots
https://drive.google.com/drive/folders/1gP1U97Fd18K_8AH1rS2IKqSQcVx2o9Z4?usp=share_link

### Proposed Change
Make it so that when canceling changes, in the case when the user did not make any adjustments, the page does not reload and the cursor remains on the same tab where the user was before clicking the "Edit dashboard" button.

**Comment by rusackas** [comment]
Seems like a reasonable concern that can be addressed. I'm a bit torn as to whether this should be considered a feature request, or filed as a bug. It does seem like the dashboard could/should remember the context of which tab was active when going into Edit mode, so that may be recalled upon cancellation (or saving) of those changes. 

I suppose if you change tabs while in edit mode, we would want to persist that state change on Save. Would we also want to persist it on Discard?

In either case, I don't think this requires a SIP to agree on this change - I'll update this accordingly.

Pinging @lauderbaugh and @kasiazjc for further comments/redirection/ticketing.

**Comment by romagrog** [comment]
I think it is not correct to save any state changes on Discard. Because the user will expect that when clicking the ‘’Discard changes’’ button, all changes will not be saved.

**Comment by geido** [comment]
Hello @romagrog there have been significant changes to the Dashboard and in general toward SAP since this issue was opened. I am closing it for now but feel free to reopen it if you think this is still a problem. Thank you!
