### ISSUE TITLE
allow DML based on role

### ISSUE THREAD

**Issue by vishnu-facilio** [apache/superset#22448]
### Discussed in https://github.com/apache/superset/discussions/22446

<div type='discussions-op-text'>

<sup>Originally posted by **vishnu-facilio** December 17, 2022</sup>
hi, 
I'm Vishnu
We have too many developers in our org. so I need to allow DML based on role.
only leads can have an update insert query permission 
please help me on this 

thanks in advance</div>

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
