### ISSUE TITLE
Embeded dashboard show timegrain filter "No Result' in native filter

### ISSUE THREAD

**Issue by thanhpd56** [apache/superset#22488]
#### How to reproduce the bug

1. Create a dashboard wilt time grain filter
2. Embed that dashboad to another website, using guest token to fetch data
3. Open native filter

### Expected results

See a dropdown of time grain

### Actual results
Time grain filter only shows "No Result"

#### Screenshots
This is dashboard inside Superset site: 
<img width="784" alt="Screen Shot 2022-12-21 at 16 18 46" src="https://user-images.githubusercontent.com/3794898/208869183-2c64a83b-eacb-49d0-acfd-aaab15418ce2.png">
This an embeded dashboad:
<img width="649" alt="Screen Shot 2022-12-21 at 16 20 29" src="https://user-images.githubusercontent.com/3794898/208869409-8adebf4e-553f-466d-bb05-024a0d4cef83.png">

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
There may be a permissions issue, but this also might have been resolved by now since this was a few versions ago. 

Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
