### ISSUE TITLE
allow_dml: true does not work from "superset import_datasources" command

### ISSUE THREAD

**Issue by tooptoop4** [apache/superset#22598]
even if my import_datasourcesfmt.yaml has allow_dml: true in it, in the UI the datasource shows false for allow_dml

i wonder if its because allow_dml is not in this block https://github.com/apache/superset/blob/ebaad10d6ce72fa9d939833720b44880d5139bb9/superset/databases/schemas.py#L677-L690?

version 2.0.1

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
