### ISSUE TITLE
Dashboard RBAC access doesn't conform to documentation (and access permission exposes a possible security risk)

### ISSUE THREAD

**Issue by giovannipapini-agilelab** [apache/superset#22640]
`DASHBOARD_RBAC` does not behave as explained in documentation: it says 'Roles is a list which defines access to the dashboard. Granting a role access to a dashboard will bypass dataset level checks. **If no roles are defined, then the dashboard is available to all roles.**', but instead when I do not assign any role to the dashboard only admin and owners can access to it.

#### How to reproduce the bug

1. Feature flag `DASHBOARD_RBAC` set to `True`
2. Open a published dashboard that has no role assigned as a Alpha-role-assigned user

### Expected results

The dashboard

### Actual results

A permission error

#### Screenshots

![image](https://user-images.githubusercontent.com/98460193/211276806-ac3eb874-f611-4266-9dac-10db9e29e783.png)

### Environment

(please complete the following information):

- browser type and version: both Edge and Firefox
- superset version: both `1.5` and `2.0`
- python version: `python --version 3.9`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

While investigating in the problem I found out that it is possible to access any dashboard with status DRAFT from any user (when dashboard has no RBAC role assigned). 

The problem could probably be here: https://github.com/apache/superset/blob/001100ddf02db7be1ea94a1cac16475d00436b78/superset/security/manager.py#L1994

Indeed, I cannot figure out why the condition should be `or (not dashboard.published and not dashboard.roles)` and not `or (dashboard.published and not dashboard.roles)`.

Is there a case in which a non-admin and non-owner user should view a (not even menu-listed) draft dashboard?

**Comment by giovannipapini-agilelab** [comment]
Just opened a PR to propose a fix: https://github.com/apache/superset/pull/22642

**Comment by drummerwolli** [comment]
possible duplicate of https://github.com/apache/superset/issues/17227 ?

**Comment by Rohit-pawar902** [comment]
@giovannipapini-agilelab Your changes still would not be working I applied your changes but still getting no access on dashboard
on alpha role without RBAC

**Comment by frabenetti** [comment]
> @giovannipapini-agilelab Your changes still would not be working I applied your changes but still getting no access on dashboard on alpha role without RBAC

I am working with Giovanni, actually it seems strange since it works for us. Did you change the status of the dashboard to "published", since RBAC, according to the documentation, applies to published dashboards.

**Comment by sfirke** [comment]
Right now if a dashboard is "draft" status and has no roles, any role can access it, even Public.  But if it's published, then Public cannot access it.  It looks like PR #22642 would switch this.  Would Public role then be able to access a Published dashboard with no role assigned?  Or would it fall back to dataset access?

Falling back to dataset access would be the desirable behavior for me.  Otherwise there's always the risk that someone forgets to assign any role to a dashboard and then it's publicly-accessible by default.  Right now that's the case and it's very sketchy: all Draft-status dashboards with no role assigned are publicly accessible.

**Comment by ivan-price-acted** [comment]
Hi there, 

100% agree with @sfirke , i'm wondering what the use-case is for allowing global access to datasets (through dashboards) that would otherwise not be visible, just because a dashboard is in draft ?

It's certain that our users will occasionally forget to publish dashboards, which leaves us wide open to leaking data, especially because dashboard URLs are so easy to guess !

I feel like I must be missing something somewhere because this seems to be a serious potential security hole for any org using superset for sensitive data, between disparate teams ?

**Comment by giovannipapini-agilelab** [comment]
@nicolas-gaillard it was solved in 2.1

**Comment by nicolas-gaillard** [comment]
Oh awesome, thank you for your quick reply :)

**Comment by giacomochiarella** [comment]
it seems still not working on the latest tag docker image

**Comment by rusackas** [comment]
By most accounts, it sounds like this is closed. Can anyone confirm/deny whether this is still am issue in the currently supported versions (3.x)?

**Comment by ivan-price-acted** [comment]
@rusackas for us this is ok since the 2.1 fix.
