### ISSUE TITLE
@superset-ui/switchboard NPM package has no esm or lib directory

### ISSUE THREAD

**Issue by jbmolle** [apache/superset#22681]
The new package @superset-ui/switchboard 0.18.26-1 published on NPM doesn't work.
It has no esm or lib directory.

If I do npm install @superset-ui/switchboard@0.18.26-0, everything works.

JB

**Comment by S4dhu** [comment]
Similar trouble with new version of @superset-ui/switchboard
Error:
```
ERROR in ./node_modules/@superset-ui/embedded-sdk/lib/index.js 8:19-54
Module not found: Error: Can't resolve '@superset-ui/switchboard' in '/app/node_modules/@superset-ui/embedded-sdk/lib'
```
Reverting to the previous version of @superset/embedded-sdk didn't help.

**Comment by NoorAhmd** [comment]
For those of you who are still having the problem!
I have managed to solve it for now with installing the following package without changing anything.
"@superset-ui/switchboard": "^1.5.0"

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long (we're on Switchboard 2.1 now), and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
