### ISSUE TITLE
CVE-2022-32221 on 2.0.1 docker image

### ISSUE THREAD

**Issue by tooptoop4** [apache/superset#22759]
can curl be removed from the img?

**Comment by sebastianliebscher** [comment]
`curl` is needed for the docker service health check. This CVE [was fixed](https://curl.se/docs/CVE-2022-32221.html) with curl 7.86.0 and the fix [got backported](https://metadata.ftp-master.debian.org/changelogs//main/c/curl/curl_7.74.0-1.3+deb11u7_changelog) to debian bullseye Dec 27 2022.

To fix this (and similar issues in the future), the Superset committers could rebuild and push the docker image from 2.0.1 tag. Another solution would be to release a new 2.0.2 tag based on the 2.0.1 tag which would rebuild the docker images and thus updating curl and other OS packages.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
