### ISSUE TITLE
Dates alignment issues (wrong font)

### ISSUE THREAD

**Issue by squalou** [apache/superset#22783]
## Screenshot

![2023-01-19_11-2superset-2 0 2-misaligned](https://user-images.githubusercontent.com/4623644/213418410-90ed11d7-6c48-40d6-acab-6719f4022f83.png)

![image](https://user-images.githubusercontent.com/4623644/213425893-5829658e-de87-4a7f-a050-182cf975ede5.png)

## Description

I reopen an issue that was supposedly solved : 

https://github.com/apache/superset/issues/14060

As you can see on above screenshot, dates are not aligned. Screenshot is from a fresh 2.0.1 installation.

(red ruler added  for more visibility)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, we don't support Superset 2.x anymore, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) we can re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
