### ISSUE TITLE
embedded-sdk | Can't resolve '@superset-ui/switchboard'

### ISSUE THREAD

**Issue by apurvh** [apache/superset#22800]
Trying to embed the dashboard using Superset Embedded SDK fails in react app.
Throws module not found error - `Module not found: Error: Can't resolve '@superset-ui/switchboard'`

#### How to reproduce the bug

1. Create a react app with - `npx create-react-app test-superset-emebed-app`
2. In the App.js, add - 

```
import { embedDashboard } from "@superset-ui/embedded-sdk";
const token = "";
embedDashboard({
              id: "1f3ebcefc9fa541f3c",  // given by the Superset embedding UI
              supersetDomain: "http://xx",
              mountPoint: document.getElementById("superset-container"), // html element in which iframe render
              fetchGuestToken: () => token,
              dashboardUiConfig: { hideTitle: true }
            });
```

### Expected results

Embedded dashboard

### Actual results

Failed to compile.

```
Module not found: Error: Can't resolve '@superset-ui/switchboard' in '/Users/apurva/Dev/test-react-app/node_modules/@superset-ui/embedded-sdk/lib'
ERROR in ./node_modules/@superset-ui/embedded-sdk/lib/index.js 8:19-54
Module not found: Error: Can't resolve '@superset-ui/switchboard' in '/Users/apurva/Dev/test-react-app/node_modules/@superset-ui/embedded-sdk/lib'

webpack compiled with 1 error
```

### Environment

(please complete the following information):

- browser type and version: chrome (latest)
- superset version: ` "@superset-ui/embedded-sdk": "^0.1.0-alpha.8"`
- python version: ``
- node.js version: `v19.4.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This pertains to Superset Embedded SDK

**Comment by villebro** [comment]
@apurvh please post your `package.json` and `package-lock.json`.

**Comment by jornetsimon** [comment]
Looks like the bundle of `@superset-ui/switchboard@0.18.26-0` is empty.

**Comment by villebro** [comment]
😱 ok let me look into what went wrong there..

**Comment by rusackas** [comment]
This issue is springing up all over the place:

https://github.com/apache/superset/issues/22800
https://github.com/apache/superset/issues/22754
https://github.com/apache/superset/issues/22747
https://github.com/apache/superset/issues/22683
https://github.com/apache/superset/issues/22681

I'd like to close some in favor of a more centralized issue, but they each have their own peculiarities/comments worth noting. In any case, the fix will be a six-birds-with-one-stone bugfix!

**Comment by zhaoyongjie** [comment]
@apurvh the temperary workaround for this issue is that
```bash
$ npm i --save @superset-ui/switchboard@^1.5.0
```

**Comment by topratiksharma** [comment]
Use    ```"@superset-ui/switchboard": "^1.5.0" ```. 
It should resolve the issues.

The latest version of switchboard has been published empty try using the previous version.

```npm install@superset-ui/switchboard@1.5.0  --save```

**Comment by villebro** [comment]
`@superset-ui/switchboard": "^0.18.26-2` should now be available with actual contents. Please try it out.

**Comment by jackgray** [comment]
I think the update just pushed yesterday caused this to happen again. It seems to have broken embedded-sdk. My app stopped compiling with this error when I did not change anything about my superset component. 

`56.09 
56.18    Creating an optimized production build ...
69.61 Failed to compile.
69.61 
69.61 ./node_modules/@superset-ui/embedded-sdk/lib/index.js
69.61 Module not found: Can't resolve '@superset-ui/switchboard'
69.61 
69.61 https://nextjs.org/docs/messages/module-not-found
69.61 
69.61 Import trace for requested module:
69.61 ./components/superset-dashboard.tsx
69.61 
69.63 
69.63 > Build failed because of webpack errors`

I did not need to even know about switchboard previously but now I'm trying to import the last version of switchboard explicitly still to no avail. 

embedded-sdk should probably import these modules explicitly so that updates them don't affect it until they have been tested. 

package.json:

`
"dependencies": {
		"next": "14.2.4",
		"@next/env": "14.2.7",
		"next-themes": "^0.2.1",
		"react": "18.3.1",
		"react-dom": "18.3.1",
		"@superset-ui/switchboard": "2.1.0",
		"@superset-ui/embedded-sdk": "0.1.0-alpha.11",
		"axios": "1.7.4"
	},
`
