### ISSUE TITLE
Set Authorization header

### ISSUE THREAD

**Issue by AyoubTahir** [apache/superset#22817]
const res = await request(app).delete(`/land`).set('Authorization', `Bearer ${token}`);

Authorization header is missing

**Comment by rusackas** [comment]
This seems like very partial context... note that you need to set your request headers to `bearer-token: {your token}` and depending on your application, you'll also need a CSRF token. 

Closing this since it sounds more like a support request than a bug report. Feel free to add more context to what you're trying to build/accomplish in a Q&A Discussion, or on Slack, and we'll do our best to help further!
