### ISSUE TITLE
code: echartInstance?.dispatchAction doesnot work

### ISSUE THREAD

**Issue by wendy2017** [apache/superset#22899]
A bug was found in use

" if all legend is unselected, we keep all selected“ : it doesnot work
It seems that this method(echartInstance?.dispatchAction ) is wrong

**Comment by rusackas** [comment]
I'm having a hard time interpreting this... can you explain a few things, for example:
• What version of Superset are you running
• What chart(s) are you seeing this in?
• What did you do to cause this error?
• What were you expecting to happen, and what DID happen?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
