### ISSUE TITLE
superset runtime error

### ISSUE THREAD

**Issue by sedanursayer** [apache/superset#22922]
We want to run superset with waitress instead of gunicorn on windows like this : waitress-serve --host 127.0.0.1 superset:app
our goal is to run Superset project directly from github project instead of installing it in virtualenv.
but we are getting this error, any idea what to do? 
Error : raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.

**Comment by rusackas** [comment]
This sounds suspiciously like the prior reported issue [here](https://github.com/apache/superset/issues/22918) in terms of running Superset  "directly from GitHub project instead of installing it in virtualenv". I'm a little confused as running it using virualenv (as far as I understand) just makes sure the dependencies are kept in order, whereas skipping those instructions means you're using other system dependencies, and things might go sideways for any number of reasons. Can you explain why you're going that route? Otherwise, I'm hesitant to say that this points out a community bug to resolve, but more of a machine configuration issue. 

Also, hosting on windows is not officially supported, but you can ask around in the `#deploying-superset` channel on Slack, or start a Q&A Discussion here on the repo look for anyone else attempting this.

**Comment by EugeneTorap** [comment]
Hey @rusackas @sedanursayer @zeynepkoyun!
I guess we can easy add the Windows support for superset.
The next two lines will be enough in ´setup.py´:
´´´python
'waitress; sys_platform == "win32"',
'gunicorn; sys_platform != "win32"',
´´´
Feel free to add a PR for this!

**Comment by sedanursayer** [comment]
What exactly should I write in the setup.py file for this to work?

**Comment by sedanursayer** [comment]
> @sedanursayer For `waitress` you should use the next command:
> ```
> waitress-serve --host 127.0.0.1 --call superset:create_app
> ```

What exactly should I write in the setup.py file for this to work?

**Comment by EugeneTorap** [comment]
Can you join in our Slack? http://bit.ly/join-superset-slack
I have the same nickname.
