### ISSUE TITLE
Time-Sync/Time-Mismatch problem in Dashboard-view and chart(clike table view in dashbord) reports

### ISSUE THREAD

**Issue by rohitpawar2811** [apache/superset#22952]
Time-sync Problem on Dashboard view and Chart/table

I am having an chart named ReportFailInSchedule and I noticed that the **date are mismatching on the dashboard-view and Chart or table view of dashboard** 

**Like :** 

- on dashboard I have same no of records but this date 2023-02-01 record 10 time and 2023-02-02 (2x-time)
- And on table/chart view 2023-02-02 (11x-time)   and this is exactly right according to query

So why in the Dashboard-view ,this date-mismatching problem is  coming ? What things are causing this problem?
Any Idea?
@evans 

![Screenshot from 2023-02-02 11-15-25](https://user-images.githubusercontent.com/72196393/216251840-6101d247-0319-46f9-9dcb-4dd8ffd2c0f6.png)

**Working on versions :** 

- image - superset-2.0.0-dev

**Comment by rusackas** [comment]
Sounds like a caching issue... dashboards have a (configurable) caching layer to them, and I _think_ the chart details modal makes a fresh query via the API, so the data will be the latest and greatest (essentially skipping the cache). 

There may be another nuance to this regarding timezone handling (see pending docs PR [here](https://github.com/apache/superset/pull/19056/files)). 

Pinging/assigning @michael-s-molina and @codyml who know this modal particularly well and might be able to spot something else that I'm not, or provide more insight.

Also worth mentioning: The `evans` github user is not me and has nothing to do with this project. Poor guy gets pinged all the time by this community. ;)

**Comment by Rohit-pawar902** [comment]
Thanks for reply
And I would not  bother evans again.  

As you said about caching-layer problem
But Its Not about Caching - Layer Problem because the **data and id** is exactly same just time is diffrent , I checked by appliying force - refreshal on them

Problem might be because of  timezone handling ,

@michael-s-molina 
Can You suggest what extra thing I will have to add/enable in config file other than this for timezone problem handling 

```
# Druid query timezone
# tz.tzutc() : Using utc timezone
# tz.tzlocal() : Using local timezone
# tz.gettz('Asia/Shanghai') : Using the time zone with specific name
# [TimeZone List]
# See: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# other tz can be overridden by providing a local_config
DRUID_TZ = tz.tzutc()
DRUID_ANALYSIS_TYPES = ["cardinality"]

```

**Comment by Rohit-pawar902** [comment]
It is caused because of checked  **isTemporal flag** it will change the date to something else , As of now on Dashboard Page I can see the right date by un-checking the isTemporal flag in Dataset of chart.

Can you tell me Why?
@codyml

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
