### ISSUE TITLE
/api/v1/chart/_info?q=(keys:!(permissions)) HTTP/1.1

### ISSUE THREAD

**Issue by zeynepkoyun** [apache/superset#22959]
Hello,
When I reboot the system with admin user, it gives an "access denied" error in all functions.

**Comment by rusackas** [comment]
by "the system" do you mean restarting the OS? Restarting just the superset python application? Restarting docker in some particular manner?

Additional details on how you're running it (os, build method, version, etc) and what _exact steps_ you're taking, would be extremely helpful. We can't fix it if we can't replicate it.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
