### ISSUE TITLE
Want to export complete dashboard to Google sheet

### ISSUE THREAD

**Issue by architmmmec** [apache/superset#22965]
Can someone explain the way to export complete dashboard to Google sheet

**Comment by rusackas** [comment]
There's no such feature, but if you have a proposal of how/why you would like this to work, or any ideas for its implementation, you could take it up in an Ideas thread on the Discussions tab above. Thanks!

**Comment by architmmmec** [comment]
We have a business case to export data from to google sheet from a superset dashboard @rusackas

**Comment by rusackas** [comment]
@architmmmec fair enough... we just haven't heard any outcry for this as a feature, so it's not on the roadmap. We'd welcome a feature discussion on the Ideas thread or on Slack, and see if it gets any traction. Otherwise, we'd be more than happy to review a PR if you're so inclined. There might be other ways, getting fancy with scripts to export the chart data as CSV, repeatedly. More details about your use case may help in finding/defining a solution that works.
