### ISSUE TITLE
deck.gl maps don't render in e-mail

### ISSUE THREAD

**Issue by JohnDietrich-Pepper** [apache/superset#22994]
After considerable work we were able to get e-mail reports sending correct unfortunately it appears that the firefox headless browser won't render the deck.gl maps even tweeking the settings below

SCREENSHOT_LOCATE_WAIT = 100
SCREENSHOT_LOAD_WAIT = 600
EMAIL_PAGE_RENDER_WAIT = 35
SCREENSHOT_SELENIUM_ANIMATION_WAIT = 10

It appears to us that the issue is a problem with the headless browser rendering webgl vs. any issue the timeouts in superset.  Deck.gl maps are an important feature for us and would like to find a way to get this to work.

**Comment by santosh-sahoo334** [comment]
@sfirke @JohnDietrich-Pepper, I had the same issue with Deck.gl Scatter Plot Charts, looks like the Firefox driver has some limitation (I was getting an empty screenshot). When I switched back to Chrome browser, its working.

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x), especially if the Playwright feature flag is enabled (it was build tof this purpose). If this is still an issue, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
