### ISSUE TITLE
Console error when navigating in the integrated superset mode

### ISSUE THREAD

**Issue by aehanno** [apache/superset#22993]
Console error are visible in the console when we show dashboard

#### How to reproduce the bug

1. Go to your embedded dashboard
2. See error in ocnsole

### Expected results

No error

### Actual results

error on the call of tab_id api

#### Screenshots
![Capture d’écran du 2023-02-03 16-36-33](https://user-images.githubusercontent.com/104373599/216715683-cce44191-52d9-47fa-b8a4-6787fb0eb93a.png)

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
