### ISSUE TITLE
docker container app doesn't work in dev mode

### ISSUE THREAD

**Issue by alekssakovsky** [apache/superset#23017]
db doesn't work. it expects 10 postgress.
after changing on 10 postgres in dev mode ui shows this:
![image](https://user-images.githubusercontent.com/39739131/217203601-37d988e1-f8da-4a11-9a81-788228b84fa6.png)

**Comment by wrschneider** [comment]
Does it work in non-dev mode?  I saw the same screen as a symptom that webpack wasn't running.
What are the errors from the superset_node container?

**Comment by alekssakovsky** [comment]
@wrschneider I won it, I changed path on 25 string on
BASE_DIR = '/usr/local/lib/python2.7/dist-packages/superset/'
in setup.py file, but i have some problems on UI.

**Comment by sparkwj** [comment]
me too

**Comment by rusackas** [comment]
Indeed, I would try the non-dev docker-compose file, as the dev one pulls from master and you might get random problems. This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.
