### ISSUE TITLE
Connecting to Databases For Presto Issue

### ISSUE THREAD

**Issue by christianxiaobai** [apache/superset#23019]
I tried to add a Presto data source for a superset，But when I told you that URL links are configured in a superset, I got an unexpected error

![image](https://user-images.githubusercontent.com/70797042/217219598-8e4bda69-364f-4754-b436-021aefb6029c.png)

Here is my configuration information
presto://admin:@host:port/hive/default

I also tried the following configuration，But they all failed
presto://host:port/hive/default

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
