### ISSUE TITLE
URL filter parameters not working in Superset dashboard

### ISSUE THREAD

**Issue by architmmmec** [apache/superset#23026]
<img width="1728" alt="Screenshot 2023-02-08 at 12 14 41 PM" src="https://user-images.githubusercontent.com/37949198/217454839-3271f1d4-f2ed-46a4-8147-30f6951420cd.png">

I am trying to apply filter on dashboard through URL but it is not applying.
I am trying this URL: http://localhost:8088/superset/dashboard/11/?native_filters=2ZiAeuy7Wtt2tuWdSlKg4JuXBURiXvD4dSkpXDJVqGYBm242sIXSEN0wIlkkA8H5:(__cache:(label:'Alpha',validateStatus:!f,validateMessage:!f,value:!('Alpha')), extraFormData:(filters:!((col:'fulfilment_type',op:IN,val:!('Alpha')))), filterState:(label:'Alpha',validateStatus:!f,validateMessage:!f,value:!('Alpha')),id:2ZiAeuy7Wtt2tuWdSlKg4JuXBURiXvD4dSkpXDJVqGYBm242sIXSEN0wIlkkA8H5,ownState:()))

And this is the value of feature flag in superset_config.py --
FEATURE_FLAGS = {"DASHBOARD_FILTERS_EXPERIMENTAL": True, "DASHBOARD_NATIVE_FILTERS_SET": True, "DASHBOARD_NATIVE_FILTERS": True, "DASHBOARD_CROSS_FILTERS": True, "ENABLE_TEMPLATE_PROCESSING": True}

Can someone help here

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
