### ISSUE TITLE
Guest token rls clause is not working

### ISSUE THREAD

**Issue by santoshmallah** [apache/superset#23056]
I have added keycloak as authentication for a superset.
whenever the user login to the superset he will going to redirect to the keycloak login screen and after successful authentication 
user will land on to superset welcome page.

I have embedded superset dashboard with the help of **Superset Embedded SDK** in Angular application 
My angular application is also integrated with keycloak for authentication and authorization.
Now I am trying to give RLS(Row level Security) using guest token

here is the request
```typescript

{
    "user": {
        "username": "santosh",
        "first_name": "santosh",
        "last_name": "santosh"
    },
    "resources": [
        {
            "type": "dashboard",
            "id": "25579002-9e70-401e-aca2-ef8ceb220fd0"
        }
    ],
    "rls": [
        {
            "clause": "customer_id=12"
        }
    ]
    }
````

with this JSON request I want to achieve a dynamic filter so that dashboard data is filtered for **customer_id 12**
```json 
      "rls": [
        {
            "clause": "customer_id=12"
        }
```
After so many tries I failed to implement this

this way of implementation is mention in [Superset Embedded SDK](https://www.npmjs.com/package/@superset-ui/embedded-sdk?activeTab=readme)

can any one suggest me what I am missing in that.

thanks in advance.

**Comment by e-geist** [comment]
Are you logged in with the same browser as admin into the Superset instance? Log out or try another browser, where you do not have an active session with more rights than the guest role user.

The embedding uses the other active session instead of the guest token and therefore doesn't use the provided RLS-clause.

**Comment by santoshmallah** [comment]
Ok, now it's working but after clicking on force to refresh or page reload RLS clause filter is not applying why ??
how can I resolve this problem?

Thanks in advance.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for about a year, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Comment by sagautam5** [comment]
@santoshmallah Have you found any way to fix dynamic rls workflow ? can you explain your workflow for dynamically filtering data based on currently logged in user in an application that embeds superset dashboards
