### ISSUE TITLE
Map chart color scheme in Edit screen does not match color scheme in regular views

### ISSUE THREAD

**Issue by anavasp** [apache/superset#23070]
I'm trying to build a dashboard with 4 map charts: 2 world maps and 2 country maps (more specifically, 2 Spain charts). The 2 world map charts are displayed as expected, but the other 2 country map charts are displayed with a seemingly random color scheme.

When accessing the country map charts from the Charts menu, the charts are displayed properly and all settings can be changed as expected, including color scheme. However, one we go into the dashboard, the charts go "rogue" and if I try to edit them from the dashboard (by clicking on the 3 dots on the chart and clicking on "Edit chart"), the Edit screen won't let me change the color scheme (I can't edit the color scheme of the world map charts like this either, but they're already working as expected).

I've seen a similar bug (I think) to this one in [https://github.com/apache/superset/issues/20376](https://github.com/apache/superset/issues/20376) but I have not seen any hints as to how to solve my issue.

#### How to reproduce the bug

1. Create a Country map chart (only Spain has been tested) and choose a color scheme.
2. Add the chart to a dashboard
3. View country map chart on the dashboard.

### Expected results

The country map chart should be displayed with the expected color scheme.

### Actual results

The country map chart is displayed with a random color scheme.

#### Screenshots
Dashboard screenshot. The 2 world map charts are displayed as expected but the country maps are not.
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/107985293/218510462-dee40865-22d3-475d-9aa0-d4b429ea914f.png)

Editing the country map chart from the Charts menu. Note the "Lineas Color Scheme" setting, which is available for editing. The preview displays the chart as expected.
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/107985293/218511150-2dfab428-cb40-4c08-9d4f-2b138f51a823.png)

The same chart, but the edit screen has been invoked from the chart menu in the dashboard. The last setting is greyed out.
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/107985293/218511306-6da8bd95-ff96-49e0-b6c7-c4f09b691df3.png)

For comparison, here's one of the world map charts edit screen, once again accessed from the chart menu in the dashboard. The color scheme option is also greyed out, but this does not seem to affect the chart in the dashboard.
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/107985293/218511890-fc4a3989-a402-4551-80bd-37a5e131eb86.png)

### Environment

(please complete the following information):

- browser type and version: tested on latest releases of Chrome and Edge on Windows 10 and MacOS.
- superset version: `Superset 0.0.0-dev` (docker-compose, apache/superset:latest-dev)
- python version: `3.8.13`
- node.js version: 
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This looks like it's because you've got a color scheme added to your Dashboard, which overrides chart color schemes (with certain exceptions) and tries to make sure each series remains consistent from chart to chart. This is why if you go to a chart FROM the dashboard, it grays out the color palette control, which tells you it's inheriting from the dashboard. If you go there directly from the Charts tab, this won't be the case. If you remove the color scheme from the Dashboard, the chards will display like they do in the Explore (chart builder) UI.

That said, it looks like there may potentially be _two_ bugs here:
1) Your dashboard has a categorical color scheme (thus the "random" colors) that is being applied to the map. This should not be happening as the map uses a _linear_ color scheme.
2) The country map, in Explore is locking out the control for color scheme, when in fact a categorical scheme shouldn't be applied here in the first place.

**Comment by anavasp** [comment]
Thank you for your reply. We did somehow set a color scheme in the dashboard properties; we did try to remove it some time ago but for whatever reason we couldn't, but we just tested with the latest Docker image and we indeed could remove the dashboard color scheme.

The charts are now displaying properly. Thank you very much for your suggestion. Our issue is now solved, but I'm unsure of whether I should close the issue or not, because it seems from your comment that what we experienced is not the expected behaviour.

**Comment by rusackas** [comment]
I think we'll go ahead and close this one, since the acute/reported issue is solved. We can consider the other (relatively minor) issues separately if they cause _actual_ trouble (nobody has noted/reported this as a problem to my knowledge). I'm more inclined to wait until anyone encounters it as a problem, since filing nuisance issues will just clutter github and be unlikely to get addressed. That said, I'll CC @geido here as a subject matter expert, who might have different opinions on whether they're worth tracking here and now.
