### ISSUE TITLE
SERIES LIMIT not restricted to TIME RANGE

### ISSUE THREAD

**Issue by rodriguez-facundo** [apache/superset#23082]
#### How to reproduce the bug

1. Start a new chart
2. Select a time range
3. Select a metric like `COUNT(*)`
4. Select a dimension like `country`
5. Select a SERIES LIMIT of 5
6. Order by `COUNT(*)`
7. Run the query

### Expected results

The top 5 countries should be the top 5 countries within the selected time range

### Actual results

The top 5 countries are the top 5 countries of the whole dataset. So, if within the time range, there were other countries that stored more events, they will not be displayed.

#### Screenshots

NA

### Environment

(please complete the following information):

- browser type and version: Chrome 110
- superset version: 2.0.1
- python version: 3.8.12
- node.js version: NA
- any feature flags active: no

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stack traces and included them here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by e271828-** [comment]
CC @villebro

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel ree to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
