### ISSUE TITLE
How to make LDAP packages install at build time

### ISSUE THREAD

**Issue by 88fingerslukee** [apache/superset#23090]
I'm trying to make python-ldap install at build time for the docker container. I can't figure out where to put the `apt-get `and `pip ` commands in the Dockerfile to get it to work.

Can somebody please help?

**Comment by Rohit-pawar902** [comment]
I did a thing to automate it 

For apt-get to run I have created a bash file custom_install.sh  and write those statements
```
apt-get update
apt-get install python-dev libldap2-dev libsasl2-dev libssl-dev -y
pip install python-ldap
pip install pymssql
```
And I have linked above bash file inside **docker-bootstarp.sh** so that on restart all unavailable dependency will download automatically

set -eo pipefail

```
REQUIREMENTS_LOCAL="/app/docker/requirements-local.txt"
#Edits to rohit
**bash /app/docker/custom_install.sh**
# If Cypress run – overwrite the password for admin and export env variables
```
I think with this you are good to go 

And the reason for not using recommended  requirement-dev is that it is only used for download of pip statements

**Comment by 88fingerslukee** [comment]
Oh my god that's it! Thank you!!!
