### ISSUE TITLE
A chart table with "SHOW TOTALS" enabled corrupts csv in report scheduled email

### ISSUE THREAD

**Issue by rolandwang19** [apache/superset#23128]
Emails kept sending w/ an attachment, but would break when trying to open. First it would try to recover, then error saying it's not possible because it's corrupt. When disabled, email sends and CSV can be opened.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please add context to this issue so we can re-open it, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
