### ISSUE TITLE
Domain sharding results in failed requests with "Missing Authorization Header"

### ISSUE THREAD

**Issue by andnig** [apache/superset#23295]
I've enabled domain sharding as follows

```python
    ENABLE_CORS = True
    CORS_OPTIONS = {
      'supports_credentials': True,
      'allow_headers': '*',
      'resources': '*',
      'origins': ['https://dashboards.mydomain.com','https://dashboards1.mydomain.com','https://dashboards2.mydomain.com','https://dashboards3.mydomain.com']
    }
    SUPERSET_WEBSERVER_DOMAINS=['dashboards.mydomain.com','dashboards1.mydomain.com','dashboards2.mydomain.com','dashboards3.mydomain.com']
```

All 4 webserver domains are set via DNS A record to the same IP address.

When navigating to a dashboard, I can see in the Edge devtools, that the ``/api/v1/chart/data`` requests are sent to all webserver domains. However, they all fail with "401" (unauthenticated). I can also see, that some of the requests have a response set to ``{"msg":"Missing Authorization Header"}``.

Is my configuration faulty? Or is there something else I can do?

### Expected results

Domain sharding uses the 4 configured webserver domains for requesting data - and uses the session cookie of original domain for authentication.

### Actual results

The authentication of the non-original webserver domains does not work and the requests are not authenticated.

### Environment

- browser type and version: MS Edge 110.0.1587.63
- superset version: `2.0.1` (as part of the apache/superset:master docker container, as of 2023-03-01)
- python version: part of the apache/superset:master docker container, as of 2023-03-01
- node.js version: part of the apache/superset:master docker container, as of 2023-03-01
- any feature flags active:

```python
        "ALLOW_DASHBOARD_DOMAIN_SHARDING": True,
        "ENABLE_TEMPLATE_PROCESSING": True,
        "ESTIMATE_QUERY_COST": True,
        "HORIZONTAL_FILTER_BAR": True,
        "DASHBOARD_RBAC": True,
        "ALERT_REPORTS": True,
        "DASHBOARD_CACHE": True,
        "DRILL_TO_DETAIL": True,
        "ENABLE_JAVASCRIPT_CONTROLS": True,
        "ALLOW_ADHOC_SUBQUERY": True,
        "DASHBOARD_CROSS_FILTERS": True
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by nickrbclark** [comment]
I've had this exact same issue, and no amount of config tweaking helped.
The only way I could get my dashboards to work was by separately navigating to every domain in a separate tab and logging in before loading the dashboard. Then I would be authed on every domain the dashboard tries to use.
I would love to use sharding because my dashboards are slowed down by my filter fields loading, but I can't sacrifice my security or expect users to log in multiple times...
https://github.com/apache/superset/pull/5039

**Comment by nickrbclark** [comment]
I tried various other CORS kwarg options noted here:
https://flask-cors.corydolphin.com/en/latest/api.html
but with no luck.

The below configuration allows sharding to work, but only if I separately log in to both domains.
Otherwise, it results in a 401 (UNAUTHORIZED) on the Post to the second subdomain.


```
# CORS Options
ENABLE_CORS = True #False
CORS_OPTIONS: Dict[Any, Any] = {
    #"resources": r'/*',
    #"methods": ["GET", "HEAD", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"],
    #"supports_credentials": True,
    #"send_wildcard": False,

    "supports_credentials": True,
    "allow_headers": "*", #["Access-Control-Allow-Origin", "Content-Type", "Authorization"],
    "expose_headers": "*",
    "origins": ["https://sub-01.mydomain.com","https://sub-02.mydomain.com"]
}


SUPERSET_WEBSERVER_DOMAINS = {"sub-01.mydomain.com","sub-02.mydomain.com"}
```

**Comment by ved-kashyap-samsung** [comment]
@graceguo-supercat @michellethomas @john-bodley @timifasubaa @kristw @williaster Please check this issue of domain sharding.

**Comment by ved-kashyap-samsung** [comment]
I found the solution to this issue . Actually session in superset is managed using cookies. So, session cookie must be sent automatically in any API request through request headers. Also, cookies are automatically sent to subdomains on a domain(TLD). So, following are two solutions. You can choose either.

1. set `SESSION_COOKIE_DOMAIN` = 'mydomain.com' 
This should take care of setting cookie in every request header and hence authorization will be done.
2. Other solution is  to create domain shards which should be subdomains of main domain like below.
SUPERSET_WEBSERVER_DOMAINS=['dashboards.mydomain.com','1.dashboards.mydomain.com','2.dashboards.mydomain.com','3.dashboards.mydomain.com']

Note: Please delete all the session cookies for your superset top level domain and subdomains intially so that previously session cookies don't change the desired behaviour.

**Comment by nickrbclark** [comment]
Adding my root domain to SESSION_COOKIE_DOMAIN in config worked!
This should definitely be documented with the Domain Sharding instructions.

**Comment by rusackas** [comment]
Made some small editorial comments on https://github.com/apache/superset/pull/24481, so hopefully we'll get that thing merged soon and close this out :D

**Comment by LeoDiep** [comment]
> I found the solution to this issue . Actually session in superset is managed using cookies. So, session cookie must be sent automatically in any API request through request headers. Also, cookies are automatically sent to subdomains on a domain(TLD). So, following are two solutions. You can choose either.
> 
> 1. set `SESSION_COOKIE_DOMAIN = 'mydomain.com' ` in superset_config.py
>    This should take care of setting cookie in every request header and hence authorization will be done.
> 2. Other solution is  to create domain shards which should be subdomains of main domain like below.
>    `SUPERSET_WEBSERVER_DOMAINS=['dashboards.mydomain.com','1.dashboards.mydomain.com','2.dashboards.mydomain.com','3.dashboards.mydomain.com']`
> 
> Note: Please delete all the session cookies for your superset top level domain and subdomains intially so that previously session cookies don't change the desired behaviour.

Hi, thank you for your suggestion. It helps me logging to subdomains just fine. But I got another problem, please help me take a look at this. Thank you a lot for your support
![image](https://github.com/apache/superset/assets/99783557/d692c998-4e66-433b-9938-512e3706feb2)

The config I set up in superset_config.py as:
ENABLE_CORS = True
CORS_OPTIONS = {
      'supports_credentials': True,
      'allow_headers': '*',
      "expose_headers": "*",
      'resources': '*',
      'origins': ['dashboard.***.com']
    }
SUPERSET_WEBSERVER_DOMAINS = ['dashboard.***.com','1.dashboard.***.com','2.dashboard***.com','3.dashboard.***.com']
SESSION_COOKIE_DOMAIN = 'dashboard.***.com'

**Comment by lelelethu** [comment]
I setting ENABLE_CORS =  false.
But i call http://192.168.56.5:8088/api/v1/security/guest_token from http://localhost:3000 causes error: 
Access to fetch at 'http://192.168.56.5:8088/api/v1/security/guest_token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

How to fix it? Any ideas please?
