### ISSUE TITLE
For charts that request more than one query, schedule report send as csv not working properly.

### ISSUE THREAD

**Issue by nkdanta1** [apache/superset#23309]
For charts that request more than one query, the schedule report send as csv not working.
It is attaching a file with .csv extension in the email that is corrupted.

#### How to reproduce the bug
1. Create a chart with multiple queries.
2. Schedule a report.

### Expected results

It should attach a zip file containing all related csv files. 

### Actual results

It is attaching a file with .csv extension in the email that is corrupted.

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!

**Comment by wuqicyber** [comment]
Version 4.0.2 also has this problem

**Comment by wuqicyber** [comment]
Version 4.0.2 also has this problem
