### ISSUE TITLE
Drill to Details charts

### ISSUE THREAD

**Issue by nandanalluri** [apache/superset#23335]
Hello All, I am new to Superset, I am looking for feature similar to Drill to Details.

 I have list of Group Names and other group metadata in base chart and when I click on Group Name, I want to see another dashboard/chart with two tabs, first tab will contain the Group Members and Second Tab will contain Group activity. How can i achieve this ? Any documentation on how to build this would be helpful. 

Thanks in Advance.

**Comment by rusackas** [comment]
There's a feature on the roadmap called Jump to Dashboard that sounds a bit like this. Effectively you'd click a part of a chart in Dashboard A, and that part (say a pie chart wedge) would apply a filter as it takes you to Dashboard B with the filter applied. This is still early in development, and we'll be talking about this at a Meetup this Tuesday if you'd like to learn more and see designs and potentially a demo.

Closing this since it's more feature request than bug report, but we appreciate validation of the idea! Feel free to open an Ideas thread on Github Discussions if you want to get more into the design/planning of things.
