### ISSUE TITLE
Feature Request: Modify CSV export for Tables and Pivot Tables to more closely resembled rendered data in these charts

### ISSUE THREAD

**Issue by rwibowo** [apache/superset#23374]
### Discussed in https://github.com/apache/superset/discussions/19705

<div type='discussions-op-text'>

<sup>Originally posted by **SakshiTharkude** April 13, 2022</sup>
Charts
Creating charts, selecting a particular visualization type , building queries
For eg: If the selected visualization type is PIVOT TABLE ,
And I want to export the pivot table to a CSV file
It gets exported to a normal csv file
It should to exported in the format of PIVOT
If I create a pivot table of 3*3 matrix the csv file should  give the same output</div>

**Comment by rusackas** [comment]
You can export pivoted data as CSV from the chart builder. It's plausible to add this export capability to the dashboard as well, which is already requested in other Issues. Since this is more feature request than bug, and fairly stale of a thread at that, I'll go ahead and close this. PRs and proposals welcome if you want to improve on this!
