### ISSUE TITLE
the chart quantity is limited when  it apply to multiple different dashboards 

### ISSUE THREAD

**Issue by yunchanggou** [apache/superset#23390]
when I attemp to apply a chart to multiple different dashboards  ,I find it is limited,it can only use five different dashboards

#### How to reproduce the bug

1. creat a chart
2.  apply the chart to  different  dashboard more than 5 times 
3. then edit the sixth dashboard,then you will find you cannot find it in  right search bar (''fliter your charts'') 

### Environment
superset 2.0; mysql 5.8 ;python 3

### Additional context
should I Modify some configuration to solve the problem?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. We also no longer support 2.x or prior. If people are still encountering this in current versions (currently 3.x) please open a new Issue or a PR to address the problem.  

Feel free to hit us up on [Superset Slack](http://bit.ly/join-superset-slack) with usability questions.
