### ISSUE TITLE
Is there a way to beautify login page?

### ISSUE THREAD

**Issue by k6407399** [apache/superset#23466]
## Screenshot
<img width="956" alt="Capture" src="https://user-images.githubusercontent.com/97595567/227122313-2fe50098-ba66-492b-b35f-cebdaddb8291.PNG">

## Description
Dear Team,

Is it possible to beautify the login page? with nice background and with some transitions/animations.

We are currently using Apache Superset for 2 different versions for 2 different Projects.

For a Project we are using Superset Version : 0.38.1
For the other Project we are using Superset Version : 2.0.1

Which Version is feasible for beautifying the Superset Login Page. 

## Design input
Want to have a nice look and feel as soon as we launch the Supersets Login Page.

**Comment by EugeneTorap** [comment]
Hi @k6407399! I like this idea!
@michael-s-molina @kgabryje @justinpark Is it possible to move login page to ReactJS?

**Comment by nytai** [comment]
While the login page could be converted to react, it would require breaking from FAB and having to reimplement all the different auth flavors FAB supports. You can override the html templates via the `BLUEPRINTS` config

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
