### ISSUE TITLE
Roles are not exporting when Dashboard is exported in zip

### ISSUE THREAD

**Issue by padmaachuth** [apache/superset#23539]
Trying to export and import dashboard in zip with roles attached to it but roles are not exported.
The DASHBOARD_RBAC feature is enabled.

1. Exporting dashboard 
       # curl -kX 'GET' --globoff "https://********.com/api/v1/dashboard/export/?q=[{*****dashboard_id****}]" -H 'accept: application/zip' -H "Authorization: Bearer ****token******" --output dashboard.zip

2. Imported 
         # curl -kX 'POST' "https://**********.com/api/v1/dashboard/import/" -H 'accept: application/json' -H "Authorization: Bearer 
 ***token**" -H 'Content-Type: multipart/form-data' -F "formData=@*****dashboard.zip****;type=application/x-zip-compressed" -F 'overwrite=true' -F 'passwords={ "databases/********":"*********", "databases/********" : "*********" }'
 
4.  After dashboard import  checked roles are not attached to dashboard.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

CC @betodealmeida @yousoph for good measure, as I'm not sure if this is even a supported feature. This might be more of a feature request than a bug report if I'm not mistaken :D
