### ISSUE TITLE
DASHBOARD_EDIT_CHART_IN_NEW_TAB feature flag is not working

### ISSUE THREAD

**Issue by iercan** [apache/superset#23648]
DASHBOARD_EDIT_CHART_IN_NEW_TAB flag is not working on new version. I set it to True after upgrading latest version which is 2.1.0 but charts still opening in same page.

#### How to reproduce the bug

1. set DASHBOARD_EDIT_CHART_IN_NEW_TAB to true
2. Go to a dahsboard and try to edit a chart

### Expected results
Chart edit page should be opening new page.

### Actual results
Chart edit page opening same page

### Environment

(please complete the following information):

- browser type and version: Chrome 112.0.5615.49
- superset version: 2.1.0 installed with docker

**Comment by santosh-sahoo334** [comment]
Hi, I am Facing the same issue in release tag - v2.1.0. Its opening the charts in same window. Any workaround to fix this ? Thanks!

**Comment by iercan** [comment]
Seems like no one care this bug :/

**Comment by rusackas** [comment]
> Seems like no one care this bug :/

You can command-click the "Edit Chart" link to open it in a new tab, just like any other link on the web. 

The "should it open in a new tab or not" debate goes back to when it was a JS function being fired rather than a normal link. 

This flag is slated to be removed in 3.0 via [this PR](https://github.com/apache/superset/pull/23785). 

I think this issue can stay open... I'm not sure why the flag isn't working in 2.1.0, and anyone is welcome to open a PR to fix it, which can be pulled into 2.1.1 or any subsequent 2.x.x patch versions.

**Comment by rusackas** [comment]
`DASHBOARD_EDIT_CHART_IN_NEW_TAB` no longer exists in supported versions of Superset. Closing. Thanks!
