### ISSUE TITLE
Team encountering Error connecting to Superset site via VPN

### ISSUE THREAD

**Issue by ozy203** [apache/superset#23713]
Have multiple users including myself not being able to connect to Supset. 

When trying to access it we are presenting with this error 

![image](https://user-images.githubusercontent.com/131021932/232565262-b56c5bfc-6f12-454d-9538-87dc9c7e666a.png)

Would love to get in contact with someone internally as the person managing our superset is no longer with the company. 

Thank you,

**Comment by sebastianliebscher** [comment]
I'm afraid this error has nothing to do with Superset itself. Maybe the system behind Superset is failing. Relevant logs from superset would help to identify the issue.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
