### ISSUE TITLE
Editing roles/permissions is painfully/unusable slow

### ISSUE THREAD

**Issue by sjmillius** [apache/superset#23722]
We are running superset on GCP using the helm chart and the latest image.
Recently, modifying roles is extremely / unusably slow.
Additionally, superset-init-db takes ages to complete when it was very quick previously.

I suspect this is because there are permissions on a per schema basis. We have quite a few databases added to our instance, and some likely slow to get schema information. Was behavior around this changed recently?
Is it possible to exclude databases from that?

### Environment

helm chart with the apache/superset latest image.

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sjmillius** [comment]
Or is the magnitude of schemas a problem? There are likely >30k schemas.

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
