### ISSUE TITLE
Disable created by filters for certain roles

### ISSUE THREAD

**Issue by avtishin** [apache/superset#23743]
## Description

Hello, I'd like to modify this header panel with filters in the following way:

Either: 
1. Restrict certain roles to use this filter (such as a user with Gamma role (or similar role) are not able to filter the dashboard created by other users) -- a user should not see the name of other users in filters: OWNER. CREATED BY etc.
or
2. Replace "user name" to "user id" when a user uses these filters.

If I forked superset and can modify my version, is it possible to implement this change? 

Thanks in advance.

## Screenshot
<img width="1439" alt="Screenshot 2023-04-19 at 23 28 51" src="https://user-images.githubusercontent.com/14963755/233180036-7bd0cc2e-cd15-4aab-8991-805311407aa6.png">

**Comment by dennishwuh** [comment]
Yup, I also want to hide these filters.
Looking for help

**Comment by rusackas** [comment]
This is not (to my knowledge) currently supported by Superset, but we'd be open to a PR adding configuration options to this effect if you're interested in making a contribution to the project. Meanwhile, closing this Issue since it's a feature request rather than a bug. We can also convert this to a GitHub discussion if you'd like, and continue the conversation there.
