### ISSUE TITLE
Editing the dashboard, dragging the chart to scroll up and down is not sensitive

### ISSUE THREAD

**Issue by sushauai** [apache/superset#23767]
### Screenshots

https://user-images.githubusercontent.com/15380093/233816064-56e2a5d3-ebd7-43ce-b66a-065fce9562e1.mov

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
