### ISSUE TITLE
Is superset support fast realtime data & api datasource

### ISSUE THREAD

**Issue by j491424570** [apache/superset#23792]
I have to question about superset. any advice will be appreciated

Q1: How cound superset display fast realtime data. some of my datas are generate in milliseconds. is superset possible to refresh milliseconds?

Q2: I have a lot of data comeing from others system which only have api and mqtt to access data. There database is forbidden to access. can superset get data from api & mqtt?

Thank you

**Comment by marrocksd** [comment]
Short answer: No.

To build a realtime solution, you will have to think about many aspects rather than just the visualization tool:
1. Usually we don't show 1 million data points in a chart, it hardly gives any insights. So how you want to aggregate data before visualization.
2. I think that you expect something like a realtime "flowing" line chart. Unfortunately, I don't think the default Superset visuals will give you that experience (which you can find when you update eChart data directly). Even if you find ways to refresh your data every 0.5s, the chart will be glitchy every time it refreshes.
3. Superset is mainly a visualization tool, you can write some custom connectors to your APIs but that's not a very common practice. It's just a part of an Analytics Solution where you have to think about Ingestion, Data Warehouse, Modeling and **Visualization**

So, please consider more carefully what you want, what you need, and the cost the implement those.

**Comment by j491424570** [comment]
> Short answer: No.
> 
> To build a realtime solution, you will have to think about many aspects rather than just the visualization tool:
> 
> 1. Usually we don't show 1 million data points in a chart, it hardly gives any insights. So how you want to aggregate data before visualization.
> 2. I think that you expect something like a realtime "flowing" line chart. Unfortunately, I don't think the default Superset visuals will give you that experience (which you can find when you update eChart data directly). Even if you find ways to refresh your data every 0.5s, the chart will be glitchy every time it refreshes.
> 3. Superset is mainly a visualization tool, you can write some custom connectors to your APIs but that's not a very common practice. It's just a part of an Analytics Solution where you have to think about Ingestion, Data Warehouse, Modeling and **Visualization**
> 
> So, please consider more carefully what you want, what you need, and the cost the implement those.

Thanks very much for your replay

Actually We want some visualization tools which can build Dashboard early.

We used to use grafana and grafana's simplejson datasource which works fine. Recently we are planing to use superset which we think is far more advanced than grafana.

The limitation is that the data is coming from other system which can only access by API. There database is not available to access.

The biggest problem is how to access other system's data by API rather than database

Is superset suitbale for my demands? Is this a common practice? If it is suitable is there any example or api datasource document?

**Comment by sebastianliebscher** [comment]
One could simply dump the API data to a database and then connect that database to Superset. I hope this answers your question?
