### ISSUE TITLE
Add Nepal to Countries Map

### ISSUE THREAD

**Issue by 1yuv** [apache/superset#23876]
It looks like Nepal is not currently supported in countries Map.

**Comment by yrimal** [comment]
I can work on it if there's no other work going on for this.

**Comment by yrimal** [comment]
Current output of geojson library used by superset is very old and I've filed an issue to update Nepal's map on that repo. nvkelso/natural-earth-vector/issues/852

**Comment by rusackas** [comment]
It's much easier to add new maps now if you use the Jupyter notebook. That said, this isn't a bug, really, and PRs are still welcome! Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
