### ISSUE TITLE
Compatible with CockroachDB function `TO_DATE`

### ISSUE THREAD

**Issue by intech** [apache/superset#23889]
In file `/superset/db_engine_specs/cockroachdb.py` need to add the override method:

https://github.com/apache/superset/blob/fd3030fc14dab1c89d198f74c8745b4c22282c9a/superset/db_engine_specs/postgres.py#L332-L333

And change to the `TO_CHAR` function:

```java
return f"TO_CHAR('{dttm.date().isoformat()}', 'YYYY-MM-DD')" 
```

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
