### ISSUE TITLE
Cannot format non-temporal x-axis values when using GENERIC_CHART_AXES

### ISSUE THREAD

**Issue by p-b--** [apache/superset#23912]
### Discussed in https://github.com/apache/superset/discussions/23782

<div type='discussions-op-text'>

<sup>Originally posted by **p-b--** April 22, 2023</sup>
Superset version: 2.0.0

I have enabled GENERIC_CHART_AXES in my superset_config and it is working well, I can use a custom x-axis value in my chart. However, I'd like to be able to format the value as a percentage (as opposed to a decimal). It appears the formatter is ignored in the when using a custom x-axis by default, is there a workaround for this? I believe there was a fix in 2.0.1 to make the time formatter work, but I didn't see anything for arbitrary D3 format strings.

Thanks!</div>

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
