### ISSUE TITLE
while adding url param in chart for mssql DB its showing error

### ISSUE THREAD

**Issue by AnanthaGopi0** [apache/superset#23945]
I am using it to create the chart with mssql getting data fine.
when we use the filter with URL param condition it will through some error.

In that same process, MySQL is working fine with the data.

### Expected results
<img width="958" alt="image" src="https://user-images.githubusercontent.com/115773598/236375831-5d8ca741-ff80-4fb1-bd77-1773afdf5b5d.png">

what you expected to happen.

![Uploading image.png…]()

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: 2.0.1
- python version: 3.8.10
- node.js version: 14.7.4
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment]
Can you share more about how you are filtering with URL param condition (Jinja?) and what error message you get?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
