### ISSUE TITLE
Missing URL Param when trying to load default datasets inside plugins

### ISSUE THREAD

**Issue by danielwodkeTecleadVentures** [apache/superset#23948]
I am getting the Error Missung URL Param after installing superset from scratch and starting the dev image using docker-compose up --build. 

#### How to reproduce the bug

1. clone superset
2. cd superset/frontend
3. npm i
4. npm run build
5. cd ..
6. sudo docker-compose up 

### Expected results

I want to simply load the dataset, it does work when i run docker-compose-non-dev.yml

### Actual results

I can not load the dataset, see image below

#### Screenshots

![image](https://user-images.githubusercontent.com/126596406/236436208-bb40cad4-fa6b-46e3-a216-44cf4f3f45fe.png)
![image](https://user-images.githubusercontent.com/126596406/236436323-0f764baf-67c3-41f0-9733-1217aa0640d9.png)

### Environment

(please complete the following information):

- browser type and version: firefox and chrome both same error
- superset version: 2.1.0
- python version: 3.9.12
- node.js version: ⁶.9.1

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x) - I don't suspect it is. If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
