### ISSUE TITLE
怎么开放superset API

### ISSUE THREAD

**Issue by xxy6910** [apache/superset#23954]
我使用admin用户创建一个chart, 然后想让未登录用户直接调用这个chart接口得到chart的返回的数据得到chart的返回的数据

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
