### ISSUE TITLE
CSV Export of Data Number Format not preserved

### ISSUE THREAD

**Issue by steliosph** [apache/superset#23968]
Downloading the data as a CSV will not maintain the format of the values.
Values are defined in Superset as 
![image](https://user-images.githubusercontent.com/3367401/236813590-0d897018-2b04-4797-a633-972fb4a8010c.png)

And displayed correctly in Superset when showing the values
![image](https://user-images.githubusercontent.com/3367401/236813870-ea8a0f44-0229-4125-8070-24aaa35de10c.png)

![image](https://user-images.githubusercontent.com/3367401/236814133-0d3b4214-66c1-4d17-99a4-0ce8e519af8b.png)

But when exporting the data the formatting in not respected and will return the values with no formatting defined

![image](https://user-images.githubusercontent.com/3367401/236813993-86bbf630-e933-4a50-8e66-3b0d9796d95d.png)

![image](https://user-images.githubusercontent.com/3367401/236814101-e6a42a77-d319-40a9-ad89-080dc0d2ccc9.png)

Superset v2.1.0

**Comment by rusackas** [comment]
I believe we have another issue open that's figuring out why this works for some formats and not others. I'm just sweeping through for now, but if we need a link here, I can dig for it. Meanwhile, we'd welcome PRs on this issue, but I'm closing this one as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. Thanks!
