### ISSUE TITLE
Unable to query BigQuery data - queries executed successful at BigQuery but results not returned at Superset

### ISSUE THREAD

**Issue by rathishkumar** [apache/superset#23979]
Unable to query BigQuery data. I could see the executed queries at the BigQuery project history. Even simple SQL statements are not returning results at Superset.

#### How to reproduce the bug

1. Installed latest version of Apache Superset (2.1) & tried with older previous version of Superset and Python (3.8)
3. Installed SQLAlchemy BigQuery connector
4. Created database connection successfully and able to see the datasets and tables
5. Creating Dataset / creating charts / running simple SQL statements at SQL lab produce Gateway TimeOut error.

### Expected results

Result set at sql lab / data returning at the superset for creating charts.

### Actual results

Gateway Timeout Error - queries running forever and then timeout after the timeout threshold.

#### Screenshots

![image](https://user-images.githubusercontent.com/3918929/237002815-a3e616e6-b27d-4b00-bc7c-6c17a155cfbb.png)
![image](https://user-images.githubusercontent.com/3918929/237004551-15b0c959-e969-4eb4-bf26-21b54adc7e90.png)
![image](https://user-images.githubusercontent.com/3918929/237003060-a39593a2-5186-4e15-aaa4-b344a8d6954a.png)

### Environment

- Browser: Tested with Google Chrome, Edge, Safari
- superset version: Superset 2.1.0 / Tested with Superset 2.0
- python version: Python 3.10 / Tested with Python 3.8
- bigquery connector: sqlalchemy-bigquery  1.6.1 / Tested with Pybigquery
- OS version: Ubuntu 22.04.2 LTS
- Hosted on: GCP VM

### Checklist

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

The VM hosted on GCP Compute Engine and verified the access to BigQuery - APIs access is already enabled and able to query data using the same connector (sqlalchemy-bigquery).

```
from sqlalchemy.engine import create_engine
from pprint import pprint

bigquery_uri = f'bigquery://{project}/{table}'

engine = create_engine(
    bigquery_uri,
)

query = f'SELECT * FROM table WHERE DATE(partition) = "2023-05-05" LIMIT 10;'
rows = engine.execute(query).fetchall()

rows = [dict(row) for row in rows]

pprint(rows)
```

Does not look like connectivity issue as I could see the datasets and tables listed for the database and once queries are executed, I could see the same successfully executed queries at the BigQuery.

![image](https://user-images.githubusercontent.com/3918929/237005148-66cd63d5-2e99-475c-9cc0-37bcfffcbea6.png)

Please let me know if you require any additional information. Your assistance would be greatly appreciated. Thank you.

**Comment by rathishkumar** [comment]
Hi @rusackas 

Our team is currently in the process of migrating Tableau & Looker studio reports to Apache Superset. However, we have encountered an issue that has prevented us from moving forward with our proof of concept. We would like to inquire if there is any enterprise support available to assist us in resolving this issue as soon as possible. Thanks!

**Comment by joev-indx** [comment]
I have the same issue. Newly installed on Debian, followed the superset instructions. I can connect to BQ and list the datasets/tables and table schemas, however the Preview or ANY query to BQ just spins and never returns any data. GCP logs show the query successfully runs, however nothing ever comes back to Superset.

**Comment by rusackas** [comment]
@rathishkumar @joev-indx sorry to hear about the difficulties... I've definitely used BQ on off-the-shelf Superset as well as on Preset's version of Superset with no difficulties... are you seeing any timeout errors or anything along those lines?

As for enterprise support / professional services, the Superset community is all volunteer effort, so not so much. Preset may be able to help provide hands-on support, depending on the scale of things, if you want to inquire about that. In the name of transparency/fairness, there may or may not be other companies offering such managed services too, this is just the one I happen to know well since I work there. Feel free to join us on the [Superset Slack](http://bit.ly/join-superset-slack) workspace and inquire with the community further (perhaps in `#debug-together`), or in quire about Preset in `#vendor-preset`.

**Comment by joev-indx** [comment]
@rusackas there are no timeouts happening. Some of our engineers are looking into the issue and if we can correct it we will, however this is out first time in this code base.

**Comment by rathishkumar** [comment]
@rusackas No, I am not seeing anything related to timeout. I am able to run the same queries, using the same sqlalchemy-bigquery library from this VM. I connected with Preset, but they could not assist with this issue. I did join the Slack workspace, yet to get any response there.

**Comment by rathishkumar** [comment]
After a week of trial and error, I discovered that the issue only occurs when running with gunicorn. I was able to resolve the issue by switching to the waitress WSGI. However, I am uncertain as to why running on gunicorn does not return results. If anyone else has observed a similar issue, please feel free to comment here.

**Comment by okayhooni** [comment]
@rathishkumar 

I found the issue is related to `gevent`, as you guess it related to wsgi server.
when I use gthread worker instead of gevent worker type on `gunicorn`, it works well!

**Comment by joev-indx** [comment]
@okayhooni & @rathishkumar thanks you two! setting the worker type to `gthread` completely resolves the issue we we having.

**Comment by rusackas** [comment]
Sorry this issue has been such a difficult one. If I'm interpreting correctly, it sounds like all interested parties have solved their problems? 

It sounds like some more documentation changes might be in order to help prevent others from running into these issues. If anyone is interested in helping spec out those changes, holler! You can leave suggestions on the docs site itself (using the little "send feedback" tab) or by joining us in `#documentation` on [slack](http://bit.ly/join-superset-slack)

**Comment by AlexMSm** [comment]
Hey @joev-indx @okayhooni  , I've found this thread after experiencing similar issues to the OP with my deployment on gcloud run. I noticed you said you changed a worker type to 'gthread' (from 'gevent'?) but I can't find where in the superset repo this change needs to be made. 
I'm running 2.0.0 and have found the gunicorn command in run-server.sh has flag --workclass = ${SERVER_WORKER_CLASS:-gthread} by default. 
I am inexperienced in this area so any help would be much appreciated and apologies if I've missed anything obvious!

**Comment by joev-indx** [comment]
@AlexMSm I cannot speak to using cloud run, we are running in as a gke cluster. When initiating the server something like this should work for a simple case:
```
gunicorn       -w 10       -k gthread       --timeout 180       -b  0.0.0.0:8080       --limit-request-line 0       --limit-request-field_size 0             "superset.app:create_app()" --daemon
```
its the `-k` option where you specify the `gthread` option. I hope this helps.

**Comment by okayhooni** [comment]
@rusackas
I already updated descriptions related to this issue on the official docs.
https://github.com/apache/superset/pull/24564

@joev-indx
thanks for reply to Alex 👍

**Comment by rusackas** [comment]
Ok, if I'm understanding correctly, now that the issue is identified and the docs are updated, we can call this case closed. If anyone feels there's more to do here, we can reopen/revisit as needed.

**Comment by bruno-santos-6** [comment]
> @AlexMSm I cannot speak to using cloud run, we are running it as a gke cluster. When initiating the server something like this should work for a simple case:
> 
> ```
> gunicorn       -w 10       -k gthread       --timeout 180       -b  0.0.0.0:8080       --limit-request-line 0       --limit-request-field_size 0             "superset.app:create_app()" --daemon
> ```
> 
> its the `-k` option where you specify the `gthread` option. I hope this helps.

Hey, sir!
Could you share how you configured your SQLAlchemy connector to pull data from BigQuery? I’m also running Superset on GKE and would appreciate any insights.

Additionally, if I specify Gunicorn parameters like this in my values.yaml instead of the way you proposed, would it work the same way?

GUNICORN_TIMEOUT: 300
# Increasing the Gunicorn worker count can drastically improve performance.
# See: https://docs.gunicorn.org/en/stable/design.html#how-many-workers
SERVER_WORKER_AMOUNT: 12
WORKER_MAX_REQUESTS: 1000
WORKER_MAX_REQUESTS_JITTER: 50
SERVER_WORKER_CLASS: gthread
SERVER_THREADS_AMOUNT: 20
GUNICORN_KEEPALIVE: 120

Thanks in advance!
