### ISSUE TITLE
Users cannot update their datasets Admin can

### ISSUE THREAD

**Issue by lozbrown** [apache/superset#24000]
As an admin i can update and rename datasets but gamma role users get a error on the screen, however n o such error shows up in the pod logs at this time. 

i have added the "can write on dataset" permission to gamma but this had no affect

this must be some missing permission but with not errors in the superset log how can i diagnose this further

#### How to reproduce the bug

go to data > Datasets

click the pen icon next to a dataset yo wish to amend

in the window that opens up click the padlock and then make changes and click save

### Expected results

Users should be able to edit datasets 

### Actual results

user 

#### Screenshots

![MicrosoftTeams-image (2)](https://github.com/apache/superset/assets/9961593/622d472e-9807-4776-af67-c01cca9c3080)

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: 2.0.1 in helm/kubernetes from official source

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
