### ISSUE TITLE
AuthN token giving 200 response with no token value

### ISSUE THREAD

**Issue by architmmmec** [apache/superset#24091]
OAUTH_PROVIDERS = [
    {
        'name': 'authn',
        'token_key': 'access_token',
        'icon': 'fa-address-card',
        'remote_app': {
   
            'client_id':'os.environ["CLIENT_ID"],
            'client_secret': os.environ["CLIENT_SECRET"],
            'request_token_params': {
                'scope': 'user.profile'
            },
            'request_token_url': None,
            'access_token_method': 'POST',
            'base_url': AUTHN_URL,
            'access_token_url': AUTHN_URL + '/oauth/token',
            'authorize_url': AUTHN_URL + '/oauth/authorize'
        }
    }

getting this:
2023-05-17 16:15:35 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): service.authn-prod.fkcloud.in:443
2023-05-17 16:15:35 DEBUG urllib3.connectionpool https://service.authn-prod.fkcloud.in:443 "POST /oauth/token HTTP/1.1" 200 None

When I logged the request body and headers I am able to get the correct value. Following are the versions.

apache-superset==2.1.0
authlib==0.15.5
Flask-OAuthlib==0.9.6
requests-oauthlib==1.3.0

Can someone help here

**Comment by architmmmec** [comment]
@mistercrunch / @kristw  can you help here

**Comment by rusackas** [comment]
Since this isn't a bug, but rather a configuration issue, we'll leave this open for now in hopes that someone can help (which probably won't be the individuals you've tagged), but you might have better luck in the `#customizing-superset` channel on [Superset Slack](http://bit.ly/join-superset-slack). That said, I see you've configured `base_url` where the docs say you should configure `api_base_url` - maybe it's that simple?

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
