### ISSUE TITLE
Cross filtering on a specific value from a column in a table is not working if the name of the column has been overridden

### ISSUE THREAD

**Issue by martin-raymond** [apache/superset#24123]
I have a table with a column 'libelleContenu'. Cross filtering on a value from that column is working on the others charts.
![working without override](https://github.com/apache/superset/assets/10060967/ae2bd4d9-a116-4f99-9679-683070c0344c)

If I override the name of the column on the chart table, cross filtering no longer works on the other charts.
![not working with override](https://github.com/apache/superset/assets/10060967/426a038e-74e7-407a-9b04-56176afa7b33)

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
