### ISSUE TITLE
Unable to accquire access_token after configuring superset to use keycloak as oauth provider

### ISSUE THREAD

**Issue by luongnguyentrong** [apache/superset#24139]
Hi ,
I am new to superset. Currently i'm having an application which is a management information system that uses superset to visualize its data, what i want is when i click a 'create new dashboard' button in my application, it will accquire access_token from /api/v1/security/login and send a post request to /api/v1/dashboard, this flow works fine when my app and superset are not connected together, but now i want to use keycloak as my sso so that users only need to login once, but after doing this i cannot get access_token from superset any more thus cannot create any dashboard from my application, can you please briefly explain or give me step wise instructions on how to solve this.

Thanks & Regards,

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
