### ISSUE TITLE
Chart d3-format currency configuration

### ISSUE THREAD

**Issue by ekuziel** [apache/superset#24274]
I'm use superset container apache/superset where all resources are prepared and I want to change / add another d3-formats for numeric values like currencies Euro / Pound - currently I see only option $,.2f and I'm not able to edit it 

#### How to reproduce the bug

1. Go to 'Charts'
3. Go to 'Customize' section and select in 'CUSTOMIZE COLUMNS' the numeric field and click an arrow
4. popup for changing format will show

### Expected results

to change interactively D3 format 

### Actual results

I can only select from existing list of options

#### Screenshots
![image](https://github.com/apache/superset/assets/24870533/ebbd3adb-7246-41db-85e7-dafb93434294)

### Environment

Containerized solution apache/superset:2.1.0

**Comment by rusackas** [comment]
In D3 formatter syntax, the $ is just a placeholder for the currency symbol. You cannot just drop in another currency symbol for this. Instead you would do it with a D3 "locale" which is different from a formatter. You can set this for your _entire superset instance_ in `config.py` if you're close to `master` (it has not been released in an official Apache version yet). 

Given all that, just know that you're not alone... a lot of people are asking for this, and various folks are trying to find the best way forward with an implementation (cc @yousoph @mistercrunch) 

For now, this all adds up to more of a feature request than a bug. I'll close this since there's [already a discussion open](https://github.com/apache/superset/discussions/18408).

**Comment by yousoph** [comment]
https://github.com/apache/superset/pull/24718 and https://github.com/apache/superset/pull/24517 add support for more currency symbols
