### ISSUE TITLE
Time Annotation Layer for Mixed Chart

### ISSUE THREAD

**Issue by peppoSVII** [apache/superset#24387]
When I try to add an annotation layer to a mixed chart, it doesn't work.
The error message is related to '**P1D**' time grain representation. 

I tried for different database connections (MariaDB and Big Query) and it fails for both.

#### How to reproduce the bug

1. Go to your mixed chart
2. Add a new 'Event' or 'Interval' annotation.

### Expected results

A new annotation layer on the graph.

### Actual results

Error for BQ:
**_400 Unrecognized Name: P1D at [1:8] Location_**

Error for MariaDB:
**_Unknown column 'P1D' in 'field list'_**

#### Screenshots

Error for Maria DB:
<img width="550" alt="image" src="https://github.com/apache/superset/assets/64637149/3b10fa60-f7bb-4fe3-96c2-c4261abfba86">

Error for BQ:
<img width="541" alt="image" src="https://github.com/apache/superset/assets/64637149/d65abe87-94b5-4f88-8154-5f620b59ee7f">

### Environment

- superset version: `2.1`

**Comment by sfirke** [comment]
Seems possibly related to https://github.com/apache/superset/issues/24374

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
