### ISSUE TITLE
Time series annotation only supports legay line chart

### ISSUE THREAD

**Issue by mattitoo** [apache/superset#24385]
When trying to create a time-series annotation on a line chart, the only option in "Annotation Source" is "Line Chart (Legacy)". 

#### How to reproduce the bug

1. Go to Chart Explorer, by creating a line chart (non-legacy)
2. Click on "Annotations & Layers", "Add Annotation"
3. Select "Time-Series" for "ANNOTATION LAYER TYPE" 
4. Open "ANNOTATIONS SOURCE" drop-down

### Expected results

Different chart types are displayed

### Actual results

Only "Line Chart (Legacy)" is shown

#### Screenshots

<img width="491" alt="Bildschirmfoto 2023-06-13 um 13 28 01" src="https://github.com/apache/superset/assets/104143980/dd7f7230-09fb-4f2c-87ed-9fd553837b2d">

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: 2.1.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: 
 FEATURE_FLAGS = {
          "DASHBOARD_NATIVE_FILTERS": True,
          "THUMBNAILS": False,
          "LISTVIEWS_DEFAULT_CARD_VIEW" : False,
          "THUMBNAILS_SQLA_LISTENERS": False,
          "ENABLE_EXPLORE_DRAG_AND_DROP": True,
          "ENABLE_TEMPLATE_PROCESSING": True,
          "DASHBOARD_CROSS_FILTERS": True,
          "GENERIC_CHART_AXES": True,
          "ENABLE_DND_WITH_CLICK_UX": True,
          "UX_BETA": True,
          "ALERT_REPORTS": True,
          "DASHBOARD_RBAC": True,
          "ALLOW_ADHOC_SUBQUERY" : True,
          "HORIZONTAL_FILTER_BAR": True,
      }

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I would close this as stale since we don't support 2.x anymore, but this is also the case in 3.x (and 4.x so far!). This is also not a _bug_ really, but a nead for more feature support in more charts. While I'm trying to close out feature requests in favor of bugs here on Github Issues, I'll leave this open for now, in hopes that you or anyone reading this might be willing to help contribute here if it's a blocker :)

**Comment by rusackas** [comment]
I think it's best we close this out. What you're reporting is still happening, but it's more of a "shortcoming" than a "bug". Honestly this whole Annotations section is in need of a holistic redesign, but I don't think that's on anyone's near-term radar since it's not the most highly-used feature, but is definitely complex from a design/egineering standpoint. Proposals (SIPs) or incremental improvement PRs are more than welcome from anyone interested. Thanks for understanding.
