### ISSUE TITLE
MonetDB database driver missing

### ISSUE THREAD

**Issue by marioproo** [apache/superset#24383]
There is no MonetDB driver in the list of supported databases to install.

Is there a way I could integrate MonetDB inside superset?

**Comment by rusackas** [comment]
Heya. There are instructions [here](https://superset.apache.org/docs/databases/installing-database-drivers/) on how to do so. We'd love to see a PR for that if you're able to, so that everyone here can gain this functionality. Let me know if that's the case (or not) and we can answer further questions here or on [Superset Slack](http://bit.ly/join-superset-slack) if needed. In the meantime, I'm closing this since it's not a "bug" but more of a feature. If you aren't able to open a PR to add this DB, you can also open a new [Ideas thread](https://github.com/apache/superset/discussions/categories/ideas) in our [Github Discussions](https://github.com/apache/superset/discussions) area.
