### ISSUE TITLE
Unable to 10k records from elasticsearch

### ISSUE THREAD

**Issue by rey2107** [apache/superset#24409]
We have installed elasticsearch-dbapi as instructed in the documentation. (https://superset.apache.org/docs/databases/elasticsearch/)
When we query elasticsearch via the SQLLAB in superset we cannot retrieve results beyond 10k records. We have increased the limits to query beyond 10k records. 

#### How to reproduce the bug
**must have elasticsearch with records more than 10k
1. Go to 'sqllab'
2. Click on 'select elasticsearch database'
3. Run the elasticsearch query 

### Expected results
Expected: should return more than 10k records

what you expected to happen.

### Actual results

what actually happens.
It shows only 10k records 

### Environment

(please complete the following information):

- browser type and version: Chrome 112 
- superset version: `superset version` 2.1.0
- python version: `python --version` 3.8.13
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ yes] I have reproduced the issue with at least the latest released version of superset.
- [ yes] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Hopeful that the above comment helped, and you're off to the races.  Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
