### ISSUE TITLE
How can I modify only the chart export row limit

### ISSUE THREAD

**Issue by qinlz-1** [apache/superset#24416]
superset version 2.1.0

Download via chart query

the same issue :https://github.com/apache/superset/issues/9861
i do not know why it close

**Comment by sebastianliebscher** [comment]
This does not seem to be a bug to me. For questions regarding the use of Superset please use the [Discussions](https://github.com/apache/superset/discussions) or join the [Superset Slack](http://bit.ly/join-superset-slack). There you can share more information in order to debug your issues effectively.

**Comment by rusackas** [comment]
Agreed, this is not a bug, but a customization question. You can explore the codebase, or open a discussion recruiting help in either of the fora linked above.
