### ISSUE TITLE
superset does not close db connections 

### ISSUE THREAD

**Issue by kvatsek** [apache/superset#24445]
Superset does not close db connections. Аs a result, connections hang for days and eventually exceed the allowed number

 See error FATAL:  too many connections for role "superset"
 Is it possible to make a superset with close db connections?

version superset 2.1.0
superset running in kubernetes 
db in psql cluster
python3.8

Connections do not close pods of worker and celery-beat

**Comment by kvatsek** [comment]
found out that hung sessions remain after SQL-lab

**Comment by rusackas** [comment]
Not all DBs support query cancellation as such, but we've made improvements for those that do. It sounds like you might need to make some timeout adjustments at your DB layer? Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If you are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
