### ISSUE TITLE
nodeport for loadbalancer?

### ISSUE THREAD

**Issue by danhiris** [apache/superset#24535]
Why does nodeport have to be set for a load balancer? It's been added part of a change 4 months ago and now the deployment fails when using loadbalancer because it needs what it seems to be an unnecessary nodeport setting.

https://github.com/apache/superset/blob/750113441cd0160ed53e918253a7256466028ac0/helm/superset/templates/service-ws.yaml#L41

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
