### ISSUE TITLE
Kusto broken by cryptography incompatibility

### ISSUE THREAD

**Issue by JohnDietrich-Pepper** [apache/superset#24636]
We are using Superset 2.0.1 and installed the sqlalchemy-kusto=1.1.0 version to avoid the issue with 2.0.1 supporting sqlalchemy==1.3.24 while sqlalchemy-kusto=2.0.0 supports sqlalchemy==1.4.36 .  We are avoiding upgrading to 2.1 because of issue #23848 https://github.com/apache/superset/issues/23848

Unfortunately when trying to connect to Kusto we are getting the error below:
ERROR: (cryptography 36.0.2 (/usr/local/lib/python3.8/site-packages), Requirement.parse('cryptography<4,>=0.6'), {'msal'})

**Comment by rusackas** [comment]
We're on cryptography 42.0.4 now. I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
