### ISSUE TITLE
Permission denied while creating a chart by duckdb dataset

### ISSUE THREAD

**Issue by nagarajmmu** [apache/superset#24757]
#### How to reproduce the bug

1. Mount a Azure file share in superset machine.
2. Create a database connection in Superset to duckdb file ,as below
     duckdb:///mount_path/file_Others.duckdb
3. Create dataset by selecting a duckdb database connection.
4. Create a table chart.
5. Error saying "IO Error: coud not read from file '/mnt/mount_path/file_Others.duckdb' Permission denied"
6. Because another system read a same duckdb file from same time

### Expected results

While super chart should get data from a duckdb. while another system reading a same duckdb file

### Actual results

Error occurred as below:
"IO Error: coud not read from file '/mnt/mount_path/file_Others.duckdb' Permission denied"

### Environment

(please complete the following information):

- superset version: v2.1.0
- python version: 3v.8

Please let me know, do I need to do any setting in a superset, to read duckdb dataset, while other system readying same duckdb file.

Thanks in advance.
Nagaraj M M

**Comment by rusackas** [comment]
This is likely fixed by now, and is pretty out of date if not. We've updated drivers a couple of times, and things seem to be working well in general. If people are still encountering this in current versions (3.x) we can reopen this issue, or open a new Issue with updated context. We're also open to PRs, of course.
