### ISSUE TITLE
Pop up help is missing on editing advanced time range 

### ISSUE THREAD

**Issue by alexryndin** [apache/superset#24845]
## Screenshot
![how it should work](https://github.com/apache/superset/assets/8342078/a876abce-a2d8-4408-9254-835c1837419b)
how it should work
![how it works now](https://github.com/apache/superset/assets/8342078/496e88e2-a711-4610-9529-24d0f868bd57)
how it works now

## Description

Starting with superset version 2.1 pop up help is missing when editing or creating new chart.
How to reproduce:
1. Create new chart
2. Select Time Series Line Chart
3. Under "Time" tab -- edit time range
4. Select "Advanced" Range Type
Now you can see that "i" button is missing, which was present in the previous version of superset and showed pop up help and suggestions.

## Design input
Please, bring back pop up help.

**Comment by sfirke** [comment]
Hm, I see the `i` button in 2.1.0 on dashboard native filters with Advanced type.  Do you see it on a dashboard native filter of type Time Range and Advanced input mode?

When I make a new chart, I don't have "Time series line chart" - just "Line Chart".  I wonder if that's because I have GENERIC_CHART_AXES feature flag enabled?

**Comment by rusackas** [comment]
It's there in 3.x. Closing as resolved

![image](https://github.com/apache/superset/assets/812905/cc487b3c-2266-4f91-a981-ac2eee2dec1e)
