### ISSUE TITLE
Add support for sqlalchemy PickleType or handle rendring pickled data

### ISSUE THREAD

**Issue by neerajd12** [apache/superset#24930]
As of now any PickleType  data  stored in postgres as bytea fails decoding.  below line https://github.com/apache/superset/blob/ec9e9a46f2f092ce56d3ed5a8a9a3ea0214db88a/superset/utils/core.py#L538

#### How to reproduce the bug

1. Save any PickleType to postgres
2. query using sql lab

### Expected results

parsed data should be shown on the sql lab

### Actual results

it just shows [bytes]

![Screenshot](https://github.com/apache/superset/assets/1935151/91cc8377-edba-419c-bf86-24c9ee158a54)

### Environment

(please complete the following information):

- browser type and version:  chrome 115.0.5790.171 (Official Build) (64-bit)
- superset version: Superset 0.0.0-dev
- python version: Python 3.9.17
- node.js version: `node -v`
- any feature flags active: No

Simple solution I've tested until the PickleType can be supported: 

```
if isinstance(obj, bytes):
    try:
        return obj.decode("utf-8")
    except Exception:  # pylint: disable=broad-except
        try:
            import pickle
            return pickle.loads(obj)
        except Exception:  # pylint: disable=broad-except
            return "[bytes]"
```
![Screenshot_fixed](https://github.com/apache/superset/assets/1935151/5d442f53-59c1-491a-b740-6e3066e81aa9)

**Comment by do-it-tim** [comment]
Would also appreciate an option like that!

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for almost 5 months, and is a feature request rather than a bug. If your solution above is enough to solve the issue for now, I think a PR is worth opening, even if only to prompt discussion. If this is a feature request, I'm happy to convert this thread to a GitHub Discussion of the Ideas variety - just say the word. If you do believe this constitutes a _bug_, then I'm happy to revisit/reopen as warranted.
