### ISSUE TITLE
Color assignment on pie charts not correct when using one dimension 

### ISSUE THREAD

**Issue by mattitoo** [apache/superset#25022]
When creating a pie chart with one dimension, the color assignment is not as would be expected from the palette.

When using two dimensions, it is correct.

#### How to reproduce the bug

1. Create a pie chart using one dimension
2. Add it to a dashboard (not sure, if this is necessary)
3. Check the colors of the slices

### Expected results

Each slice has the color according to the palette.

### Actual results

The colors of each slice seems to be applied randomly (s. screenshot above)

#### Screenshots
<img width="1808" alt="Bildschirmfoto 2023-08-16 um 12 12 45" src="https://github.com/apache/superset/assets/104143980/d44c412e-241d-496b-b7a7-4c69d7ad0c01">

### Environment

(please complete the following information):

- browser type and version:
- superset version: 2.1
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:
      FEATURE_FLAGS = {
          "DASHBOARD_NATIVE_FILTERS": True,
          "THUMBNAILS": False,
          "LISTVIEWS_DEFAULT_CARD_VIEW" : False,
          "THUMBNAILS_SQLA_LISTENERS": False,
          "ENABLE_EXPLORE_DRAG_AND_DROP": True,
          "ENABLE_TEMPLATE_PROCESSING": True,
          "DASHBOARD_CROSS_FILTERS": True,
          "GENERIC_CHART_AXES": True,
          "ENABLE_DND_WITH_CLICK_UX": True,
          "UX_BETA": True,
          "ALERT_REPORTS": True,
          "DASHBOARD_RBAC": True,
          "ALLOW_ADHOC_SUBQUERY" : True,
          "HORIZONTAL_FILTER_BAR": True,
      }

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
This is likely due to the "color consistency" work that is perpetually cropping up, where in dashboards that have a color palette applied, the dashboard reserves colors from the palette on a per-series basis, so that series values ("labels") all use the same color in the dashboard. E.g If Toyota is green and Mazda is blue, all charts will match that way. 

We're no longer supporting Superset 2.x or prior (which must've been the case when this was reported), and it's been a while since this thread saw any activity, so I'm closing this as stale. I'm hoping this case might have been solved between then and now, but if it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context. Thanks!
