### ISSUE TITLE
[SIP] Add Atgenomix SeqsLab data engine to Superset supported database.

### ISSUE THREAD

**Issue by allen-chang** [apache/superset#25093]
### Motivation

[Atgenomix SeqsLab](https://www.atgenomix.com/seqslab-platform) allows its users to use Superset to on-demand access and visualize their omics databases stored in data lake.

### Proposed Change

Add documentation in the list of supported databases and dependencies.
https://superset.apache.org/docs/databases/installing-database-drivers/

<img width="1437" alt="Screen Shot 2023-08-27 at 9 21 41 AM" src="https://github.com/apache/superset/assets/13267303/cc33835b-54e1-4ae2-b2ae-6d3fc99648f2">

### New or Changed Public Interfaces

[SeqsLab db engine spec](https://github.com/atgenomix/seqslab-connector/blob/main/seqslab/superset/seqslab.py)

### New dependencies

[The SeqsLab Connector for Python based on pyhive](https://pypi.org/project/seqslab-connector/)

### Migration Plan and Compatibility

N/A

### Rejected Alternatives

N/A

**Comment by betodealmeida** [comment]
This is nice! In my opinion we don't need a SIP for this, since [it doesn't affect any public interfaces or major features](https://github.com/apache/superset/issues/5602). And even though it introduces a new dependency, DB engine spec dependencies are optional, so it should be fine. You can go ahead an PR it and add me as a reviewer, I'll be happy to take a look.

A few things of notice:

1. I wrote a tool to test DB engine spec implementations (and SQLAlchemy dialects as well, to make sure they implement everything Superset needs). You can read more about it in https://github.com/apache/superset/pull/24918.
2. You have the option of having the DB engine spec be part of Superset, or you can distribute it in a separate package (see an example [here](https://github.com/DataJunction/dj/blob/3e2b687f376fd36687152d8f5d319b096367f291/datajunction-server/pyproject.toml#L63C1-L64) and [here](https://github.com/DataJunction/dj/blob/3e2b687f376fd36687152d8f5d319b096367f291/datajunction-server/datajunction_server/superset.py#L47)). Distributing it in a separate package means you can release new versions independently of Superset, which allows people to adopt features more quickly. But the downside is that the DB engine spec interface is not public, so it might change between major versions and break existing 3rd party DB engine specs.

**Comment by allen-chang** [comment]
@betodealmeida #25176 please can you review it.

**Comment by eschutho** [comment]
Looks like we can close this issue/SIP in favor of the attached PR, but feel free to comment if you think we need to reopen.
