### ISSUE TITLE
The extraConfigs cannot be written to the correct location

### ISSUE THREAD

**Issue by YaoHuizhou1** [apache/superset#25109]
#### How to reproduce the bug

If I want to integrate third-party oauth2, because it's our own oauth, so I have to rewrite the userinfo method, so I need the extraConfigs to mount this configuration to /app, but it doesn't actually mount to it. Because only the superset-config secret can be mounted to this directory, there is a problem with temolates

### Expected results

extraConfigs can be properly mounted to /app

### Actual results

It was mounted to an invalid directory

**Comment by rusackas** [comment]
Sorry, but I think this issue has been open so long because it's a request for building a custom security manager? Lots of folks are using Oauth as far as I know, so I don't *think* this is a bug with Superset itself. Please clarify if you're still facing this, and maybe we can reopen the issue. Meanwhile, closing this as stale. Note that we only support Superset 3.x or newer as of this comment.
