### ISSUE TITLE
API reference on /swagger/v1/ differs from the one in the documentation

### ISSUE THREAD

**Issue by kaptsanovb** [apache/superset#25167]
When I look at the API refence through /swagger/v1/, there is no SQLlab section, while on the official docs there is. When I try to use /sqllab/excecute, I get this: `{"errors": [{"message": "404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}`

**Comment by rusackas** [comment]
Probably just a version misalignment. The docs should be pretty current, but your deployment may not be. 

I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.

**Comment by rusackas** [comment]
Probably just a version misalignment. The docs should be pretty current, but your deployment may not be. 

I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
