### ISSUE TITLE
Evaluation of the "next" parameter in combination with "OAuth" authentication

### ISSUE THREAD

**Issue by psandtner** [apache/superset#25180]
Dear Superset community!

I have an probable issue about the "next" parameter in context of Apache Superset Version 2.0.0.

We use Superset with a “Custom OAuth2 Configuration” and several “OAUTH_PROVIDERS”. This leads for example to the following dashboard URLs:

```
https://dashboard.example.com/login/ProviderOne?next=https://dashboard.example.com/superset/dashboard/special_dashboard/
https://dashboard.example.com/login/OtherProvider?next=https://dashboard.example.com/superset/dashboard/special_dashboard/
```

In our tests, however, these only work (meaning: lead to the URL specified under "next") if the user is **not** logged in yet. Of course, these links should also work if the user is already logged in.

Is this a known problem or am I missing something here?

(I have already made this question in the "Flask-AppBuilder" community - unfortunately without success so far. Hope I have more luck here).

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x, we can re-open this, or feel free to open a new issue with updated context.
