### ISSUE TITLE
"/v1/dashboard/2/filter_state?tab_id=13"   This API prompt “400 Bad Request: The CSRF tokens do not match.”

### ISSUE THREAD

**Issue by githubid0719** [apache/superset#25201]
![image](https://github.com/apache/superset/assets/68492256/53ac870d-acd2-4ffa-9477-1370d94bb935)

How can I solve the problem that occurs during iframe embedding?
![image](https://github.com/apache/superset/assets/68492256/51598226-2447-4f96-83bf-6034518cf1f5)

**Comment by shubham8456** [comment]
I'm also having the same issue. Though it's not affecting how I'm using the filters on the dashboard.

**Comment by rusackas** [comment]
Is this using the Embedded SDK or some other form of igrame embed? How are you deploying Superset, and what version? This seems like it's more of a configuration issue than a Superset bug, but it's hard to say the state of affairs without the remainder of the Issue template filled out. 

I'll close this as stale since it's been almost 6 months since a comment, but I'm happy to re-open if further details merit it... or if it's a Q&A/config issue that needs tackling, we can take it to Github discussions or [slack](http://bit.ly/join-superset-slack)
