### ISSUE TITLE
Super set is not accessing  the external PGSQL db and It always takes the Flask sqllite instance

### ISSUE THREAD

**Issue by sreekanthtn** [apache/superset#25315]
Super set is not accessing  the external PGSQL db and It always takes the Flask sqllite instance

**Comment by sfirke** [comment]
Hello, this is not a bug report so I am closing it as a GitHub issue.  You may be able to find help through the project's Slack chat (linked from the main GitHub page) or in a GitHub discussion post.  There you should share how you are deploying Superset: from scratch, docker-compose, Kubernetes, etc. so that others can better help you.
