### ISSUE TITLE
I can't get multiple user sessions

### ISSUE THREAD

**Issue by rafaelkorz** [apache/superset#25321]
what you expected to happen.

I need the superset session to identify different users.

### Actual results

If I log in with user A and then log in with user B, user A gets B's session
This code ever return last user logged, I need that it return each session logged.
**user_logged = session.get("_user_id");**

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: `superset version` 2.1.1
- python version: `python --version` 3.10
- node.js version: `node -v`v12.22.9
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
custom_security.py
![image](https://github.com/apache/superset/assets/13335397/72916c07-17e7-4162-af9e-9e7850c6b791)
query_context_factory.py
![image](https://github.com/apache/superset/assets/13335397/5af87043-6f06-4216-b06e-dbdf6b152451)
superset.config.py
![image](https://github.com/apache/superset/assets/13335397/742cd5c1-b71f-401b-bb1f-186f620bae3b)

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. I think this went quiet due to a lack of reproducible steps. If you can walk us through how to get to this error in detail, that'd help.
