### ISSUE TITLE
 list as you type the values in the Explore's filter section

### ISSUE THREAD

**Issue by ZhannaUp** [apache/superset#25371]
It would be great if there's a dropdown list as you type the values in the Explore's filter section. Just like how there's a dropdown for the column and operator part, so that users would have an idea if the value they are inserting exists or not.

Here's an example of what I mean. Below is a screenshot of the dashboard native filter. And the filter section in Explore should have this dropdown feature too.

<p class="aligncenter">
  <img src="https://ltdfoto.ru/images/2023/09/22/SNIMOK-EKRANA-2023-09-22-V-18.27.36.png" width="500">

Please, sharing example

**Comment by rusackas** [comment]
Closing this as stale since it's been silent for so long, and seems more like a feature request rather than a bug. I'll also say that you can turn on the search option in your filter config, that may address your request.

<img width="869" alt="Pasted_Image_3_15_24__11_08 AM" src="https://github.com/apache/superset/assets/812905/8642b44a-6e0c-47cb-b59e-61577d733a2b">

If you see a shortcoming in current versions (currently 3.x) please open a new Ideas discussion or a PR to address the request.
