### ISSUE TITLE
Superset 3.0 , not able to schedule report over mail

### ISSUE THREAD

**Issue by shafad1** [apache/superset#25381]
Reports not able to send over mail once configured scheduling, getting the following error.

![image](https://github.com/apache/superset/assets/107529872/e53b171a-d560-430e-a22b-46afcae9c6d3)

#### How to reproduce the bug

1. Go to  alerts and report 
2. Configure chart or dashboard to be send over mail
3. Check the celery log 

### Expected results

report should be delivered to the configured email

what actually happens.

![image](https://github.com/apache/superset/assets/107529872/66c861cc-a7d5-4a63-9ef2-cbf5e004c4bd)

**Comment by shafad1** [comment]
any update on the above issue , due to multiple issues our customer is planning to remove superset . they lost confidence on superset .

**Comment by shafad1** [comment]
any update please

**Comment by rusackas** [comment]
Not sure if you're still facing this, but you should not be using SQLite in production, and it seems that it's a SQL error. Closing this due to being unsupported, and a config issue rather than a bug, but happy to keep the discussion going if warranted. You can also [slack](http://bit.ly/join-superset-slack) me for additional pointers to channels/resources if needed.
