### ISSUE TITLE
Mixed_chart: show values only for determined metrics 

### ISSUE THREAD

**Issue by GinkoValery** [apache/superset#25412]
## Screenshot
![image](https://github.com/apache/superset/assets/113714043/0e0afcc2-b2bd-4300-8147-02b975091027)

## Description
I added several metrics in Query B at a **Mixed_chart** and turned on showing values. Now I can see the values for both metrics. But I want to show values only for metric "SUM(val)" and to hide values for metric "150".
How can I do it?

**Comment by rusackas** [comment]
I think Sam's right that this is a feature request rather than a bug, and the annotation layer would be a good way to do this. 

I'll close this accordingly, but I think we can re-open it if there's a bug here, or move it to a Discussion if you don't want to copy/paste the content into a fresh thread.

If you have other proposals for different control arrangements that would support these features, and you'd want to open a PR accordingly, we're open to that conversation too!
