### ISSUE TITLE
Geting error during build

### ISSUE THREAD

**Issue by satyaviya** [apache/superset#25442]
get following error when i am trying to build frontend 

![image](https://github.com/apache/superset/assets/138752111/dd1fe9f2-00e7-4566-9c38-9b6b740670f5)

**Comment by rusackas** [comment]
I think at least one of these is resolved... but they're both warnings. While these are gross, they're not really a user-facing _bug_, per se. If you want to investigate and open a PR for either, you're more than welcome to, it would be appreciated. Otherwise, we'll do what we can, but might close this issue as stale before too long if it doesn't get community attention/contribution.
