### ISSUE TITLE
How can i use Javascript to customize dashboards ib Superset?

### ISSUE THREAD

**Issue by Gal-Gadot** [apache/superset#25499]
## Screenshot

[drag & drop image(s) here!]

## Description

Please help me, i want to custom my dashbords in superset using javascript, how can i do it?
I try handlebars? but it doesnt work

**Comment by sfirke** [comment]
Hello - this Github issues tracker is for bug reports.  Since this is a question about usage, I am closing it.  This post is better suited for the project's Slack chat.  The link to that is on the main Superset Github page.  There's even a channel called #customizing-superset where you can ask and browse what others have discussed.
