### ISSUE TITLE
pivot table V2 Color Shading bug

### ISSUE THREAD

**Issue by RaptorRob** [apache/superset#25511]
Conditional formatting in pivot table V2 seems to be shading very granular. Is it possible to have conditional formatting without it showing a different shade? Seems the color is not staying solid but rather fades away as the difference between highest and lowest value that is being picked up by a condition is increasing. You could call it a feature, but if the color becomes so faint, it's not visible anymore, I would rather call it a bug.

#### How to reproduce the bug

1. Create a data source with values to display that are very far away from each other. (positive range)
2. Use the  pivot table V2 chart to display the data. 
3. Use conditional formatting on the values to show everything > 0 as green
4. See like here, that the data is showing only very faint color in relation to the highest value:

### Expected results

See shading never go below 70% occupancy for the lowest shade range.
OR an option to only show solid colors without shading.

### Actual results

shading down to almost no occupancy of the smaller values.

#### Screenshots

![image](https://github.com/apache/superset/assets/33096624/f9f2f9bf-baf9-4e21-8afb-b51895417a5d)

### Environment

(please complete the following information):

- browser type and version: Google-Chrome Version 116.0.5845.180 (Official Build) (64-bit)
- superset version: 2.0.1
- python version: `python --version` no idea
- node.js version: `node -v` no idea
- any feature flags active: no idea

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
I suspect we're not seeing all your data in the screenshot. The scale of the color considers the entire value range... so if you have values of 1, 2, 3, 10000, you'll barely be able to see the color of the lower values, but the 10000 will be full opacity.

Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!
