### ISSUE TITLE
superset query stuck at pending and timer not starting in SQLLAB

### ISSUE THREAD

**Issue by Shisir99** [apache/superset#25529]
superset query stuck at pending and timer not starting in SQLLAB for athena db connection. Please help.
![stop_query](https://github.com/apache/superset/assets/43596686/e54c67f8-162e-42cc-a63a-cc1df9247dc7)

- browser type and version: chrome
- superset version: 2.1.0

**Comment by rusackas** [comment]
I'm thus far unable to reproduce this. I'm not sure if this is still a reproducible issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.
