### ISSUE TITLE
the feature 'Querying across databases' doesn't work

### ISSUE THREAD

**Issue by actuo** [apache/superset#25522]
following [the documentation](https://superset.apache.org/docs/databases/meta-database) to enable meta database and can't find database of type "Superset meta database" in add new database window.  the feature flag (ENABLE_SUPERSET_META_DB )mentioned in documentation can not be found in https://github.com/apache/superset/blob/master/RESOURCES/FEATURE_FLAGS.md.

#### How to reproduce the bug

set the ENABLE_SUPERSET_META_DB feature flag to true
add a new database of type "Superset meta database" with the SQLAlchemy URI "superset://".

### Expected results
the database of type "Superset meta database" shows at available database list in add database windows
what you expected to happen.

### Actual results
No such type of database shows

### Environment
(please complete the following information):

- browser type and version: chrome Version 117.0.5938.132
- superset version: 3.0.0
- python version: 3.9.6
- node.js version: v16.20.2
- any feature flags active:ENABLE_SUPERSET_META_DB= True ,WTF_CSRF_ENABLED = True

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ozbillwang** [comment]
Someone mentioned in Slack that it will be released in version 3.1.0, but we are uncertain about the release date.

https://apache-superset.slack.com/archives/C016B3LG5B4/p1696459438961999

![image](https://github.com/apache/superset/assets/8954908/33cb4b30-6c5c-4644-94f6-28f359b94ba0)

**Comment by PierrickVoulet** [comment]
I confirm I can see the Superset Meta DB type in 3.1.0 version

**Comment by nevotheless** [comment]
I'm using `3.1.0` as well, and tried setting `ENABLE_SUPERSET_META_DB` to `True` inside the `superset_config.py`, saved the secret restarted my deployment, pods getting recreated but i don't see it. 

There's also no mention of that feature on the supported feature flag [documentation page](https://github.com/apache/superset/blob/3.1/RESOURCES/FEATURE_FLAGS.md) and know i don't really know where to set the feature flag instead.

**Comment by rusackas** [comment]
Just opened a PR to add the feature flag to the relevant page:
https://github.com/apache/superset/pull/27071
@betodealmeida feel free to categorize that if you'd like :)

The feature is indeed in 3.1 (see changelog [here](https://github.com/apache/superset/blob/3.1.0/CHANGELOG.md?plain=1#L102)) so that's not it. 

I'm closing this issue because the issue as-reported (not being in 3.0.0) isn't relevant. Questions about its existence in 3.1 have been addressed. Getting into the intricacies of why a particular deployment isn't updating should be filed as a new/separate issue, or taken to the `#deploying-superset` channel on [Superset Slack](http://bit.ly/join-superset-slack)

**Comment by GauravJain98** [comment]
@nevotheless i found this issue and fixed this bug later this might help you 
https://superset.apache.org/docs/installation/running-on-kubernetes/#superset_configpy
