### ISSUE TITLE
How to increase user session data save frequency?

### ISSUE THREAD

**Issue by shauryagoel** [apache/superset#25605]
I have installed superset v2.1.0 using helm chart v0.10.7 on a GKE cluster. I have also enabled SSO only authentication for my Superset deployment and added cookie timeout using `PERMANENT_SESSION_LIFETIME`. Now, whenever I am editing my SQL queries and the cookie expires, then, my query will not be saved. I would have to manually copy the query and then relogin to superset and then paste the query to save it. This deteriorates the user experience. I would like to know if there is a parameter which increases the frequency to save data (like SQL queries) or if there is another approach to solving this issue?

**Comment by shauryagoel** [comment]
@sfirke can you help with this issue?

**Comment by rusackas** [comment]
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale for now. Holler if it needs further attention.
