### ISSUE TITLE
Issue with /api/v1/chart/{pk} endpoint's "query_context" after upgrade to 3.0.0

### ISSUE THREAD

**Issue by rscarborough1996** [apache/superset#25782]
I believe I may have found a bug in the /api/v1/chart/{pk} endpoint on version 3.0.0.
I make use of Supersets api to retrieve chart data for other applications. I start by making a get request to /api/v1/chart/{pk}, obtain the query context, add "time_range" under "queries", and finally post that to /api/v1/chart/data.
This worked until I upgraded to 3.0.0, then the time range would occasionally be ignored.
From what I have found, time range has no effect unless this is under the filters key:
```
{
  "col": "My Time Column",
  "op": "TEMPORAL_RANGE",
  "val": "No filter"
}
```
If the chart was created BEFORE upgrading then the following behavior can be observed:
If the chart does not contain the temporal column, then this filter is included and the time range is respected.
If the chart DOES contain the temporal column, then this filter IS NOT included, and the time range is ignored.

This does not happen on charts created after upgrading, and it can be fixed.
After deleting the temporal column, saving, re-adding it, and saving again, the query context returns the correct filters.

**Comment by rusackas** [comment]
Closing this since it's been silent for nearly half a year, _but..._ I'm curious what version of Superset you were upgrading from. It sounds like a migration might not have taken place somehow. That temporal filter is indeed required, and you can see in the current UI that you can't remove that last temporal filter. We hope to make the UI a little better on this front in the future, but nonetheless... at least it sounds like you have a functional workaround :)
