### ISSUE TITLE
Oauth redirect_uri is having private IP, instead of public DNS

### ISSUE THREAD

**Issue by nagarajmmu** [apache/superset#25813]
Hi All

1. I have deployed superset 2.1.0 in Azure kubernetes, with IP, example 1.2.3.4

2. Configured AKS superset IP 1.2.3.4 in Azure application gateway, to access superset from public, 
3. gateway URL would be https://test.com
4. When I access superset with Azure SSO, it will give me below Redirect_URI in browser.
http://1.2.3.4/oauth-authorized/azure
5. Instead of https://test.com/oauth-authorized/azure
6. My application gateway URL should be carried and used for the redirection URL.

How to solve this issue

### Expected results

Application gateway DNS should be used for redirect_uri

### Actual results

private IP is used to construct redirect_uri

### Environment

- superset version: v2.1.0
- python version: v3.8

Please let me know, how can I make superset to use my application gateway DNS for redirect_uri

Thanks
Nagaraj M M

**Comment by rusackas** [comment]
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, or feel free to open a new issue with updated context. Thanks!
