### ISSUE TITLE
Issue with creating a external table with a table name containing spaces.

### ISSUE THREAD

**Issue by AjayEstuate** [apache/superset#26047]
Dear Team,

I hope this message finds you well. While working with Parquet data, I am currently facing an issue with Spark across multiple versions (Spark 3.4.1, Spark 3.5.0, and Spark 3.3.3).

Some database supports to name, table name with spaces
I attempted to  create an external table using a Parquet file with Spark
I'm not able to create a table with a name containing spaces, and I'm getting a syntax error.
I attempted various formats such as (table name, "table name," and 'table name'), but none were successful.

I would appreciate any help or insights you could give me to help resolve this issue. If additional information or details are needed, please let me know, and I will gladly provide them.

Thank you for your time and assistance.

Best regards,
Ajay Kumar D

**Comment by rusackas** [comment]
@AjayEstuate Can you give us more details of how you're connecting to Spark. Are you using Hive like [this](https://superset.apache.org/docs/databases/spark-sql/)? Closing this because it's gone silent for so long, but if you still have the problem and can provide more details (logs/errors/etc) we might be able to help debug further. Also wondering if this is magically fixed in currently supported versions of Superset (3.1/4.0). Given all of that, we're happy to reopen this if needed.
