### ISSUE TITLE
setting edit list roles trino The data source can only obtain part of the schema.

### ISSUE THREAD

**Issue by A-little-bit-of-data** [apache/superset#26125]
#### How to reproduce the bug

1. Go to 'setting'
2. Click on 'edit list '
3. Scroll down to 'edit record'

![image](https://github.com/apache/superset/assets/31812278/4000d387-9ae7-4ed6-aec4-b52a344cd875)

Connect through the same data source, show schemas from xxxx_test; you can see all schemas
![image](https://github.com/apache/superset/assets/31812278/b6df3178-db93-47c5-8fe1-f21052232c89)

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment]
Closing this because it's stale, which is likely because it's also confusing. The issue template was not filled out, so we don't have a statement of expected/actual behavior. It looks like you're enabling schema access, and then getting a list of schemas. If you're still facing this in Superset 3.1 or newer, let us know, and we can revisit/reopen if there's more context here.
