### ISSUE TITLE
create or send dashboard or report issues.

### ISSUE THREAD

**Issue by 31000023** [apache/superset#26144]
1. When exporting to Excel, the downloaded file name can only be the default date + serial number, can not bring the name of the report;
2. When exporting CSV format, the Chinese header of the report is garbled;
3. Mail push can only choose CSV or TXT format, CSV Chinese is also garbled;
4. Dashboard: can only be downloaded as a jpg image, no other format;
5. Mail push can only receive pictures, and the Chinese inside cannot be displayed normally;
6. Cannot add Logo in dashboard;

**Comment by michael-s-molina** [comment]
Hi @31000023. This ticket is a mixture of issues and feature requests. In order to resolve them, we need more details. Please open GitHub discussions for the feature requests and GitHub issues for the bugs following the [issue template](https://github.com/apache/superset/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml) which contain the expected information needed. Thank you.
