### ISSUE TITLE
'Installing Superset Locally Using Docker Compose' in official doc not work

### ISSUE THREAD

**Issue by shiftonetothree** [apache/superset#26622]
#### How to reproduce the bug

````shell
git clone https://github.com/apache/superset.git
cd superset
docker compose up
````

### Expected results

Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: TLS handshake timeout

### Actual results

what actually happens.

#### Screenshots
![截屏2024-01-15 18 09 04](https://github.com/apache/superset/assets/10464106/67c42405-82c4-42cf-b696-e7cb83e03993)

### Environment

- browser type and version: 
- superset version: 3.0.2
- python version: Python 2.7.18
- node.js version: v14.21.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Mybe change node:16 to node:18 in docker-compose.yml will fix it

**Comment by sfirke** [comment]
Sounds like it's a bad connection to the Docker registry and you're unable to pull an image.  Source: https://stackoverflow.com/questions/52252791/error-get-https-registry-1-docker-io-v2-net-http-tls-handshake-timeout-in

I'm going to close this since it doesn't seem to be a bug report related to Superset's codebase.  If you are looking for help getting started, please ask in the Superset Slack chat or in GitHub Discussions.
