### ISSUE TITLE
FAB translation is ignored

### ISSUE THREAD

**Issue by qleroy** [apache/superset#26738]
### Bug description

All translated strings related to FAB are ignored, e.g. the navbar.

This is due to the absence of the compiled messages.mo files in the Docker image.

The solution is to run
```bash
pybabel compile -d superset/translations
```
and add this possibly to the docker/docker-init.sh script.

### How to reproduce the bug

1.  Set a language different than English.
For example add 
```python
# Setup default language
BABEL_DEFAULT_LOCALE = "fr"
```
to your docker/pythonpath_dev/superset_config_docker.py

2. Run Superset with docker compose

```bash
git checkout 3.1.0
# Edit docker/pythonpath_dev/superset_config_docker.py to change BABEL_DEFAULT_LOCALE
TAG=3.1.0 docker compose -f docker-compose-non-dev.yml up -d
```
3. Observe that the navbar is not translated ! Indeed, there are no messages.mo files.

### Screenshots/recordings

Before running pybabel compile -d superset/translations
<img width="766" alt="before" src="https://github.com/apache/superset/assets/9881262/ee78587c-75e4-489c-b22f-8264f92393ca">

After running pybabel compile -d superset/translations
<img width="905" alt="after" src="https://github.com/apache/superset/assets/9881262/02b608ca-ceed-43c3-aae0-d67f0acd3898">

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ogui11aume** [comment]
I confirm that French i18n does not work out of the box for the top menu (Dashboards | Charts | Datasets | SQL).

I also confirm that following these steps solves the problem of the localization not been taken into account :
1. `pybabel compile -d superset/translations`
2. superset_config.py ( this step alone doesn't make the French translation work out of the box).
```
BABEL_DEFAULT_LOCALE = "fr"

LANGUAGES = {
    "fr": {"flag": "fr", "name": "French"},
} 
```
3. `docker build -t superset31fr .`
4. `docker-compose -f docker-compose-non-dev.yml up`

![Screenshot showing French localization for top menu Tableaux de bord | Graphiques | Jeux de données | SQL ](https://github.com/apache/superset/assets/31072389/455b6179-2741-4579-8d77-51d931e80b45)

A step needs to be added to the Docker build to include `pybabel compile -d superset/translations` .

**Comment by rusackas** [comment]
Yep, this is all a bit of a mess. 
1. We need to keep the `.pot` file up to date (I intend to add CI for this)
2. We need to keep the `.po` files up to date (I intend to add CI for this)
3. Just like `.mo` files are `.gitignore`'d, we should do the same for `.json` files, removing them from the repo
4. I intend to add an `npm` script to generate `.mo` and `.json` fies easily
5. We should also add such generation triggers to other buid processes, as you've suggested
6. Once all of the above is in place, we can skip the `--ignore-obsolete` flag in our translation build scripts, so files stay slim once they're kept current

If we do all that, then hopefully things will stay up to date, stay clean, and people will contribute in all the right ways. Then we can revisit the topic of enhancing/automating the population of translations.

CC @mistercrunch since we were just talking about all this elsewhere.
