### ISSUE TITLE
Unable to create EXTRA_SEQUENTIAL_COLOR_SCHEMES with the selected colors

### ISSUE THREAD

**Issue by igamat** [apache/superset#26742]
### Bug description

When trying to add a custom sequential color scheme and when specifiying less than 10 colors, Superset automatically creates a gradient from the specified colors to fill a list of 10 final colors. The expected behavior here would be the same as what happens with the categorical color schemes where only the specified colors are the ones added to the color scheme. This bug prevents some of the charts to be correctly colored, such as the Country map.
The result obtained is a color scheme with 10 colors (as shown in the image) instead of the 2 or 4 colors that were initially added as described in the **_How to_**:
![image](https://github.com/apache/superset/assets/138484309/0f95a3cd-13ef-4a73-961c-4bb85d26c490)

### How to reproduce the bug

1. Clone the Superset repo
2. Update the config.py file to add these sequential color schemes:
```
EXTRA_SEQUENTIAL_COLOR_SCHEMES =  [
    {
        "id": 'custom sequential',
        "description": '',
        "isDiverging": True,
        "label": 'Custom sequential',
        "isDefault": True,
        "colors": ['#FF0000', '#0000FF']
    },
    {
        "id": 'custom sequential 2',
        "description": '',
        "isDiverging": True,
        "label": 'Custom 2 sequential',
        "isDefault": True,
        "colors": ['#FF0000', '#0000FF', '#00FF00', '#000000']
    }]
```
3. Build the Superset docker image
4. Check the available color schemes (i.e. from the Country map) and see that the added ones contain more gradient colors than  specified in the code

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by igamat** [comment]
@villebro @geido @rusackas do you have any update on this ?

**Comment by rusackas** [comment]
Ahh, it's actually not a bug! Sequential schemes are "gradients" essentially. You want to be adding/editing a categorical color scheme, which should be under `EXTRA_CATEGORICAL_COLOR_SCHEMES` rather than `EXTRA_SEQUENTIAL_COLOR_SCHEMES`. Here's a blog about how it all works: https://preset.io/blog/customizing-chart-colors-with-superset-and-preset/

**Comment by igamat** [comment]
Appreciate your answer @rusackas, but the issue here is to add let's say about 3-4 colors (following the principle behind the Four Color Theorem) for coloring the Country Map, and this type of chart only accepts Sequential color schemes. And with the current behavior of the EXTRA_SEQUENTIAL_COLOR_SCHEMES this is not possible as it fills out the gradients of the selected colors as a list of up to ten colors. Is there any way to overcome this behavior ? Thanks

**Comment by rusackas** [comment]
I think you've landed in a weird corner case... 

The Country Map plugin is _designed_ to be a choropleth, with the metric determining shading. That's why the control is titled "linear color scheme". Categorical color schemes are not showing up in this menu for that reason. If you add a `EXTRA_SEQUENTIAL_COLOR_SCHEMES` to get it to show up in the menu, it will treat them as such. 

So... the way to fix this for your use case would be to enhance the control panel for the Country Map (and/or World Map). I think the idea would be to:
* add a switch (radio buttons) for Categorical/Sequential coloring (maybe it could be called "Choropleth / Discrete" or something like that
* Have the value of that form input switch which type of color palette you can select/apply
* Dynamically disable/enable the Metric control for the map when in Choropleth mode, since if it's no longer relevant.

I am curious the use case... I haven't heard of any outcry for this. 

On another note, there's what I consider a bug that you _might_ consider a feature (CC @geido for this part). If you add your map to a dashboard, you can go to Dashboard properties, and select a Categorical color palette for the dashboard. This overrides the sequential palette and makes your map categorical. In most cases, this _breaks_ the map for those who want choropleth maps, but in your case it may be exactly what you want. 

_However_ I don't _think_ the map is coded with logic to actually _adhere_ to the four color theorem, so that might require enhancements to the map itself to make it smarter. Additionally, I think this points at an enhancement that should be made to the Dashboard Properties, wherein we would allow dashboard authors to select a Categorical AND/OR Sequential palette, and the charts should be smart enough to know which one they use. 

So... yeah... there's kind of a lot to unfurl here. Let me know if you want to contribute to any part of that, since it's not high up on the priority list for maintainers I speak to regularly.

**Comment by feldti** [comment]
"I haven't heard of any outcry for this" - that is really surprising me. I installed Superset 4.0.2 today and I wanted to visualize - as an example how Superset could be used - the result of the last US presidental election based on state results and was surprised to see, that it seems for me, that with CountryMap this could not be solved with Superset. For this example one only needs two colors (red and blue)
