### ISSUE TITLE
Issue with the apache/superset:dockerize

### ISSUE THREAD

**Issue by rnpaiva** [apache/superset#26788]
### Bug description

Kubernetes can't pull the image apache/superset:dockerize . I tested in my local and it's not possible as well . 

### How to reproduce the bug

docker pull apache/superset:dockerize

### Screenshots/recordings

![Screenshot from 2024-01-24 14-53-34](https://github.com/apache/superset/assets/97540715/1bb73962-dae3-4a6f-9e9a-35acef941aca)
![Screenshot from 2024-01-24 14-50-15](https://github.com/apache/superset/assets/97540715/5166956c-5a37-42a5-a749-2068db8ed31e)
![Screenshot from 2024-01-24 15-05-47](https://github.com/apache/superset/assets/97540715/400ed15e-f6aa-45fe-8329-c343abc1c3b8)

### Superset version

3.0.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by kamilrotter** [comment]
Hey @mistercrunch , we can't pull image using tag 'latest', is that the same issue? 
![image](https://github.com/apache/superset/assets/11577785/d5d33d00-9d14-4a08-9eb5-e40df2b0cfe1)

**Comment by mistercrunch** [comment]
Yes should be the same, we had conflicting tags before that just happened to make the `amd` builds get the proper base docker tags because they were running sequentially with amd last. Now that we parallelize the build, and because arm is emulated and slower, it tends to take over the tags. Now I'm adding suffixes to all arm builds so that tags won't conflict.

**Comment by jun0tpyrc** [comment]
or do docker multi-arch build to make things work implicitly...
most other images in chart are amd64 only

**Comment by jun0tpyrc** [comment]
or may  do docker multi-arch build to make things work implicitly...
most other images in chart are amd64 only

**Comment by kevin-delisle-peakpower** [comment]
> or may do docker multi-arch build to make things work implicitly... most other images in chart are amd64 only

This is the right way of dealing with this. Modifying your build to assemble a multi-arch image means no one has to worry about pulling alternate tags to get the build that's right for them, and it avoids adding complexity to the tagging structure.

**Comment by rnpaiva** [comment]
it's happening again

**Comment by rnpaiva** [comment]
do you have the dockerfile please ? I'll compile and push in my ECR

**Comment by kevin-delisle-peakpower** [comment]
@rnpaiva As a workaround, I pinned my dependencies to a specific release instead of using the `dockerize` image.
If you browse Docker Hub, there's a bunch of tags that look like `apache/superset:<commit-hash>-dockerize-linux-amd64-<base-image-version>`: https://hub.docker.com/r/apache/superset/tags?page=1&name=docker

(ex. `e6f9ef159d113f9cf698791e5f965855e7be0169-dockerize-linux-amd64-3.9-slim-bookworm`)

**Comment by edu-sistec** [comment]
Hello, [kevin-delisle-peakpower](https://github.com/kevin-delisle-peakpower)
I have problems booting in docker, I think it's also due to the AMR64 architecture.

As you say there are these options but I have tried some and I get errors.

I don't understand if the error is the image that is wrong, or the missing file 'config.json' if I should create it, but there is no information about where this file 'config.json' should be located , nor that it has to be introduced.

Have you been able to run some of these images? Which ones exactly? Did you have to do anything special?

Thanks
![1](https://github.com/apache/superset/assets/97883571/cb2c7303-7852-4610-b89c-9d2b98f6a8b9)

**Comment by kevin-delisle-peakpower** [comment]
I used the `apache/superset:b0c8f620d6517b400a9676c01393cda8a57b0d64-dockerize-linux-amd64-3.9-slim-bookworm` image, in particular.
I only used it for the `initImage` portion of the Helm chart when I installed it, since that was what I was running into problems with. We're still using a tagged release for the "main" container instance of the installation.

I'm not versed in the use of Superset's docker-compose install, but if there's a section that's meant to run the postgres initialization, that's probably where you'd want to use this image.

**Comment by mistercrunch** [comment]
Ok i merged that PR, eventually should get a `apache/superset:latest` to point to as we push the next release

**Comment by edu-sistec** [comment]
Hello [kevin-delisle-peakpower](https://github.com/kevin-delisle-peakpower)

Hello,

I am now seeing that you are booting the amd64 image.
I used your comments to try to boot the arm64 image, because I'm on an arm64 architecture.
I get these errors, I attach an image
Am I doing something wrong in docker-compose?

Thank you so much
![1](https://github.com/apache/superset/assets/97883571/1ca8fcaf-0a7e-4cca-8212-e0adf70ec80b)

**Comment by mistercrunch** [comment]
no bash!?

**Comment by mistercrunch** [comment]
I don't really use docker here on my local setup and it looks like it's busted for my new mac (linux/arm64/v8), can't really help. I really like docker conceptually but in practice it's a different story.

**Comment by jun0tpyrc** [comment]
for those who using helm install and want a quick workaround with min changes  , that place in helm values to temp modify before there is a tag on default init image that does  multi-arch

```
 initImage:
   repository: apache/superset
-  tag: dockerize
+  tag: ea6cbcef3e980e42d3a19b8fc5928f973fd7be4a-dockerize-linux-amd64-3.9-slim-bookworm # NOTE: https://github.com/apache/superset/issues/26788
   pullPolicy: IfNotPresent
```

**Comment by edu-sistec** [comment]
Hello [jun0tpyrc](https://github.com/jun0tpyrc),

I tried to do what you say (I attach image 1) but still it want to take the standard Superset image.
I have also put in the docker-compse file the image I would like to use (I attach image 2), and it keeps saying that it cannot run the 'bach'.
Is there something I'm not doing right?

thank you so much,
Edu

![1](https://github.com/apache/superset/assets/97883571/596d6ef9-14a5-43b0-80be-8e160bf6bf20)
![2](https://github.com/apache/superset/assets/97883571/f0be3749-7b0a-4f93-b8d9-a163b6639b80)

**Comment by arundh93** [comment]
Any update on this issue?

**Comment by mistercrunch** [comment]
This should help https://github.com/apache/superset/pull/27055
