### ISSUE TITLE
[SIP-118] Ability to assign a unique asset id to a superset dashboard / visual

### ISSUE THREAD

**Issue by hondyman** [apache/superset#27194]
### Motivation
We need to provide information on various classified data used in reports to Regulatory bodies globally

Description of the problem to be solved.
In large regulated industries, we have to keep track of classified data for various global reporting such a PII for GDPR, financials metrics for Dodd/Frank and other regulatory bodies. We have to be able to say where / when and how certain data sets are used inside the org. To do this we assign an asset id (UUID) to each report, process and interface we report, xfer or export data from and we manage these through Data Governance.

### Proposed Change
Superset has metadata but its not editable, users should be able to add additional metadata to reports that allows for easier identification and governance. In our case we need to add an asset id to the metadata so we can track its usage.
I have provided a logical diagram of how we would see the process working in our org. The data catalog manages all our metadata so it will have an inventory of all dashboards power bi, superset and looker each is assigned an asset id and is actively managed by DG. 

Because superset uses integers inside an environment such as Dev, QA and prod the integers in each environment can be different. The asset id does not change between environments, its a consistent id thats callable from our portal.

![Screenshot 2024-02-21 1 20 16 PM](https://github.com/apache/superset/assets/54151500/a67202da-9f39-4103-9dbe-5b4bb34c5d22)

### New or Changed Public Interfaces

Typically our Data Governance tool assigns asset ids (UUID) and we push them into the various assets such as dashboards either manually or via api. If a new metadata area was exposed we will expect this to be available via Swagger API for insert, read and update.

### New dependencies

Not Applicable

### Migration Plan and Compatibility

Not Applicable

### Rejected Alternatives

Not Applicable

**Comment by webobite** [comment]
Hi @hondyman 
I would like this use case in more detail.
You are asking about a feature support which should be able to assign asset id to superset dashboard. I am not getting clear picture what would be usage of that with with your Database Governance Tool ?
Can you pls explain that part if possible ?

Thanks & Regards

**Comment by hondyman** [comment]
Hi Subham
The superset id right now is an integer and we develop reports in
development and bring to QA and production. Each report will have a
separate ID in each environment, as a regulated industry we need to keep
track of all reports and processes that have confidential and personal data
for global regulatory requirements. We do this by assigning an Asset ID
(UUID) that remains static in each environment and that is documented in
our Data Governance platform, even if we upgrade or change reports. What
I'm asking for is a JSON section where organizations can put metadata that
is important to them, in our case AssetID. Happy to walk through our use
case in more detail if that helps
Regards
-p




[image: Screenshot 2024-03-04 1.03.36 PM.png]

**Comment by webobite** [comment]
Thanks, seems interesting, I would like know more on this, Let me know if you are available on slack / or any other mean, would like to get some walk through about the same usecase @hondyman  :-)

**Comment by webobite** [comment]
@hondyman any update on this ? (in case you have missed)

**Comment by rusackas** [comment]
If anyone wants to move this forward, the next step is to create a [DISCUSS] thread on the dev@ mailing list.

**Comment by rusackas** [comment]
@mistercrunch FYI :)

**Comment by mistercrunch** [comment]
We do have a certain number of our core ORM models inherit a `uuid` through the `ImportExportMixin`

https://github.com/apache/superset/blob/master/superset/models/helpers.py#L171-L174

Idea being that when exporting/importing object across Superset environments, we need to be able to recognize that objects are the same while potentially having different ids.

Now we've talked about refactoring this many times over the years. Some related thoughts:
- would be great to factor a `UuidModelMixin` out of `ImportExportMixin`, so it could could used in other (all!) models that are not necessarily exportable/importable
- could be good to use the UUIDs as PKs and FKs too (instead of current auto-increment PKs), as it would greatly simlify export/import logic. Currently we have to do all sorts of lookup tables to figure stuff out. I think it has perf implications though as index become significantly larger - I could see someone arguing against that idea. 
- change the UI / API to be "UUID-native" and slowly deprecate exposing in of the internal auto-increment PKs as they expose a mild security threat, making it easy for user to guess urls and easily effectively scan through the data 
- seems you have a use case of forcing `uuids`, seems reasonable... assuming you'd need to be quite cautious about preserving referential integrity during update. Maybe export/re-import/deleting-orignals might make sense (?)

In terms of moving forward. A first, non-controversial step in that direction that wouldn't require a SIP [AFAIC] would be to:
- As mention, factor `UuidModelMixin` out of `ImportExportMixin` and into `superset/models/uuid.py`, make the second derive the former
- Move/create utility methods that are uuid-specific under this new `superset/models/uuid.py`
- spread across all models that could benefit from `uuid`, handle database migration to auto assign

**Comment by rusackas** [comment]
@hondyman any intention to move this through the SIP / ASF process? Let me know here or on [slack](http://bit.ly/join-superset-slack) if you want help.

**Comment by mistercrunch** [comment]
Here's a proof of concept if someone wants to run with it! https://github.com/apache/superset/pull/30398

**Comment by rusackas** [comment]
Anyone looking to move this proposal forward? If not, it will be closed in time.

**Comment by rusackas** [comment]
Closing this since we haven't heard from @hondyman in 8 months. Happy to re-open if anyone wants to take up the mantle, and the linked PRs can be adopted to pave the way.

**Comment by mistercrunch** [comment]
Pointing out that https://github.com/apache/superset/pull/30398 is ready for review/merge and is a bit related to the topic. Now looking at the issue as a whole, it was less about Superset providing a true uuid across instances (as the UuidMixin) implementation solves for - but more about allowing to enrich the Superset metadata with say a remote uuid from the metadata catalog. 

For that purpose, many ORM-backed tables implement the `ExtraJSONMixin` -> https://github.com/apache/superset/blob/master/superset/models/helpers.py#L595, which is used to store arbitrary object metadata without having to change the database model. This seems like a decent entry-point to allow say an external service to enrich any model with any metadata. Seems it'd be possible to add endpoint(s) that would enable reading/write arbitrary key/value pairs to any model backed by `ExtraJSONMixin`
