### ISSUE TITLE
Dashboard Filter Side

### ISSUE THREAD

**Issue by 12re34enes** [apache/superset#27210]
![filterbox](https://github.com/apache/superset/assets/155597786/260e0a07-ce70-4173-84b4-05ba57b326fe)

How can we move the Filters section to the right side? We need this for ease of use. Can you help us?

**Comment by rusackas** [comment]
You'd have to adjust the CSS layout of the dashboard view. IIRC, these are laid out with flexbox. You could do that on a fork, or, potentially open a PR to expand the menu for vertical/horizontal filters to be left/top/right. If you want to open a proposal or PR for that, we'd be happy to review it. Closing this now since it's a feature request rather than a bug :)
