### ISSUE TITLE
Error Cloning superset Repo

### ISSUE THREAD

**Issue by ColossalHub21** [apache/superset#27564]
### Bug description

When we try to clone the repo we getting this error

git clone https://github.com/apache/superset.git
Cloning into 'superset'...
remote: Enumerating objects: 431079, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (26/26), done.
error: RPC failed; curl 56 Recv failure: Connection reset by peer
error: 3327 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### How to reproduce the bug

git clone https://github.com/apache/superset.git

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment]
Hi @ColossalHub21. The error message "error: RPC failed; curl 56 Recv failure: Connection reset by peer" suggests a network connection problem. This can occur due to a variety of reasons such as a slow or unstable internet connection.
To troubleshoot this issue, you can try the following steps:
- Check your internet connection: Make sure you have a stable and reliable internet connection. If you are on a Wi-Fi network, try connecting to a different network or use a wired connection if possible.
- Retry the clone command: Sometimes the issue can be temporary, so it's worth trying the clone command again. You can do this by running the same clone command again.
- Check the repository server status: It's possible that the repository server may be experiencing issues. You can check the status of the server or contact the repository owner to see if there are any known issues.
- Use a VPN: If you are experiencing network issues due to restrictions or firewalls, you can try using a VPN service to bypass those restrictions.
