### ISSUE TITLE
Enabling partial text matches in dashboard filters

### ISSUE THREAD

**Issue by nkdanta1** [apache/superset#27929]
I want to use the dashboard filters to use a value for LIKE queries. Currently, if I add a filter for a column of type "Value" to a dashboard, I can only select a full value from the dropdown. It isn't possible to enter anything for partial text matches.

More details in discussion: https://github.com/apache/superset/discussions/25358

**Comment by johncassil** [comment]
Why was this closed? It is still a needed feature.

**Comment by rusackas** [comment]
The linked discussion is the right place to hash out a feature idea and try to recruit around it. We're attempting to keep GitHub Issues for bugs. Contributions are still quite welcome, if anyone wants to volunteer for this effort. Just note that we'll need _some form_ of configurability or RBAC control of this, since the implementation of this feature could cause performance and cost issues for many databases.
