### ISSUE TITLE
docker\.env-local not found

### ISSUE THREAD

**Issue by zhangle231** [apache/superset#28026]
### Bug description

quickstart 

docker-compose -f docker-compose-image-tag.yml up

docker\.env-local not found

### How to reproduce the bug

https://superset.apache.org/docs/quickstart

git clone https://github.com/apache/superset

docker-compose -f docker-compose-image-tag.yml up

docker\.env-local not found

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by wellingt21** [comment]
create your own .env-local, use .env as an example

**Comment by mistercrunch** [comment]
It wasn't my intention to make it required. Until  An empty file should do the trick until I find a better solution, so just `touch docker/.env-local` for now and you're back on track. 

For context the intention is allowing to put something in the filesystem that's .gitignored, so that there's no risk to push an API key or other local configurations.

**Comment by artofcomputing** [comment]
Ah that makes sense, it's due to Docker Compose making any environment file a hard requirement.

You can make the file optional by specifying it on the `required` attribute under `env_file`. It's a new feature in Compose 2.24.0 and afterwards. Here's the doc about it: https://docs.docker.com/compose/compose-file/05-services/#env_file

So to fix it, we just need to:

```yaml
  db:
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
```

On services that need it at [docker-compose-image-tag.yml](https://github.com/apache/superset/blob/2a62c40526510f23edd2ac032effd7e93081078d/docker-compose-image-tag.yml#L35-L40) and it should be good to go.

**Comment by mistercrunch** [comment]
Ok https://github.com/apache/superset/pull/28039 should address this issue

**Comment by mistercrunch** [comment]
Oh nice, I saw you message after I published my fix, I may keep it then, WDYT?

**Comment by artofcomputing** [comment]
Hm I think it would be really good to keep it as optional. It's a neat idea to have a .env-local for overrides, IMO makes customizing the environment much easier.
