### ISSUE TITLE
How to integrate  superset with zitadel for SSO login  

### ISSUE THREAD

**Issue by resulraveendran** [apache/superset#28055]
Hi ,

 There there any option for integrate superset with zitadel for SSO login .If there is any docs for there please share.Or We can do customize that Please give ther setps. I am using this  https://github.com/apache/superset.git repo. and doing docker install.

**Comment by rusackas** [comment]
Closing this in favor of https://github.com/apache/superset/issues/28058 since that's more actionable, and this would be better as a Q&A Discussion. In short, Preset allows you to write a custom security manager. Here's an entry point for some docs. https://superset.apache.org/docs/installation/configuring-superset/#custom-oauth2-configuration

**Comment by resulraveendran** [comment]
Hi,

     Hi I followed the same
