### ISSUE TITLE
Adjusting Font Size of Legend, Axes, and Value Labels in Apache Superset Dashboard

### ISSUE THREAD

**Issue by aprendizlaura** [apache/superset#28213]
Hello everyone!

I'm wondering if anyone knows if it's possible to adjust the font size of the legend, as well as the size of the axes and value labels in all the charts within a single dashboard on Apache Superset. Ideally, I'd like to customize these settings only for one dashboard instead of applying them to all dashboards. Additionally, if there's a way to modify the font size of the legend, axes, and value labels for individual charts within a dashboard, it would be incredibly helpful!

Any insights or suggestions would be greatly appreciated!

Thank you very much!

**Comment by rusackas** [comment]
Hi! Since this is more feature request than bug, we generally encourage folks to open a new thread in our [Github Discussions](https://github.com/apache/superset/discussions) area or join us on [slack](http://bit.ly/join-superset-slack). 

That said, the answer is effectively that this isn't built into Superset. We support [custom CSS](https://preset.io/blog/customizing-superset-dashboards-with-css/), and are on a path toward [theming](https://preset.io/blog/theming-superset-progress-update/), but CSS won't/can't work for many of the chart details you're asking for, and theming would (probably) start as a global override before it moves to dashboard-specific use. So... not easy right now! Sorry it's not the answer you were hoping for.
