### ISSUE TITLE
D3_FORMATS PROBLEM

### ISSUE THREAD

**Issue by iRoot13x18** [apache/superset#29251]
### Bug description

When I change the configuration of the superset_config.py file and I want to change the number format to European when I reboot to apply the changes nothing comes up.

### How to reproduce the bug

1. go to superset_config.py or config.py
2. add or edit this lines
- D3_FORMATS = {

    'NUMBER': {

        'thousands': '.',

        'decimal': ','

    },

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment]
`D3_FORMATS` isn't a thing, as far as I know. There is `D3_FORMAT` in config.py, but that takes the parameters for a single format, not an array or object of various formats like you seem to be using.

**Comment by fabgat** [comment]
Hi,
I've modified the D3FormatConfig.ts file, as per follow:
import { FormatLocaleDefinition } from 'd3-format';

export const DEFAULT_D3_FORMAT: FormatLocaleDefinition = {
  decimal: ',',
  thousands: '.',
  grouping: [3],
  currency: ['€', ''],
};

I've modified also the config.py:
# Override the default d3 locale format
# Default values are equivalent to
# D3_FORMAT = {
#     "decimal": ".",           # - decimal place string (e.g., ".").
#     "thousands": ",",         # - group separator string (e.g., ",").
#     "grouping": [3],          # - array of group sizes (e.g., [3]), cycled as needed.
#     "currency": ["$", ""]     # - currency prefix/suffix strings (e.g., ["$", ""])
# }
# https://github.com/d3/d3-format/blob/main/README.md#formatLocale
class D3Format(TypedDict, total=False):
    decimal: str
    thousands: str
    grouping: list[int]
    currency: list[str]

#D3_FORMAT: D3Format = {}

D3_FORMAT: D3Format = {
    "decimal": ",",
    "thousands": ".",
    "grouping": [3],
    "currency": ["€", ""]
}

no changes into: superset_config.py

After those activities I've restarted the docker, but everything is the same, no changes.

Where I'm wrong?

Regards

**Comment by rusackas** [comment]
@dosu-bot

**Comment by fabgat** [comment]
Thanks a lot.
Unfortunately also following your instructions, I'm not able to see deployed Italian D3.
I still see everything as before, even into drop down menu into charts menu, where I can choose a different "number formatting", into the drop down menu, I still see the original once.

**Comment by fabgat** [comment]
At the end, I've D3-format working.
To whom it may concern, here follows the two steps needed:
1) update the file: superset-frontend/src/setup/setupFormatters.ts
into that file, I've added the needed configuration:

    .registerValue('CURRENCY_ITALY', createD3NumberFormatter({
      locale: {
        decimal: ',',
        thousands: '.',
        grouping: [3],
        currency: ['€', ''],
      },
      formatString: '€.,2f',
    }))

after changing it, I proceed to build the frontend:
npm run build

D3_FORMAT = {
    "decimal": ",",
    "thousands": ".",
    "currency": ["€", ""],
    "grouping": [3],
}

After this I've build the new docker image as follow:

sudo docker build -t my-custom-superset-image .    <--- pay attention to not forget the "." at the end.

Now I got the choice into the dropdown menu into charts.
That's all.

Hope it helps.

**Comment by fabgat** [comment]
Now I'm trying to apply same number formatting to the export feature.
I've first added this into superset_config.py:
CSV_EXPORT = {"encoding": "utf-8", "sep": ";", "decimal": ",", "thousands": "."}

But when I try to download dashboard in CSV format, I receive this log:
NDFrame.to_csv() got an unexpected keyword argument 'thousands'

So I have removed "thousands" from superset_config.py and launched again superset.
Trying new conf, now I can download the csv but I only see that the new separator is: ":".

Decimal remained as ".".

Any ideas how to implement:
decimal ,
thousands .

Thanks

**Comment by sfirke** [comment]
There are many things going on in this issue, much of which have been resolved.  I'm going to close it because that makes issues not useful for bug tracking.  To recap + respond:
- How to change the comma separator of how Superset displays float numbers: people should be able to simply set `D3_FORMAT=` in their custom `superset_config.py` as covered in this discussion and the pull request it links to: https://github.com/apache/superset/discussions/29113  You should not have to change Superset's code and rebuild an image. If this isn't working please post in that discussion comments or on Slack.
  - The original poster of this GitHub issue had a problem caused by a typo, pluralizing the variable name.
- Changing the format of the export via CSV_EXPORT: @fabgat I agree with your approach of passing argument to pandas `DataFrame.to_csv` via the `CSV_EXPORT` config settings.  Looks like `thousands` is not a supported keyword, see the docs here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html  I think your best bet is to investigate the `float_format` argument, playing with it outside of Superset until you find the setting you need.
 
If you think this needs work, is a bug, or you have a contribution to make, feel free to post a new GitHub issue and tag me.  Or if you get it working, feel free to reply here with your solution or make a new GitHub Discussion and self-answer it so others can learn from it.
