### ISSUE TITLE
Oracle as Metadata- Not working

### ISSUE THREAD

**Issue by selvadinesh** [apache/superset#29295]
### Bug description

superset db upgrade 
superset init

This throws a lot of errors from missing columns in metadata tables, and foreign key issues. reserved keyword like row issue. 

I know we need to use MySQL and PostgreSQL. My firm wants to use Oracle. 

Any update ? 

### How to reproduce the bug

superset db upgrade 
superset init

### Superset version

4.0.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
> I know we need to use MySQL or PostgreSQL. My firm wants to use Oracle.

You have a good handle on this.  There is no plan to support Oracle as a metadata store DB, so I'm going to close this issue.  If you were to go that route and somehow get it working, there would be no community support available and it's always possible that subsequent changes would break something that previously worked.

I can relate, my org uses MS SQL Server exclusively for application DBs.  We decided that to set up a managed PostgreSQL DB in order to use Superset.  For what it's worth, the amount of knowledge of PostgreSQL needed to maintain a Superset instance is very low.
