### ISSUE TITLE
Remove or make less prominent legacy contributing guide

### ISSUE THREAD

**Issue by MialLewis** [apache/superset#29596]
There is a link to an outdated contributing guide here: https://github.com/apache/superset/blob/master/docs/docs/contributing/contributing.mdx?plain=1#L22

It is likely the first link to a contributing guide a user see's when following the link specified in [CONTRIBUTING.md](https://github.com/apache/superset/blob/master/CONTRIBUTING.md).

This guide leads users down the likely painful path of trying to set up a developer environment without docker compose, as I have just experienced.

This link should be removed, moved to a less prominent position and/or a warning added with a link to the relevant up to date page which is available in the side bar menu.

**Comment by sfirke** [comment]
Thanks for pointing this out.  Just to be clear, you are saying the problem is the link to https://preset.io/blog/tutorial-contributing-code-to-apache-superset/ because that blog post is obsolete - correct me if that's not right.

An easy fix would be to remove that link.  I wonder if that content would have been better off as part of the official docs, where it would be easier to keep updated.  I'm fine with removing that link, but will also ping @mistercrunch and @rusackas as people who have thoughts about developer docs and the Preset blog.

**Comment by rusackas** [comment]
Fine by me to remove it. I opened a PR to do so. 

In a perfect world, we'd have the bandwidth to go back and change all our old blog posts to keep them fresh and current, but that's more than a full time job at this point, so we're probably better off treating them as time capsules, like so many blogs do. If anything, it's probably time for a NEW blog post on the topic!

**Comment by MialLewis** [comment]
Thanks both.
