### ISSUE TITLE
Placeholders and "select all" option of select filters are missing localization

### ISSUE THREAD

**Issue by torbenw** [apache/superset#30160]
## Screenshot

![grafik](https://github.com/user-attachments/assets/99abec7e-a864-4576-b7b0-ef1153239631)

## Description

When changing the language to German the text of the placeholder and "select all" option are not localized.

"2 options" -> "2 Optionen"
"Select All (2)" -> "Alle auswählen (2)"

**Comment by torbenw** [comment]
```
msgid "Select all data"
msgstr "Alle Daten auswählen"

msgid "Select all items"
msgstr "Alle Elemente auswählen"
```
Those exist and are translated to German already, but are not used for the select filter.

For the placeholder it might just be a change to this line, but I was not able to test this yet, because I cannot build the project.

```
#, fuzzy, python-format
msgid "%s option"
msgid_plural "%s options"
msgstr[0] "%s Option"
msgstr[1] ""
```

Maybe change to this?

```
#, fuzzy, python-format
msgid "%s option"
msgid_plural "%s options"
msgstr[0] "%s Option"
msgstr[1] "%s Optionen"
```

**Comment by rusackas** [comment]
Yep, I think you're on to it. Just make sure you're changing the translation in the .`po` file, not the `.pot` or `.json/.mo` files.

Closing this since we don't treat missing translations as bugs (if we did, we'd have several thousand bugs!). If you could open a PR with your changes, we'd be grateful and happy to review it! Thanks for calling this out and looking into the fix!

**Comment by torbenw** [comment]
I can currently only run Superset in Docker via the latest images, because I failed to get it compiled/running from source. I tried to get my changes to the .mo file applied there, but was not successful.
