### ISSUE TITLE
`show summary` does not correctly apply all filters

### ISSUE THREAD

**Issue by mapledan** [apache/superset#30193]
### Bug description

In the changes introduced in #28057 ([code](https://github.com/apache/superset/pull/28057/files#diff-0186dcc4a861c06db2a94660bfcd32fb3301eee43a0d9c16e8e3b592ad7f8fc1R248)), all parameters are discarded when passing extras. However, the custom SQL filters are set within the extras, leading to an issue where the show summary feature does not correctly apply these filters, as illustrated in the attached image.

### How to reproduce the bug

1. Set the filter using custom SQL.
2. Select the show summary option.
3. Observe that the summary of the query results does not apply the filter.

### Screenshots/recordings

![image](https://github.com/user-attachments/assets/99120ebf-1202-4ac5-b79e-ed24f62d1d9f)

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mapledan** [comment]
My version is already 4.1.0rc2.

**Comment by round3d** [comment]
@dosu 
@mapledan  is correct. 
The bug is at 
https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-table/src/buildQuery.ts#L204 for time comparison where the extras args is cleared when it has timeoffsets. The keeps any custom sql filters from being included in the generated query.

It is the similar for Show summary where the extraQueries doesn't include the extras args assuming it is only for time grains. 
https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-table/src/buildQuery.ts#L242

**Comment by Antonio-RiveroMartnez** [comment]
Thanks for reporting this @mapledan! I assigned it to me so I can work on a fix for it

**Comment by michael-s-molina** [comment]
Just for reference, take a look at this discussion: https://github.com/apache/superset/discussions/29297

**Comment by michael-s-molina** [comment]
Hi @Antonio-RiveroMartnez. My main objective in sharing that discussion is to highlight that the Summary will not necessarily match what's displayed in the table because of limits/pagination constraints. That being said, we still need to fix the issue reported here.

> does that means only the tooltip was to change and the computation must remain as is -- except for the extras that will be fixed as part of this issue --?

Exactly.
