### ISSUE TITLE
Bar Chart sorting does not appear to work

### ISSUE THREAD

**Issue by HJelinkova** [apache/superset#30238]
### Bug description

It is imposible to change the layout of the bar chart by using the "Sort by" function. 
The ASC/DESC checkbox changes the query but the chart stays unaffected. 

Same issues previously reported: #15260, #15318

### How to reproduce the bug

1. Create a bar chart.
2. In the "Data" tab find the "Sort by" section.
3. Choose the column and the aggregate by which you want to sort the data by.
4. Tick/Untick the "Sort descending" checkbox.

### Screenshots/recordings

![Bar chart bug (1)](https://github.com/user-attachments/assets/b9943f63-e1aa-460c-9e78-94385cb645c3)
![Bar chart bug (2) ](https://github.com/user-attachments/assets/ad42d47b-7bd6-4ac7-b942-eba2073ce2b3)
![Bar chart bug - query (1)](https://github.com/user-attachments/assets/f5dc5e75-5e2f-4364-aaca-b2376f4d1d4b)
![Bar chart bug - query (2)](https://github.com/user-attachments/assets/62227fe1-939c-467f-8d5c-a2fe0588349f)

### Superset version

4.0.2

### Python version

Python 3.10.14

### Node version

NODE version 20

### Browser

Chrome

### Additional context

Note: Superset installed using docker. 

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
If you read the mouseover tooltip for SORT BY you'll see that's for something else.  That should probably be labeled as "DATA LIMIT SORT BY".  What you need is X-AXIS SORT BY, which switches to Y-AXIS SORT BY when a bar chart is switched to horizontal orientation as it appears yours is.  I don't know why you don't see that option in your screenshot; are you positive you're running Superset 4.0.2?

Here's what it looks like for me.  With the default sorting:
![image](https://github.com/user-attachments/assets/1da3d002-dd28-4931-9f8c-bd27b35cf9e5)

Sorting by a specific metric changes the bars' order:
![image](https://github.com/user-attachments/assets/dfc42a08-2f16-4ea2-8a22-f4d48b2a5433)

**Comment by HJelinkova** [comment]
Thank you for your reply. I have now figured out what the problem was.  The X-AXIS SORT BY (Y-AXIS SORT BY) didn't appear because of the data type of the column. It only works for STRING data type whilst mine is VAR_STRING.

**Comment by mahesh-babu-drivex** [comment]
> Thank you for your reply. I have now figured out what the problem was. The X-AXIS SORT BY (Y-AXIS SORT BY) didn't appear because of the data type of the column. It only works for STRING data type whilst mine is VAR_STRING.

How can you change the column type to string? @HJelinkova

**Comment by pedrosubei** [comment]
> > Thank you for your reply. I have now figured out what the problem was. The X-AXIS SORT BY (Y-AXIS SORT BY) didn't appear because of the data type of the column. It only works for STRING data type whilst mine is VAR_STRING.
> 
> How can you change the column type to string? [@HJelinkova](https://github.com/HJelinkova)

Did you find how? (i am using version 4.0.2 and that option doesn't apear)

**Comment by rbosnjak** [comment]
Hello!

I'm dealing with the same issue. While I'm still not able to find out how to sort x-axis of bar chart based on some metric, while not showing it on the chart, I found a way how to create STRING column from VAR_STRING.

To do this, you should open Edit dataset screen, and select "CALCULATED COLUMNS" tab. There you need to enter SQL expression, which will probably be just the name of the varchar column you want to  convert.  This will create a new column in your dataset, which is marked as String.

I'm attaching 2 screenshots where this beahviour is visible.

![Image](https://github.com/user-attachments/assets/8934dd34-8f70-4a1d-ae87-368613115d28)

![Image](https://github.com/user-attachments/assets/3e44937f-8d02-424c-beb9-1a2b9d97b523)


Now, Sorting option really appears on the screen, as mentioned in the comments above. 

![Image](https://github.com/user-attachments/assets/516ecd82-983b-4ccf-b8eb-82187e49c5c5)

![Image](https://github.com/user-attachments/assets/fdfe85e3-f3be-44f4-aec1-09376639bd4c)

The next thing I would like to achieve is custom sorting, based on a column which is not shown neither on x-axis or inside bar chart values (metrics field). 

In my scenario, I have x-axis which is formed out of dates and Identification Numbers of subjects I am analyzing. The date is in the following format: `%d.%m.%Y.` - for example `31.12.2024.`. The identification number is 11 digit number. So in the end I get x-axis value like `31.12.2024. 12345678901`.

I would want to sort these on x-axis, but based on `YYYY-mm-dd` date format, since string sort does not work correctly on my time format. Note that I already track some metric for each date-subject, and I cannot add any new metric to the barchart to be visible.

![Image](https://github.com/user-attachments/assets/848eaeb6-d61a-40c2-8868-7c0163c4e553)

Does anyone know how I could achieve this?

**Comment by rbosnjak** [comment]
Hello, and thanks for answering!

I see what you're saying—probably I should have explained it better from the start.

My x-axis can't be a temporal column because it's a string created using `CONCAT(date_in_d_m_y_format, '\n', subject_id)`. 
I did it this way because I need to show one bar per day per subject.
Without concatenating the `subject_id` to the date, Superset would aggregate all subjects at the daily level.

Here's a screenshot that shows how the x-axis values actually look in one example
![Image](https://github.com/user-attachments/assets/1e2182d3-a151-4c8c-85fe-0733bc25380a)
