### ISSUE TITLE
Histogram chart not able to use decimal datatype column

### ISSUE THREAD

**Issue by clavidk** [apache/superset#30301]
### Bug description

When I try to create a Histogram chart and choose a decimal datatype column (e.g. `start_rate` in my scenario)as the main column, I get an error that says:

> The column 'start_rate' must be numeric.

But I have checked that it is a decimal datatype (Postgres db) which is equivalent to the `numeric` datatype.

### How to reproduce the bug

1. Create a new Histogram chart (not the legacy version)
2. For column,  select the column that is a decimal data type.
3. Click save/update chart

What I expect: histogram is created

What actually happens: I get the following error:

> DB engine Error
> The column 'start_rate' must be numeric.
> 
> This may be triggered by:
> Issue 1011 - Superset encountered an unexpected error. 
> 
> Please reach out to the Chart Owner for assistance.
> 
> Chart Owner: Superset Admin

### Screenshots/recordings

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/292c92fb-0b70-402a-96ff-fcea0b4386a3">

### Superset version

master / latest-dev

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by BlakeList** [comment]
Even if the columns are correctly set to numeric datatypes in the database, Superset still doesn't interpret this properly (converts to `decimal` type). 

One way around this is to convert/cast the column to `FLOAT` or `REAL` data type (not `NUMERIC`) in your SQL query that produces the dataset in Superset. This is then interpreted as a `float` type in Superset and can be used in the current histogram visualization. 

Hopefully this can be solved on Superset's end, but otherwise I hope it helps with your problem for now :)

**Comment by clavidk** [comment]
@BlakeList This worked, thanks for that tip!  

Though it seems it surfaced a new issue in that the histogram chart only creates bin delineations at whole integer numbers and doesn't play nicely when a lot of the values are <1 e.g. 0.33)
