### ISSUE TITLE
Show User: Inconsistent capitalisation on page headings

### ISSUE THREAD

**Issue by praveer38** [apache/superset#30515]
### Bug description

On the Show User page, there is inconsistent capitalisation for the section headings.

User info

Personal Info

Audit Info

“User info” should be changed to “User Info” to keep the capitalisation consistent.
<img width="454" alt="image" src="https://github.com/user-attachments/assets/982ac18c-40e6-49a0-8b2b-283ec73aff5c">

### Screenshots/recordings

<img width="454" alt="image" src="https://github.com/user-attachments/assets/45fc6eb1-2d4a-4bbb-8751-e3152cb00095">

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment]
Hello @praveer38 : this is an issue with Flask-AppBuilder.  Superset uses FAB for much of its code, including security.  You would need to change the line [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/1d27eb42a4f9b6e19fb3c025327b4110b175eccb/flask_appbuilder/security/views.py#L194) and [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/1d27eb42a4f9b6e19fb3c025327b4110b175eccb/flask_appbuilder/security/views.py#L219).

Could you please submit that change as a pull request to that repository?  To be complete I guess you should also change https://github.com/dpgaspar/Flask-AppBuilder/blob/1d27eb42a4f9b6e19fb3c025327b4110b175eccb/examples/quickhowto2/app/sec_views.py#L14 and maybe capitalize it in the translations files too.  Basically search the repository for "User info" and where exactly that string occurs, make the appropriate substitution.

That's as far as this relates to Superset.  I'm going to close this because it's not an actionable bug for this project.
