### ISSUE TITLE
Time Out in querys superset

### ISSUE THREAD

**Issue by carza06** [apache/superset#30741]
### Bug description

The waiting time of my superset is 60sec, is it possible to increase this value?

### Superset version

4.0.2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by carza06** [comment]
where is superset_config.py in the repository?

**Comment by ascendlin** [comment]
> where is superset_config.py in the repository? @dosu

see：https://superset.apache.org/docs/configuration/configuring-superset

**Comment by rusackas** [comment]
`SUPERSET_WEBSERVER_TIMEOUT` is also in `config.py`, so you can set it there. `superset_config.py` is an override option. You can read about it [here](https://superset.apache.org/docs/configuration/configuring-superset/#superset_configpy). Closing this since it's not a bug, and I believe this answers the question :)
