### ISSUE TITLE
Filter Bar: Move "Add/Edit Filters" to the Gear Icon

### ISSUE THREAD

**Issue by yousoph** [apache/superset#30876]
Requirements: 
* On both horizontal and vertical orientation dashboard filters, remove the blue "+ Add/Edit Filters" button
* In the settings icon (on both orientations), add "Add or edit filters" to the top of the menu (note the copy change from current and note the capitalization)
* Add a divider to separate the "Add or edit filters" button from the rest of the current menu (same type of divider that is used above the "Orientation of filter bar" option) 
* New "Add or edit filters" button should open the same menu that the current button opens

![Image](https://github.com/user-attachments/assets/eb7be613-a699-4f12-8c84-008cada31925)
![Image](https://github.com/user-attachments/assets/80d38fd5-0745-4317-9260-fcd4fb4d35e6)

**Comment by samarsrivastav** [comment]
hey @yousoph !! I would love to work on this issue

**Comment by rusackas** [comment]
Just thinking here about how to make the UX a little simpler... not that we need another project. But, just to say it out loud in case @kasiazjc thinks it's a good idea for a rainy day:

Tha add/edit filters modal has always bothered me... from the button/menu in the top, to the fact that I accidentally overwrite filters instead of adding them, ALL THE TIME. 

I wonder if we could fix that by just having "Add Filter" appear in the gear menu. Then add "Edit" icons when you hover over each _existing_ filter. The Add modal and the Edit modal would essentially be the same UI, aside from a "delete" button when editing.

If I'm not mistaken, this would actually let us chop out a fair bit of code/logic in that modal. We'd just need to make them re-arrangeable in the dashboard setting, which kind of makes sense to me if (a) that's where all the dragg/drop stuff happens anyway, and (b) we might make it so you can drag them into the dashboard one day.

**Comment by alexandrusoare** [comment]
I am interested in taking this one
