### ISSUE TITLE
[SIP] Adding a more granular write permission for database connections

### ISSUE THREAD

**Issue by Hen0k** [apache/superset#30957]
*Please make sure you are familiar with the SIP process documented*
[here](https://github.com/apache/superset/issues/5602). The SIP will be numbered by a committer upon acceptance.

### Motivation

I want my users to be able to add new google sheets to a pre-existing Google Sheet database I created with a test sheet connection. I am managing this capability with a custom role. It only works if I enable the "Can Write on Database" permission. This allow the user with this role to edit the connection, and add another sheet/table to the database. But this also allows them to edit and delete other database connections. 

### Proposed Change

I propose a new permission that allowed write access to individual databases instead of allowing edit on all databases connections.

**Comment by rusackas** [comment]
If you want to go this route, it seems plausible, but I think we'd need a little more explanation (i.e. filling out the rest of the SIP template) so we know all the use cases, whether or not this is useful to other database connection types, and if you've explored the alternatives, which might include:
• Having users add _additional_ GSheet connections rather than tweaking a single pre-existing one
• Using an intermediary query engine to deal with administrating rights to add/edit GSheet connections (Trino, Presto, Drill, Shillelagh, etc)

**Comment by rusackas** [comment]
OK. I'll close this out since it doesn't meet the SIP guidelines, and it doesn't sound like there's an implementation plan here. 

I think adding granular (per-db) write permissions may be considered in https://github.com/apache/superset/issues/28377 which seeks to expand the flexibility/specificity of the current security model. You can certainly add a comment on that thread if you'd like.
